++ ls caseresult/ -ltr
++ wc -l
+ filename=case19
+ mkdir caseresult/case19
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case19
+ TEN=10
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case19.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 33.9570 seconds

0 row(s) in 0.8190 seconds

0 row(s) in 0.0680 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', BLOOMFILTER=>'\''ROW'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'BLOOMFILTER=>'\''ROW'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case19/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case19/create_1.script
/home/hadoop/git/physical_design/caseresult/case19/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case19/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 1.5970 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404660795
1404660795
++ echo /home/hadoop/git/physical_design/caseresult/case19/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case19/load_1.dat
Loading workload...
Starting test.
2014-07-06 08:33:16:114 0 sec: 0 operations; 
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:33:16 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x46f91a48, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:33:16 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x46f91a48 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:33:16 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:33:16 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 08:33:16 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c495153000d, negotiated timeout = 90000
2014-07-06 08:33:26:118 10 sec: 286436 operations; 28632.15 current ops/sec; [INSERT AverageLatency(us)=317.45] 
2014-07-06 08:33:36:121 20 sec: 291132 operations; 469.46 current ops/sec; [INSERT AverageLatency(us)=56.78] 
2014-07-06 08:33:46:122 30 sec: 291132 operations; 0 current ops/sec;  
2014-07-06 08:33:56:123 40 sec: 291132 operations; 0 current ops/sec;  
2014-07-06 08:34:06:123 50 sec: 469522 operations; 17839 current ops/sec; [INSERT AverageLatency(us)=1042.29] 
14/07/06 08:34:15 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2244 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10039 ms, replay 2244 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2258 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10013 ms, replay 2258 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2315 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10072 ms, replay 2315 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10082 ms, replay 2281 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2231 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10064 ms, replay 2231 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10025 ms, replay 2310 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10036 ms, replay 2257 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10066 ms, replay 2237 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10083 ms, replay 2268 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2265 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10033 ms, replay 2265 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2313 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10068 ms, replay 2313 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10028 ms, replay 2310 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2261 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10009 ms, replay 2261 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2299 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10084 ms, replay 2299 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2307 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10080 ms, replay 2307 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2222 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10099 ms, replay 2222 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 10097 ms, replay 2255 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10080 ms, replay 2296 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10051 ms, replay 2253 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2298 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10024 ms, replay 2298 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2282 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10017 ms, replay 2282 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2339 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10025 ms, replay 2339 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2218 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10038 ms, replay 2218 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10068 ms, replay 2279 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2243 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10080 ms, replay 2243 ops.
14/07/06 08:34:15 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10031 ms, replay 2235 ops.
2014-07-06 08:34:16:124 60 sec: 718468 operations; 24892.11 current ops/sec; [INSERT AverageLatency(us)=114.06] 
14/07/06 08:34:17 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2264 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10051 ms, replay 2264 ops.
14/07/06 08:34:17 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2240 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10061 ms, replay 2240 ops.
14/07/06 08:34:17 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2312 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10087 ms, replay 2312 ops.
14/07/06 08:34:17 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 10072 ms, replay 2250 ops.
14/07/06 08:34:17 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2270 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:39879 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 10074 ms, replay 2270 ops.
2014-07-06 08:34:26:125 70 sec: 718468 operations; 0 current ops/sec;  
14/07/06 08:34:30 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2264 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10065 ms, replay 2264 ops.
14/07/06 08:34:30 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2270 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 10031 ms, replay 2270 ops.
14/07/06 08:34:30 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2240 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10007 ms, replay 2240 ops.
14/07/06 08:34:30 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2243 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10018 ms, replay 2243 ops.
14/07/06 08:34:30 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2222 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10099 ms, replay 2222 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10018 ms, replay 2268 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10068 ms, replay 2296 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 10038 ms, replay 2255 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10014 ms, replay 2257 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2312 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10022 ms, replay 2312 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10003 ms, replay 2253 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10068 ms, replay 2281 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10079 ms, replay 2279 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2261 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10032 ms, replay 2261 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2265 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10093 ms, replay 2265 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2235 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10004 ms, replay 2235 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2250 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 10034 ms, replay 2250 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2339 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10067 ms, replay 2339 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2218 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10009 ms, replay 2218 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2282 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10042 ms, replay 2282 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10051 ms, replay 2237 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2313 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10000 ms, replay 2313 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2244 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 10038 ms, replay 2244 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2307 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10076 ms, replay 2307 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2258 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10009 ms, replay 2258 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2298 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10083 ms, replay 2298 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2299 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10084 ms, replay 2299 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2231 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10064 ms, replay 2231 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10085 ms, replay 2310 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2315 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 10066 ms, replay 2315 ops.
14/07/06 08:34:32 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 10070 ms, replay 2310 ops.
2014-07-06 08:34:36:125 80 sec: 723164 operations; 469.6 current ops/sec; [INSERT AverageLatency(us)=3124.27] 
14/07/06 08:34:42 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2240 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=792, waitTime=2052, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20015 ms, replay 2240 ops.
14/07/06 08:34:42 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2270 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=792, waitTime=2052, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 20154 ms, replay 2270 ops.
14/07/06 08:34:42 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=792, waitTime=2052, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20177 ms, replay 2243 ops.
14/07/06 08:34:42 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=795, waitTime=2002, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20166 ms, replay 2264 ops.
14/07/06 08:34:43 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2222 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2473, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20067 ms, replay 2222 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2253 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20177 ms, replay 2253 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20110 ms, replay 2296 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2237 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20138 ms, replay 2237 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20006 ms, replay 2279 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2244 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20032 ms, replay 2244 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2250 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 20129 ms, replay 2250 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2282 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20160 ms, replay 2282 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2339 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20124 ms, replay 2339 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2258 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20122 ms, replay 2258 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 20153 ms, replay 2255 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20141 ms, replay 2310 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2299 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20089 ms, replay 2299 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2231 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20114 ms, replay 2231 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2265 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20087 ms, replay 2265 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20194 ms, replay 2268 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2312 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20004 ms, replay 2312 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2310 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20006 ms, replay 2310 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2235 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20108 ms, replay 2235 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2315 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20136 ms, replay 2315 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2257 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20045 ms, replay 2257 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2298 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20056 ms, replay 2298 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2218 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20153 ms, replay 2218 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2313 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20160 ms, replay 2313 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2261 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20168 ms, replay 2261 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2307 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20140 ms, replay 2307 ops.
14/07/06 08:34:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2281 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20073 ms, replay 2281 ops.
2014-07-06 08:34:46:218 90 sec: 723164 operations; 0 current ops/sec;  
2014-07-06 08:34:56:218 100 sec: 723164 operations; 0 current ops/sec;  
14/07/06 08:35:03 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:35:03 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014
14/07/06 08:35:03 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:35:03 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:35:03 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
2014-07-06 08:35:06:219 110 sec: 723164 operations; 0 current ops/sec;  
14/07/06 08:35:08 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20184 ms, replay 2279 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2312 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:40002 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20093 ms, replay 2312 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20145 ms, replay 2310 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20018 ms, replay 2218 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20136 ms, replay 2313 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20034 ms, replay 2261 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 20166 ms, replay 2255 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20014 ms, replay 2257 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 20091 ms, replay 2250 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20088 ms, replay 2253 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2282 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20008 ms, replay 2282 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2231 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20108 ms, replay 2231 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2244 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20156 ms, replay 2244 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2307 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20185 ms, replay 2307 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20184 ms, replay 2235 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20140 ms, replay 2268 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20043 ms, replay 2296 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20014 ms, replay 2298 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20012 ms, replay 2258 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2281 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20172 ms, replay 2281 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20176 ms, replay 2310 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20021 ms, replay 2237 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20008 ms, replay 2265 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2339 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20056 ms, replay 2339 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2315 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20119 ms, replay 2315 ops.
14/07/06 08:35:08 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2299 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=882, waitTime=2509, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20131 ms, replay 2299 ops.
2014-07-06 08:35:16:220 120 sec: 723164 operations; 0 current ops/sec;  
2014-07-06 08:35:26:221 130 sec: 864044 operations; 14085.18 current ops/sec; [INSERT AverageLatency(us)=1945.53] 
14/07/06 08:35:28 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:35:28 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:35:31 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:35:31 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20071 ms, replay 2261 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20087 ms, replay 2257 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20151 ms, replay 2218 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20180 ms, replay 2237 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20022 ms, replay 2298 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014, retrying after 20071 ms, replay 2250 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2315 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20140 ms, replay 2315 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20178 ms, replay 2265 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2231 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20134 ms, replay 2231 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2307 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20138 ms, replay 2307 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 20106 ms, replay 2255 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20144 ms, replay 2268 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2244 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20032 ms, replay 2244 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20084 ms, replay 2310 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20064 ms, replay 2258 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2299 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20192 ms, replay 2299 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2339 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20041 ms, replay 2339 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2281 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20097 ms, replay 2281 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20179 ms, replay 2296 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20083 ms, replay 2310 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20132 ms, replay 2253 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20193 ms, replay 2313 ops.
14/07/06 08:35:31 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1005, waitTime=2664, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20124 ms, replay 2235 ops.
2014-07-06 08:35:36:222 140 sec: 962660 operations; 9860.61 current ops/sec; [INSERT AverageLatency(us)=1663.79] 
2014-07-06 08:35:46:223 150 sec: 1128512 operations; 16585.2 current ops/sec; [INSERT AverageLatency(us)=352.47] 
14/07/06 08:35:53 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:25 PDT 2014
14/07/06 08:35:53 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2339 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20106 ms, replay 2339 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20146 ms, replay 2258 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2268 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20037 ms, replay 2268 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20146 ms, replay 2235 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2281 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20002 ms, replay 2281 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2231 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20062 ms, replay 2231 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20052 ms, replay 2298 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20057 ms, replay 2257 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20183 ms, replay 2261 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20069 ms, replay 2265 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20168 ms, replay 2237 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20099 ms, replay 2296 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20126 ms, replay 2310 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2307 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20028 ms, replay 2307 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20180 ms, replay 2253 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2299 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20075 ms, replay 2299 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20185 ms, replay 2313 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2315 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20055 ms, replay 2315 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20172 ms, replay 2218 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20128 ms, replay 2310 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 20195 ms, replay 2255 ops.
14/07/06 08:35:53 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2244 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1153, waitTime=2333, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20182 ms, replay 2244 ops.
2014-07-06 08:35:56:223 160 sec: 1225636 operations; 9711.43 current ops/sec; [INSERT AverageLatency(us)=426.52] 
2014-07-06 08:36:06:224 170 sec: 1365159 operations; 13950.9 current ops/sec; [UPDATE AverageLatency(us)=1428406] [INSERT AverageLatency(us)=354.05] [CLEANUP AverageLatency(us)=1428676.33] 
14/07/06 08:36:15 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:36:15 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:15 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1340, waitTime=2025, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20141 ms, replay 2298 ops.
14/07/06 08:36:15 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:16 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:36:16 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2315 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20131 ms, replay 2315 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2299 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20080 ms, replay 2299 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #1, table=usertable, attempt=16/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20107 ms, replay 2265 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2231 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20163 ms, replay 2231 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20095 ms, replay 2296 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2339 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20009 ms, replay 2339 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20150 ms, replay 2310 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20035 ms, replay 2310 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20007 ms, replay 2258 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20034 ms, replay 2235 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014, retrying after 20190 ms, replay 2255 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #3, table=usertable, attempt=16/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20057 ms, replay 2253 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2313 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014, retrying after 20187 ms, replay 2313 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #1, table=usertable, attempt=16/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20120 ms, replay 2261 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 failed 2237 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20017 ms, replay 2237 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 2218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20075 ms, replay 2218 ops.
14/07/06 08:36:16 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2257 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1341, waitTime=2159, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20060 ms, replay 2257 ops.
2014-07-06 08:36:16:225 180 sec: 1474280 operations; 10911.01 current ops/sec; [UPDATE AverageLatency(us)=798123] [INSERT AverageLatency(us)=1648.5] [CLEANUP AverageLatency(us)=798148] 
2014-07-06 08:36:26:226 190 sec: 1620969 operations; 14667.43 current ops/sec; [UPDATE AverageLatency(us)=636094] [INSERT AverageLatency(us)=95.85] [CLEANUP AverageLatency(us)=636117] 
2014-07-06 08:36:36:226 200 sec: 1716002 operations; 9503.3 current ops/sec; [UPDATE AverageLatency(us)=386876] [INSERT AverageLatency(us)=81.85] [CLEANUP AverageLatency(us)=386896] 
14/07/06 08:36:37 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #17, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #3, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:22 PDT 2014
14/07/06 08:36:37 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:24 PDT 2014
14/07/06 08:36:38 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:38 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 failed 2310 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20049 ms, replay 2310 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2296 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20036 ms, replay 2296 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 failed 2299 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20176 ms, replay 2299 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 failed 2218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20181 ms, replay 2218 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:38 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20027 ms, replay 2235 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #1, table=usertable, attempt=17/35 failed 2265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1481, waitTime=2075, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014, retrying after 20095 ms, replay 2265 ops.
14/07/06 08:36:38 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:38 INFO client.AsyncProcess: #1, table=usertable, attempt=17/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1489, waitTime=2132, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014, retrying after 20100 ms, replay 2261 ops.
2014-07-06 08:36:46:227 210 sec: 1997762 operations; 28173.18 current ops/sec;  [INSERT AverageLatency(us)=5745.28]  
2014-07-06 08:36:56:228 220 sec: 2326482 operations; 32868.71 current ops/sec;  [INSERT AverageLatency(us)=247.03]  
14/07/06 08:36:59 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #10, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #16, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #1, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:23 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #13, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #14, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
14/07/06 08:36:59 INFO client.AsyncProcess: #1, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:33:18 PDT 2014
2014-07-06 08:37:06:231 230 sec: 2673986 operations; 34739.98 current ops/sec;  [INSERT AverageLatency(us)=4021.44]  
2014-07-06 08:37:16:231 240 sec: 2697466 operations; 2348 current ops/sec;  [INSERT AverageLatency(us)=228.95]  
2014-07-06 08:37:26:232 250 sec: 2697466 operations; 0 current ops/sec;    
2014-07-06 08:37:36:233 260 sec: 2697466 operations; 0 current ops/sec;    
2014-07-06 08:37:46:233 270 sec: 2819562 operations; 12209.6 current ops/sec;  [INSERT AverageLatency(us)=1002.12]  
2014-07-06 08:37:56:234 280 sec: 2927570 operations; 10799.72 current ops/sec;  [INSERT AverageLatency(us)=298.85]  
14/07/06 08:37:59 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2229 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10048 ms, replay 2229 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2251 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:02 PDT 2014, retrying after 10092 ms, replay 2251 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10041 ms, replay 2273 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2291 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10068 ms, replay 2291 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10007 ms, replay 2247 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2228 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014, retrying after 10066 ms, replay 2228 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10030 ms, replay 2275 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10081 ms, replay 2235 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014, retrying after 10008 ms, replay 2298 ops.
14/07/06 08:37:59 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2307, waitTime=2990, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:02 PDT 2014, retrying after 10040 ms, replay 2277 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10097 ms, replay 2277 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10095 ms, replay 2290 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2252 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10048 ms, replay 2252 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10079 ms, replay 2287 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2258 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014, retrying after 10007 ms, replay 2258 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2240 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10059 ms, replay 2240 ops.
14/07/06 08:38:00 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2336, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:06 PDT 2014, retrying after 10090 ms, replay 2272 ops.
2014-07-06 08:38:06:235 290 sec: 3026186 operations; 9860.61 current ops/sec;  [INSERT AverageLatency(us)=929.45]  
14/07/06 08:38:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:02 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:02 PDT 2014
14/07/06 08:38:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014
14/07/06 08:38:13 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:04 PDT 2014
14/07/06 08:38:13 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014
14/07/06 08:38:13 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2435, waitTime=2000, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10098 ms, replay 2277 ops.
14/07/06 08:38:13 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
14/07/06 08:38:13 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2436, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 10072 ms, replay 2290 ops.
14/07/06 08:38:13 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2436, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:06 PDT 2014, retrying after 10071 ms, replay 2272 ops.
14/07/06 08:38:13 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2436, waitTime=2036, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 10036 ms, replay 2287 ops.
2014-07-06 08:38:16:236 300 sec: 3228114 operations; 20190.78 current ops/sec;  [INSERT AverageLatency(us)=2282.89]  
14/07/06 08:38:25 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:06 PDT 2014
14/07/06 08:38:25 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2598, waitTime=2079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 20137 ms, replay 2287 ops.
14/07/06 08:38:25 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2598, waitTime=2079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 20060 ms, replay 2277 ops.
14/07/06 08:38:25 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2598, waitTime=2079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 20181 ms, replay 2290 ops.
2014-07-06 08:38:26:236 310 sec: 3445243 operations; 21712.9 current ops/sec;  [INSERT AverageLatency(us)=423.33]  
2014-07-06 08:38:36:237 320 sec: 3681156 operations; 23588.94 current ops/sec; [UPDATE AverageLatency(us)=5396221] [INSERT AverageLatency(us)=716.1] [CLEANUP AverageLatency(us)=5396255] 
2014-07-06 08:38:46:239 330 sec: 3893589 operations; 21239.05 current ops/sec; [UPDATE AverageLatency(us)=6670063] [INSERT AverageLatency(us)=513.97] [CLEANUP AverageLatency(us)=6670089] 
14/07/06 08:38:48 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
14/07/06 08:38:48 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2817, waitTime=2164, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014, retrying after 20071 ms, replay 2287 ops.
14/07/06 08:38:48 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2817, waitTime=2164, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014, retrying after 20076 ms, replay 2290 ops.
2014-07-06 08:38:56:240 340 sec: 4016798 operations; 12319.67 current ops/sec; [UPDATE AverageLatency(us)=8611436] [INSERT AverageLatency(us)=1110.89] [CLEANUP AverageLatency(us)=8611464] 
2014-07-06 08:39:06:241 350 sec: 4349149 operations; 33235.1 current ops/sec; [UPDATE AverageLatency(us)=12112549] [INSERT AverageLatency(us)=356.92] [CLEANUP AverageLatency(us)=12112570] 
14/07/06 08:39:09 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:03 PDT 2014
14/07/06 08:39:09 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404660438694, tracking started Sun Jul 06 08:37:05 PDT 2014
2014-07-06 08:39:16:242 360 sec: 4658843 operations; 30963.21 current ops/sec; [UPDATE AverageLatency(us)=2111489.25] [INSERT AverageLatency(us)=1022.28] [CLEANUP AverageLatency(us)=2111514] 
2014-07-06 08:39:26:249 370 sec: 4911762 operations; 25274.21 current ops/sec; [UPDATE AverageLatency(us)=1044576.33] [INSERT AverageLatency(us)=166.9] [CLEANUP AverageLatency(us)=1044601.67] 
2014-07-06 08:39:31:599 375 sec: 5000000 operations; 16493.08 current ops/sec; [UPDATE AverageLatency(us)=590959.33] [INSERT AverageLatency(us)=128.27] [CLEANUP AverageLatency(us)=590991.33] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404661173
1404661173
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404661183
1404661183
++ echo /home/hadoop/git/physical_design/caseresult/case19/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case19/random_read_1.dat
Loading workload...
Starting test.
2014-07-06 08:39:49:440 0 sec: 0 operations; 
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:39:51 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4ef888ea, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:39:51 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4ef888ea connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:39:51 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:39:51 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 08:39:51 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c494fa1000b, negotiated timeout = 90000
2014-07-06 08:39:59:450 10 sec: 38757 operations; 3871.83 current ops/sec; [READ AverageLatency(us)=5068.14] 
2014-07-06 08:40:09:453 20 sec: 185188 operations; 14638.71 current ops/sec; [READ AverageLatency(us)=1363.18] 
2014-07-06 08:40:19:453 30 sec: 331199 operations; 14601.1 current ops/sec; [READ AverageLatency(us)=1354.6] 
2014-07-06 08:40:29:454 40 sec: 495943 operations; 16472.75 current ops/sec; [READ AverageLatency(us)=1217.78] 
2014-07-06 08:40:39:454 50 sec: 663686 operations; 16774.3 current ops/sec; [READ AverageLatency(us)=1187.4] 
2014-07-06 08:40:49:455 60 sec: 825843 operations; 16214.08 current ops/sec; [READ AverageLatency(us)=1228.46] 
2014-07-06 08:40:59:456 70 sec: 1004645 operations; 17878.41 current ops/sec; [READ AverageLatency(us)=1113.74] 
2014-07-06 08:41:09:456 80 sec: 1193330 operations; 18868.5 current ops/sec; [READ AverageLatency(us)=1055.18] 
2014-07-06 08:41:19:457 90 sec: 1387255 operations; 19390.56 current ops/sec; [READ AverageLatency(us)=1026.47] 
2014-07-06 08:41:29:457 100 sec: 1581053 operations; 19379.8 current ops/sec; [READ AverageLatency(us)=1027.15] 
2014-07-06 08:41:39:458 110 sec: 1773755 operations; 19268.27 current ops/sec; [READ AverageLatency(us)=1033.02] 
2014-07-06 08:41:49:459 120 sec: 1960607 operations; 18683.33 current ops/sec; [READ AverageLatency(us)=1064.13] 
2014-07-06 08:41:59:459 130 sec: 2149451 operations; 18884.4 current ops/sec; [READ AverageLatency(us)=1055.25] 
2014-07-06 08:42:09:460 140 sec: 2339117 operations; 18964.7 current ops/sec; [READ AverageLatency(us)=1049.6] 
2014-07-06 08:42:19:460 150 sec: 2533183 operations; 19406.6 current ops/sec; [READ AverageLatency(us)=1025.74] 
2014-07-06 08:42:29:461 160 sec: 2726681 operations; 19347.87 current ops/sec; [READ AverageLatency(us)=1028.85] 
2014-07-06 08:42:39:462 170 sec: 2907690 operations; 18099.09 current ops/sec; [READ AverageLatency(us)=1098.08] 
2014-07-06 08:42:49:462 180 sec: 3082229 operations; 17453.9 current ops/sec; [READ AverageLatency(us)=1141.86] 
2014-07-06 08:42:59:463 190 sec: 3259813 operations; 17756.62 current ops/sec; [READ AverageLatency(us)=1118.46] 
2014-07-06 08:43:09:464 200 sec: 3451366 operations; 19153.38 current ops/sec; [READ AverageLatency(us)=1039.26] 
2014-07-06 08:43:19:464 210 sec: 3647095 operations; 19572.9 current ops/sec; [READ AverageLatency(us)=1016.51] 
2014-07-06 08:43:29:465 220 sec: 3840303 operations; 19318.87 current ops/sec; [READ AverageLatency(us)=1032.78] 
2014-07-06 08:43:39:466 230 sec: 4038632 operations; 19830.92 current ops/sec; [READ AverageLatency(us)=1003.61] 
2014-07-06 08:43:49:466 240 sec: 4225517 operations; 18688.5 current ops/sec; [READ AverageLatency(us)=1065.31] 
2014-07-06 08:43:59:467 250 sec: 4418670 operations; 19313.37 current ops/sec; [READ AverageLatency(us)=1030.63] 
2014-07-06 08:44:09:468 260 sec: 4600272 operations; 18158.38 current ops/sec; [READ AverageLatency(us)=1096.44] 
2014-07-06 08:44:19:468 270 sec: 4790006 operations; 18973.4 current ops/sec; [READ AverageLatency(us)=1049.3] 
2014-07-06 08:44:29:469 280 sec: 4959153 operations; 16913.01 current ops/sec; [READ AverageLatency(us)=1177.44] 
2014-07-06 08:44:32:266 282 sec: 5000000 operations; 14603.86 current ops/sec; [UPDATE AverageLatency(us)=10.55] [READ AverageLatency(us)=1118.9] [CLEANUP AverageLatency(us)=1174.05] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404661472
1404661472
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404661482
1404661482
++ echo /home/hadoop/git/physical_design/caseresult/case19/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case19/workloada_1.dat
Loading workload...
Starting test.
2014-07-06 08:44:43:723 0 sec: 0 operations; 
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:44:44 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x629bee3a, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:44:44 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x629bee3a connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:44:44 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:44:44 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 08:44:44 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c495153000e, negotiated timeout = 90000
2014-07-06 08:44:53:724 10 sec: 36449 operations; 3643.81 current ops/sec; [INSERT AverageLatency(us)=1270.16] [READ AverageLatency(us)=3388.24] 
2014-07-06 08:45:03:726 20 sec: 150441 operations; 11396.92 current ops/sec; [INSERT AverageLatency(us)=16.06] [READ AverageLatency(us)=1805.41] 
2014-07-06 08:45:13:727 30 sec: 271674 operations; 12122.09 current ops/sec; [INSERT AverageLatency(us)=12.71] [READ AverageLatency(us)=1811.98] 
2014-07-06 08:45:23:728 40 sec: 402967 operations; 13127.99 current ops/sec; [INSERT AverageLatency(us)=13.33] [READ AverageLatency(us)=1674.49] 
2014-07-06 08:45:33:728 50 sec: 544216 operations; 14124.9 current ops/sec; [INSERT AverageLatency(us)=16.33] [READ AverageLatency(us)=1554.43] 
2014-07-06 08:45:43:822 60 sec: 679338 operations; 13386.37 current ops/sec; [INSERT AverageLatency(us)=25.41] [READ AverageLatency(us)=1628.62] 
2014-07-06 08:45:53:823 70 sec: 816763 operations; 13741.13 current ops/sec; [INSERT AverageLatency(us)=20.11] [READ AverageLatency(us)=1619.99] 
2014-07-06 08:46:03:923 80 sec: 934107 operations; 11618.22 current ops/sec; [INSERT AverageLatency(us)=60.7] [READ AverageLatency(us)=1892.12] 
2014-07-06 08:46:13:924 90 sec: 1027272 operations; 9315.57 current ops/sec; [INSERT AverageLatency(us)=28.71] [READ AverageLatency(us)=2356.17] 
2014-07-06 08:46:23:924 100 sec: 1131743 operations; 10447.1 current ops/sec; [INSERT AverageLatency(us)=30.6] [READ AverageLatency(us)=2124.63] 
2014-07-06 08:46:33:925 110 sec: 1245707 operations; 11395.26 current ops/sec; [INSERT AverageLatency(us)=16.74] [READ AverageLatency(us)=1931.25] 
2014-07-06 08:46:43:926 120 sec: 1379926 operations; 13420.56 current ops/sec; [INSERT AverageLatency(us)=15.77] [READ AverageLatency(us)=1643.33] 
2014-07-06 08:46:53:927 130 sec: 1510584 operations; 13064.49 current ops/sec; [INSERT AverageLatency(us)=20.36] [READ AverageLatency(us)=1690.02] 
2014-07-06 08:47:03:928 140 sec: 1641980 operations; 13138.29 current ops/sec; [INSERT AverageLatency(us)=17.08] [READ AverageLatency(us)=1678.17] 
2014-07-06 08:47:13:929 150 sec: 1778373 operations; 13637.94 current ops/sec; [INSERT AverageLatency(us)=16.14] [READ AverageLatency(us)=1613.03] 
2014-07-06 08:47:23:929 160 sec: 1883296 operations; 10492.3 current ops/sec; [INSERT AverageLatency(us)=40.47] [READ AverageLatency(us)=2078] 
2014-07-06 08:47:33:931 170 sec: 1972719 operations; 8941.41 current ops/sec; [INSERT AverageLatency(us)=33.25] [READ AverageLatency(us)=2516.53] 
2014-07-06 08:47:43:944 180 sec: 2104925 operations; 13202.12 current ops/sec; [INSERT AverageLatency(us)=18.97] [READ AverageLatency(us)=1670.81] 
2014-07-06 08:47:53:950 190 sec: 2261900 operations; 15688.09 current ops/sec; [INSERT AverageLatency(us)=15.14] [READ AverageLatency(us)=1406.71] 
2014-07-06 08:48:03:951 200 sec: 2417839 operations; 15592.34 current ops/sec; [INSERT AverageLatency(us)=17.48] [READ AverageLatency(us)=1408.18] 
2014-07-06 08:48:13:952 210 sec: 2587021 operations; 16916.51 current ops/sec; [INSERT AverageLatency(us)=15.94] [READ AverageLatency(us)=1306.42] 
2014-07-06 08:48:23:952 220 sec: 2761186 operations; 17416.5 current ops/sec; [INSERT AverageLatency(us)=13.85] [READ AverageLatency(us)=1267.23] 
2014-07-06 08:48:33:954 230 sec: 2863786 operations; 10257.95 current ops/sec; [INSERT AverageLatency(us)=24.67] [READ AverageLatency(us)=2156.55] 
2014-07-06 08:48:43:954 240 sec: 3037589 operations; 17380.3 current ops/sec; [INSERT AverageLatency(us)=13.78] [READ AverageLatency(us)=1272.68] 
2014-07-06 08:48:53:955 250 sec: 3220965 operations; 18335.77 current ops/sec; [INSERT AverageLatency(us)=13.76] [READ AverageLatency(us)=1203.2] 
2014-07-06 08:49:03:956 260 sec: 3405219 operations; 18423.56 current ops/sec; [INSERT AverageLatency(us)=12.52] [READ AverageLatency(us)=1198] 
2014-07-06 08:49:13:957 270 sec: 3587059 operations; 18182.18 current ops/sec; [INSERT AverageLatency(us)=14.49] [READ AverageLatency(us)=1213.48] 
2014-07-06 08:49:23:958 280 sec: 3748972 operations; 16189.68 current ops/sec; [INSERT AverageLatency(us)=15.96] [READ AverageLatency(us)=1362.04] 
2014-07-06 08:49:33:958 290 sec: 3868563 operations; 11959.1 current ops/sec; [INSERT AverageLatency(us)=19.9] [READ AverageLatency(us)=1849.79] 
2014-07-06 08:49:43:959 300 sec: 4053960 operations; 18537.85 current ops/sec; [INSERT AverageLatency(us)=12.17] [READ AverageLatency(us)=1191.5] 
2014-07-06 08:49:53:960 310 sec: 4225587 operations; 17160.98 current ops/sec; [INSERT AverageLatency(us)=13.77] [READ AverageLatency(us)=1287.3] 
2014-07-06 08:50:03:961 320 sec: 4406651 operations; 18104.59 current ops/sec; [INSERT AverageLatency(us)=14] [READ AverageLatency(us)=1220.42] 
2014-07-06 08:50:13:962 330 sec: 4558870 operations; 15221.9 current ops/sec; [INSERT AverageLatency(us)=12.45] [READ AverageLatency(us)=1451.07] 
2014-07-06 08:50:23:962 340 sec: 4681889 operations; 12300.67 current ops/sec; [INSERT AverageLatency(us)=15.11] [READ AverageLatency(us)=1788.01] 
2014-07-06 08:50:33:963 350 sec: 4784298 operations; 10239.88 current ops/sec; [INSERT AverageLatency(us)=19.02] [READ AverageLatency(us)=2168.45] 
2014-07-06 08:50:43:964 360 sec: 4973962 operations; 18964.5 current ops/sec; [INSERT AverageLatency(us)=12.86] [READ AverageLatency(us)=1164.01] 
2014-07-06 08:50:47:536 363 sec: 5000000 operations; 7289.47 current ops/sec; [UPDATE AverageLatency(us)=168586.7] [INSERT AverageLatency(us)=12.48] [READ AverageLatency(us)=1699.7] [CLEANUP AverageLatency(us)=168777.35] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404661848
1404661848
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404661858
1404661858
++ echo /home/hadoop/git/physical_design/caseresult/case19/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case19/workloadb_1.dat
Loading workload...
Starting test.
2014-07-06 08:50:59:644 0 sec: 0 operations; 
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 08:51:00 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4dcc8fa3, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 08:51:00 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4dcc8fa3 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 08:51:00 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 08:51:00 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 08:51:00 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c494fa1000c, negotiated timeout = 90000
2014-07-06 08:51:09:646 10 sec: 37073 operations; 3706.19 current ops/sec; [INSERT AverageLatency(us)=685.77] [READ AverageLatency(us)=3725.83] 
2014-07-06 08:51:19:654 20 sec: 190235 operations; 15303.96 current ops/sec; [INSERT AverageLatency(us)=22.63] [READ AverageLatency(us)=2394.17] 
2014-07-06 08:51:29:655 30 sec: 366409 operations; 17615.64 current ops/sec; [INSERT AverageLatency(us)=15.9] [READ AverageLatency(us)=2218.11] 
2014-07-06 08:51:39:656 40 sec: 503891 operations; 13746.83 current ops/sec; [INSERT AverageLatency(us)=15.55] [READ AverageLatency(us)=2866.94] 
2014-07-06 08:51:49:730 50 sec: 649140 operations; 14418.21 current ops/sec; [INSERT AverageLatency(us)=16.7] [READ AverageLatency(us)=2710.6] 
2014-07-06 08:51:59:731 60 sec: 822218 operations; 17306.07 current ops/sec; [INSERT AverageLatency(us)=22.9] [READ AverageLatency(us)=2274.15] 
2014-07-06 08:52:09:732 70 sec: 982334 operations; 16010 current ops/sec; [INSERT AverageLatency(us)=17.79] [READ AverageLatency(us)=2471.71] 
2014-07-06 08:52:19:733 80 sec: 1133334 operations; 15100 current ops/sec; [INSERT AverageLatency(us)=18.48] [READ AverageLatency(us)=2603.87] 
2014-07-06 08:52:29:780 90 sec: 1319113 operations; 18489.15 current ops/sec; [INSERT AverageLatency(us)=15.37] [READ AverageLatency(us)=2143.44] 
2014-07-06 08:52:39:780 100 sec: 1489062 operations; 16994.9 current ops/sec; [INSERT AverageLatency(us)=13.01] [READ AverageLatency(us)=2307.5] 
2014-07-06 08:52:49:781 110 sec: 1606711 operations; 11763.72 current ops/sec; [INSERT AverageLatency(us)=16.87] [READ AverageLatency(us)=3391.89] 
2014-07-06 08:52:59:782 120 sec: 1718569 operations; 11184.68 current ops/sec; [INSERT AverageLatency(us)=16.71] [READ AverageLatency(us)=3531.11] 
2014-07-06 08:53:09:783 130 sec: 1881704 operations; 16313.5 current ops/sec; [INSERT AverageLatency(us)=16.32] [READ AverageLatency(us)=2396.23] 
2014-07-06 08:53:19:784 140 sec: 1976986 operations; 9526.29 current ops/sec; [INSERT AverageLatency(us)=13.53] [READ AverageLatency(us)=4208.96] 
2014-07-06 08:53:29:784 150 sec: 2088224 operations; 11123.8 current ops/sec; [INSERT AverageLatency(us)=25.66] [READ AverageLatency(us)=3561.34] 
2014-07-06 08:53:39:785 160 sec: 2245319 operations; 15707.93 current ops/sec; [INSERT AverageLatency(us)=14] [READ AverageLatency(us)=2535.75] 
2014-07-06 08:53:49:786 170 sec: 2266643 operations; 2132.19 current ops/sec; [INSERT AverageLatency(us)=26.12] [READ AverageLatency(us)=6058.83] 
2014-07-06 08:53:59:787 180 sec: 2300274 operations; 3362.76 current ops/sec; [INSERT AverageLatency(us)=13.48] [READ AverageLatency(us)=19779.09] 
2014-07-06 08:54:09:787 190 sec: 2437551 operations; 13727.7 current ops/sec; [INSERT AverageLatency(us)=18.06] [READ AverageLatency(us)=2884.39] 
2014-07-06 08:54:19:788 200 sec: 2500800 operations; 6324.27 current ops/sec; [INSERT AverageLatency(us)=27.32] [READ AverageLatency(us)=6306.56] 
2014-07-06 08:54:29:789 210 sec: 2605762 operations; 10495.15 current ops/sec; [INSERT AverageLatency(us)=30.75] [READ AverageLatency(us)=3750.93] 
2014-07-06 08:54:39:790 220 sec: 2694326 operations; 8855.51 current ops/sec; [INSERT AverageLatency(us)=19.66] [READ AverageLatency(us)=4485.22] 
2014-07-06 08:54:49:791 230 sec: 2811773 operations; 11743.53 current ops/sec; [INSERT AverageLatency(us)=30.94] [READ AverageLatency(us)=3351.66] 
2014-07-06 08:54:59:792 240 sec: 2920657 operations; 10887.31 current ops/sec; [INSERT AverageLatency(us)=16.23] [READ AverageLatency(us)=3643.39] 
2014-07-06 08:55:09:895 250 sec: 3032207 operations; 11041.27 current ops/sec; [INSERT AverageLatency(us)=16.53] [READ AverageLatency(us)=3589.51] 
2014-07-06 08:55:19:896 260 sec: 3152368 operations; 12014.9 current ops/sec; [INSERT AverageLatency(us)=12.16] [READ AverageLatency(us)=3288.77] 
2014-07-06 08:55:29:897 270 sec: 3215606 operations; 6323.17 current ops/sec; [INSERT AverageLatency(us)=16.09] [READ AverageLatency(us)=6358.03] 
2014-07-06 08:55:39:898 280 sec: 3302788 operations; 8717.33 current ops/sec; [INSERT AverageLatency(us)=14.53] [READ AverageLatency(us)=4578.54] 
2014-07-06 08:55:49:914 290 sec: 3395257 operations; 9232.13 current ops/sec; [INSERT AverageLatency(us)=17.38] [READ AverageLatency(us)=4246.26] 
2014-07-06 08:55:59:915 300 sec: 3481673 operations; 8640.74 current ops/sec; [INSERT AverageLatency(us)=15.89] [READ AverageLatency(us)=4668.9] 
2014-07-06 08:56:09:916 310 sec: 3561054 operations; 7938.1 current ops/sec; [INSERT AverageLatency(us)=16.06] [READ AverageLatency(us)=4990.34] 
2014-07-06 08:56:19:940 320 sec: 3603879 operations; 4271.82 current ops/sec; [INSERT AverageLatency(us)=18.23] [READ AverageLatency(us)=9331.23] 
2014-07-06 08:56:29:941 330 sec: 3684895 operations; 8100.79 current ops/sec; [INSERT AverageLatency(us)=12.68] [READ AverageLatency(us)=4871.81] 
2014-07-06 08:56:39:941 340 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:56:49:942 350 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:56:59:943 360 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:57:09:944 370 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:57:19:944 380 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:57:29:945 390 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:57:39:946 400 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:57:49:946 410 sec: 3684895 operations; 0 current ops/sec;   
2014-07-06 08:58:00:233 420 sec: 3687513 operations; 254.5 current ops/sec; [INSERT AverageLatency(us)=21.34] [READ AverageLatency(us)=1306395.34] 
2014-07-06 08:58:10:235 430 sec: 3721816 operations; 3429.61 current ops/sec; [INSERT AverageLatency(us)=11.62] [READ AverageLatency(us)=14958.44] 
2014-07-06 08:58:20:236 440 sec: 3755178 operations; 3335.87 current ops/sec; [INSERT AverageLatency(us)=23.64] [READ AverageLatency(us)=11972.04] 
2014-07-06 08:58:30:237 450 sec: 3789473 operations; 3429.16 current ops/sec; [INSERT AverageLatency(us)=19] [READ AverageLatency(us)=11697.22] 
2014-07-06 08:58:40:237 460 sec: 3822511 operations; 3303.8 current ops/sec; [INSERT AverageLatency(us)=15.25] [READ AverageLatency(us)=12061.67] 
2014-07-06 08:58:50:238 470 sec: 3854816 operations; 3230.18 current ops/sec; [INSERT AverageLatency(us)=11.94] [READ AverageLatency(us)=12180.78] 
2014-07-06 08:59:00:239 480 sec: 3888811 operations; 3399.16 current ops/sec; [INSERT AverageLatency(us)=21.65] [READ AverageLatency(us)=11991.28] 
2014-07-06 08:59:10:240 490 sec: 3927911 operations; 3909.61 current ops/sec; [INSERT AverageLatency(us)=13.58] [READ AverageLatency(us)=10162.41] 
2014-07-06 08:59:20:241 500 sec: 3963005 operations; 3509.05 current ops/sec; [INSERT AverageLatency(us)=19.49] [READ AverageLatency(us)=11374.37] 
2014-07-06 08:59:30:242 510 sec: 4004250 operations; 4124.5 current ops/sec; [INSERT AverageLatency(us)=22.45] [READ AverageLatency(us)=9708.73] 
2014-07-06 08:59:40:242 520 sec: 4048367 operations; 4411.26 current ops/sec; [INSERT AverageLatency(us)=13.01] [READ AverageLatency(us)=9008.16] 
2014-07-06 08:59:50:244 530 sec: 4091649 operations; 4327.33 current ops/sec; [INSERT AverageLatency(us)=11.13] [READ AverageLatency(us)=9207.91] 
2014-07-06 09:00:00:253 540 sec: 4136309 operations; 4461.98 current ops/sec; [INSERT AverageLatency(us)=15.78] [READ AverageLatency(us)=8909.5] 
2014-07-06 09:00:10:254 550 sec: 4179104 operations; 4279.07 current ops/sec; [INSERT AverageLatency(us)=16.36] [READ AverageLatency(us)=9277.74] 
2014-07-06 09:00:20:255 560 sec: 4227846 operations; 4873.71 current ops/sec; [INSERT AverageLatency(us)=11.91] [READ AverageLatency(us)=8184.48] 
2014-07-06 09:00:30:255 570 sec: 4277690 operations; 4984.4 current ops/sec; [INSERT AverageLatency(us)=12.08] [READ AverageLatency(us)=7998.65] 
2014-07-06 09:00:40:257 580 sec: 4330453 operations; 5275.77 current ops/sec; [INSERT AverageLatency(us)=17.34] [READ AverageLatency(us)=7549.98] 
2014-07-06 09:00:50:258 590 sec: 4389784 operations; 5931.91 current ops/sec; [INSERT AverageLatency(us)=14.64] [READ AverageLatency(us)=6728.29] 
2014-07-06 09:01:00:259 600 sec: 4447252 operations; 5746.23 current ops/sec; [INSERT AverageLatency(us)=18.8] [READ AverageLatency(us)=6882.06] 
2014-07-06 09:01:10:260 610 sec: 4505623 operations; 5837.1 current ops/sec; [INSERT AverageLatency(us)=23.89] [READ AverageLatency(us)=6827.94] 
2014-07-06 09:01:20:260 620 sec: 4563125 operations; 5749.63 current ops/sec; [INSERT AverageLatency(us)=15.27] [READ AverageLatency(us)=6960.24] 
2014-07-06 09:01:30:261 630 sec: 4629396 operations; 6626.44 current ops/sec; [INSERT AverageLatency(us)=12.85] [READ AverageLatency(us)=5818.6] 
2014-07-06 09:01:40:262 640 sec: 4692415 operations; 6301.27 current ops/sec; [INSERT AverageLatency(us)=14.68] [READ AverageLatency(us)=6495.9] 
2014-07-06 09:01:50:262 650 sec: 4745411 operations; 5299.6 current ops/sec; [INSERT AverageLatency(us)=17.24] [READ AverageLatency(us)=7584.67] 
2014-07-06 09:02:00:263 660 sec: 4811916 operations; 6649.84 current ops/sec; [INSERT AverageLatency(us)=12.62] [READ AverageLatency(us)=5980.74] 
2014-07-06 09:02:10:264 670 sec: 4872997 operations; 6108.1 current ops/sec; [INSERT AverageLatency(us)=15] [READ AverageLatency(us)=6557.76] 
2014-07-06 09:02:20:402 680 sec: 4929830 operations; 5605.94 current ops/sec; [INSERT AverageLatency(us)=17.62] [READ AverageLatency(us)=7054.37] 
2014-07-06 09:02:30:402 690 sec: 4991589 operations; 6175.28 current ops/sec; [UPDATE AverageLatency(us)=536812.75] [INSERT AverageLatency(us)=12.48] [READ AverageLatency(us)=6042.96] [CLEANUP AverageLatency(us)=537669.5] 
2014-07-06 09:02:35:643 696 sec: 5000000 operations; 1604.85 current ops/sec; [UPDATE AverageLatency(us)=375284.83] [INSERT AverageLatency(us)=30.56] [READ AverageLatency(us)=4481.96] [CLEANUP AverageLatency(us)=375299.75] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404662556
1404662556
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404662566
1404662566
++ echo /home/hadoop/git/physical_design/caseresult/case19/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case19/workloadc_1.dat
Loading workload...
Starting test.
2014-07-06 09:02:49:104 0 sec: 0 operations; 
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 09:02:49 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xc2c915f, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 09:02:49 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xc2c915f connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 09:02:49 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 09:02:49 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 09:02:49 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c494fa1000d, negotiated timeout = 90000
2014-07-06 09:02:59:106 10 sec: 116693 operations; 11666.97 current ops/sec; [INSERT AverageLatency(us)=234] [READ AverageLatency(us)=13208.63] 
2014-07-06 09:03:09:113 20 sec: 276878 operations; 16007.29 current ops/sec; [INSERT AverageLatency(us)=13.84] [READ AverageLatency(us)=12292.71] 
2014-07-06 09:03:19:114 30 sec: 297626 operations; 2074.59 current ops/sec; [INSERT AverageLatency(us)=15.39] [READ AverageLatency(us)=95075.65] 
2014-07-06 09:03:29:115 40 sec: 427160 operations; 12952.1 current ops/sec; [INSERT AverageLatency(us)=20.25] [READ AverageLatency(us)=15378.68] 
2014-07-06 09:03:39:116 50 sec: 584212 operations; 15703.63 current ops/sec; [INSERT AverageLatency(us)=15.84] [READ AverageLatency(us)=12492.87] 
2014-07-06 09:03:49:117 60 sec: 722359 operations; 13814.7 current ops/sec; [INSERT AverageLatency(us)=13.52] [READ AverageLatency(us)=13372.56] 
2014-07-06 09:03:59:117 70 sec: 828284 operations; 10591.44 current ops/sec; [INSERT AverageLatency(us)=12.73] [READ AverageLatency(us)=19801.31] 
2014-07-06 09:04:09:118 80 sec: 946770 operations; 11847.42 current ops/sec; [INSERT AverageLatency(us)=13.61] [READ AverageLatency(us)=16505.69] 
2014-07-06 09:04:19:119 90 sec: 1059116 operations; 11233.48 current ops/sec; [INSERT AverageLatency(us)=11.49] [READ AverageLatency(us)=18036.78] 
2014-07-06 09:04:29:120 100 sec: 1164658 operations; 10553.14 current ops/sec; [INSERT AverageLatency(us)=14.93] [READ AverageLatency(us)=18660.11] 
2014-07-06 09:04:39:120 110 sec: 1268818 operations; 10416 current ops/sec; [INSERT AverageLatency(us)=11.61] [READ AverageLatency(us)=19397.11] 
2014-07-06 09:04:49:121 120 sec: 1381466 operations; 11263.67 current ops/sec; [INSERT AverageLatency(us)=14.88] [READ AverageLatency(us)=17487.77] 
2014-07-06 09:04:59:122 130 sec: 1505016 operations; 12353.76 current ops/sec; [INSERT AverageLatency(us)=11.25] [READ AverageLatency(us)=16131.52] 
2014-07-06 09:05:09:123 140 sec: 1590472 operations; 8544.75 current ops/sec; [INSERT AverageLatency(us)=14.51] [READ AverageLatency(us)=23380.93] 
2014-07-06 09:05:19:123 150 sec: 1727281 operations; 13680.9 current ops/sec; [INSERT AverageLatency(us)=13.13] [READ AverageLatency(us)=14612.59] 
2014-07-06 09:05:29:124 160 sec: 1845638 operations; 11834.52 current ops/sec; [INSERT AverageLatency(us)=13.77] [READ AverageLatency(us)=17035.27] 
2014-07-06 09:05:39:125 170 sec: 1934065 operations; 8842.7 current ops/sec; [INSERT AverageLatency(us)=12.96] [READ AverageLatency(us)=22225.55] 
2014-07-06 09:05:49:125 180 sec: 2028664 operations; 9458.95 current ops/sec; [INSERT AverageLatency(us)=13.52] [READ AverageLatency(us)=20786.83] 
2014-07-06 09:05:59:126 190 sec: 2131427 operations; 10275.27 current ops/sec; [INSERT AverageLatency(us)=11.02] [READ AverageLatency(us)=19485.01] 
2014-07-06 09:06:09:127 200 sec: 2236888 operations; 10545.05 current ops/sec; [INSERT AverageLatency(us)=11.05] [READ AverageLatency(us)=18666.69] 
2014-07-06 09:06:19:136 210 sec: 2331338 operations; 9436.51 current ops/sec; [INSERT AverageLatency(us)=11.38] [READ AverageLatency(us)=20918.54] 
2014-07-06 09:06:29:136 220 sec: 2440693 operations; 10935.5 current ops/sec; [INSERT AverageLatency(us)=12.36] [READ AverageLatency(us)=18285.88] 
2014-07-06 09:06:39:137 230 sec: 2545790 operations; 10508.65 current ops/sec; [INSERT AverageLatency(us)=12.92] [READ AverageLatency(us)=18874.39] 
2014-07-06 09:06:49:138 240 sec: 2656922 operations; 11112.09 current ops/sec; [INSERT AverageLatency(us)=13.25] [READ AverageLatency(us)=17427.82] 
2014-07-06 09:06:59:139 250 sec: 2756758 operations; 9982.6 current ops/sec; [INSERT AverageLatency(us)=10.94] [READ AverageLatency(us)=19767.05] 
2014-07-06 09:07:09:140 260 sec: 2846178 operations; 8941.11 current ops/sec; [INSERT AverageLatency(us)=12.59] [READ AverageLatency(us)=22160.33] 
2014-07-06 09:07:19:141 270 sec: 2946452 operations; 10026.4 current ops/sec; [INSERT AverageLatency(us)=12.39] [READ AverageLatency(us)=19753.07] 
2014-07-06 09:07:29:142 280 sec: 3032212 operations; 8576 current ops/sec; [INSERT AverageLatency(us)=12.79] [READ AverageLatency(us)=22978.17] 
2014-07-06 09:07:39:142 290 sec: 3137696 operations; 10547.35 current ops/sec; [INSERT AverageLatency(us)=12.52] [READ AverageLatency(us)=18578.11] 
2014-07-06 09:07:49:143 300 sec: 3248072 operations; 11036.5 current ops/sec; [INSERT AverageLatency(us)=16.19] [READ AverageLatency(us)=17937.34] 
2014-07-06 09:07:59:144 310 sec: 3349390 operations; 10131.8 current ops/sec; [INSERT AverageLatency(us)=10.72] [READ AverageLatency(us)=19692.61] 
2014-07-06 09:08:09:144 320 sec: 3458549 operations; 10914.81 current ops/sec; [INSERT AverageLatency(us)=12.72] [READ AverageLatency(us)=18131.49] 
2014-07-06 09:08:19:145 330 sec: 3577341 operations; 11878.01 current ops/sec; [INSERT AverageLatency(us)=10.66] [READ AverageLatency(us)=16538.27] 
2014-07-06 09:08:29:146 340 sec: 3680005 operations; 10265.37 current ops/sec; [INSERT AverageLatency(us)=12.98] [READ AverageLatency(us)=19180.64] 
2014-07-06 09:08:39:146 350 sec: 3783635 operations; 10363 current ops/sec; [INSERT AverageLatency(us)=15.56] [READ AverageLatency(us)=19069.69] 
2014-07-06 09:08:49:147 360 sec: 3889024 operations; 10537.85 current ops/sec; [INSERT AverageLatency(us)=10.78] [READ AverageLatency(us)=19060.71] 
2014-07-06 09:08:59:148 370 sec: 4009568 operations; 12053.19 current ops/sec; [INSERT AverageLatency(us)=11.73] [READ AverageLatency(us)=16459.84] 
2014-07-06 09:09:09:148 380 sec: 4130640 operations; 12107.2 current ops/sec; [INSERT AverageLatency(us)=13.41] [READ AverageLatency(us)=16237.65] 
2014-07-06 09:09:19:149 390 sec: 4244878 operations; 11422.66 current ops/sec; [INSERT AverageLatency(us)=13.77] [READ AverageLatency(us)=17362.55] 
2014-07-06 09:09:29:150 400 sec: 4362407 operations; 11751.72 current ops/sec; [INSERT AverageLatency(us)=11.7] [READ AverageLatency(us)=16263.36] 
2014-07-06 09:09:39:151 410 sec: 4481180 operations; 11877.3 current ops/sec; [INSERT AverageLatency(us)=11.75] [READ AverageLatency(us)=17514.31] 
2014-07-06 09:09:49:151 420 sec: 4585584 operations; 10439.36 current ops/sec; [INSERT AverageLatency(us)=14.43] [READ AverageLatency(us)=19001.36] 
2014-07-06 09:09:59:152 430 sec: 4701602 operations; 11600.64 current ops/sec; [INSERT AverageLatency(us)=13.87] [READ AverageLatency(us)=16990.04] 
2014-07-06 09:10:09:153 440 sec: 4805073 operations; 10346.07 current ops/sec; [INSERT AverageLatency(us)=12.17] [READ AverageLatency(us)=19475.89] 
2014-07-06 09:10:19:153 450 sec: 4929115 operations; 12404.2 current ops/sec; [INSERT AverageLatency(us)=10.86] [READ AverageLatency(us)=15877.08] 
2014-07-06 09:10:29:154 460 sec: 4996546 operations; 6742.43 current ops/sec; [UPDATE AverageLatency(us)=635827.06] [INSERT AverageLatency(us)=11.96] [READ AverageLatency(us)=14875.59] [CLEANUP AverageLatency(us)=635949.22] 
2014-07-06 09:10:31:980 462 sec: 5000000 operations; 1222.22 current ops/sec; [UPDATE AverageLatency(us)=495386.5] [INSERT AverageLatency(us)=8.98] [READ AverageLatency(us)=11109.03] [CLEANUP AverageLatency(us)=495538.5] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404663032
1404663032
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
