++ ls caseresult/ -ltr
++ wc -l
+ filename=case14
+ mkdir caseresult/case14
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case14
+ TEN=10
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case14.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 33.6490 seconds

0 row(s) in 0.7920 seconds

0 row(s) in 0.0680 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''SNAPPY'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''SNAPPY'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case14/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case14/create_1.script
/home/hadoop/git/physical_design/caseresult/case14/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case14/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 2.0600 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404517307
1404517307
++ echo /home/hadoop/git/physical_design/caseresult/case14/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case14/load_1.dat
Loading workload...
Starting test.
2014-07-04 16:41:48:723 0 sec: 0 operations; 
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/04 16:41:49 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xc2c915f, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/04 16:41:49 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xc2c915f connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/04 16:41:49 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:41:49 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/04 16:41:49 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x4703bbde3b000b, negotiated timeout = 90000
2014-07-04 16:41:58:725 10 sec: 268747 operations; 26869.33 current ops/sec; [INSERT AverageLatency(us)=515.49] 
2014-07-04 16:42:08:727 20 sec: 290719 operations; 2196.76 current ops/sec; [INSERT AverageLatency(us)=435.36] 
2014-07-04 16:42:18:728 30 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:42:28 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4703bbde3b000b, likely server has closed socket, closing socket connection and attempting reconnect
2014-07-04 16:42:28:729 40 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:42:29 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:42:29 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/04 16:42:29 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x4703bbde3b000b, negotiated timeout = 90000
14/07/04 16:42:30 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4703bbde3b000b, likely server has closed socket, closing socket connection and attempting reconnect
14/07/04 16:42:30 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:42:30 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/04 16:42:30 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4703bbde3b000b, likely server has closed socket, closing socket connection and attempting reconnect
14/07/04 16:42:32 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:42:32 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/04 16:42:32 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x4703bbde3b000b, negotiated timeout = 90000
2014-07-04 16:42:38:729 50 sec: 290719 operations; 0 current ops/sec;  
2014-07-04 16:42:48:730 60 sec: 290719 operations; 0 current ops/sec;  
2014-07-04 16:42:58:731 70 sec: 290719 operations; 0 current ops/sec;  
2014-07-04 16:43:08:731 80 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:43:10 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2260 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10065 ms, replay 2260 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2264 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10016 ms, replay 2264 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10072 ms, replay 2263 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2319 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10003 ms, replay 2319 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10042 ms, replay 2286 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10080 ms, replay 2247 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2212 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10024 ms, replay 2212 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2200 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10053 ms, replay 2200 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2287 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10089 ms, replay 2287 ops.
14/07/04 16:43:10 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2290 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10013 ms, replay 2290 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2245 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10043 ms, replay 2245 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10096 ms, replay 2272 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2271 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10094 ms, replay 2271 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10064 ms, replay 2289 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10055 ms, replay 2247 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10000 ms, replay 2266 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10068 ms, replay 2247 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2286 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10079 ms, replay 2286 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2274 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10013 ms, replay 2274 ops.
14/07/04 16:43:12 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2302 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10022 ms, replay 2302 ops.
14/07/04 16:43:14 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 226 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10057 ms, replay 226 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 221 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10056 ms, replay 221 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 558 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10005 ms, replay 558 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 569 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10059 ms, replay 569 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 998 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10053 ms, replay 998 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2274 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10055 ms, replay 2274 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 573 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10068 ms, replay 573 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 218 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10002 ms, replay 218 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1704 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10063 ms, replay 1704 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 585 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10024 ms, replay 585 ops.
14/07/04 16:43:16 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1702 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10019 ms, replay 1702 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 230 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10055 ms, replay 230 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2256 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10088 ms, replay 2256 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2297 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:55 PDT 2014, retrying after 10018 ms, replay 2297 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 227 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10088 ms, replay 227 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 234 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10082 ms, replay 234 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1710 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10079 ms, replay 1710 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 550 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10008 ms, replay 550 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10027 ms, replay 2272 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 205 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10005 ms, replay 205 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10040 ms, replay 2263 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2269 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10044 ms, replay 2269 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2282 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10023 ms, replay 2282 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 243 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10087 ms, replay 243 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 576 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10064 ms, replay 576 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 986 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10095 ms, replay 986 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 92 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10068 ms, replay 92 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10033 ms, replay 2254 ops.
14/07/04 16:43:18 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2245 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:44413 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10019 ms, replay 2245 ops.
2014-07-04 16:43:18:732 90 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:43:20 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 85 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=935, waitTime=3434, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10048 ms, replay 85 ops.
14/07/04 16:43:20 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=935, waitTime=3434, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10014 ms, replay 2279 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 11 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10021 ms, replay 11 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 87 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10092 ms, replay 87 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 38 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10097 ms, replay 38 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 3 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10012 ms, replay 3 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 6 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10061 ms, replay 6 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 29 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10094 ms, replay 29 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 19 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10085 ms, replay 19 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 565 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10082 ms, replay 565 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 30 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10007 ms, replay 30 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 88 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10004 ms, replay 88 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 26 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10046 ms, replay 26 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 97 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10004 ms, replay 97 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 216 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10063 ms, replay 216 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2214 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10002 ms, replay 2214 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 18 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10030 ms, replay 18 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 6 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10046 ms, replay 6 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 90 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10025 ms, replay 90 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10077 ms, replay 2236 ops.
14/07/04 16:43:21 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 223 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=939, waitTime=2709, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10047 ms, replay 223 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10068 ms, replay 1 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2319 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10081 ms, replay 2319 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10010 ms, replay 1 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10071 ms, replay 2290 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 11 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10054 ms, replay 11 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 572 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10061 ms, replay 572 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10003 ms, replay 2286 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10009 ms, replay 2264 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10052 ms, replay 2253 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 9 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10035 ms, replay 9 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10017 ms, replay 2212 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 36 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10022 ms, replay 36 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 17 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10058 ms, replay 17 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2200 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10032 ms, replay 2200 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10053 ms, replay 2287 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10067 ms, replay 2263 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2260 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10044 ms, replay 2260 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10052 ms, replay 2247 ops.
14/07/04 16:43:22 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 85 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=962, waitTime=2441, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10076 ms, replay 85 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=983, waitTime=2002, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10059 ms, replay 2274 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=983, waitTime=2002, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10025 ms, replay 2266 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=985, waitTime=2002, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10059 ms, replay 2302 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=986, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10087 ms, replay 2245 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10057 ms, replay 2247 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10003 ms, replay 2289 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10007 ms, replay 2286 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10077 ms, replay 2247 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10055 ms, replay 2272 ops.
14/07/04 16:43:24 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=987, waitTime=2073, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 10018 ms, replay 2271 ops.
14/07/04 16:43:27 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 226 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=995, waitTime=2895, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10040 ms, replay 226 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 218 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=998, waitTime=2011, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10034 ms, replay 218 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 558 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=998, waitTime=2011, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10086 ms, replay 558 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 998 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10057 ms, replay 998 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 221 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10098 ms, replay 221 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 573 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10036 ms, replay 573 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10079 ms, replay 2274 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 1704 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10037 ms, replay 1704 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 569 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10047 ms, replay 569 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1702 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10022 ms, replay 1702 ops.
14/07/04 16:43:28 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 585 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1000, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10038 ms, replay 585 ops.
2014-07-04 16:43:28:732 100 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:43:30 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 550 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10015 ms, replay 550 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2297 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:55 PDT 2014, retrying after 10026 ms, replay 2297 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10094 ms, replay 2272 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10054 ms, replay 2245 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10063 ms, replay 2263 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2282 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10032 ms, replay 2282 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 205 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10013 ms, replay 205 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10062 ms, replay 2254 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 92 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10060 ms, replay 92 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 576 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10048 ms, replay 576 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2269 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10074 ms, replay 2269 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10049 ms, replay 230 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 986 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014, retrying after 10057 ms, replay 986 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2256 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10052 ms, replay 2256 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 227 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10079 ms, replay 227 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 234 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10039 ms, replay 234 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1710 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10038 ms, replay 1710 ops.
14/07/04 16:43:30 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1010, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10088 ms, replay 243 ops.
14/07/04 16:43:32 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 85 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1032, waitTime=2194, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10019 ms, replay 85 ops.
14/07/04 16:43:32 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1032, waitTime=2194, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014, retrying after 10086 ms, replay 2279 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 97 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10053 ms, replay 97 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 18 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10082 ms, replay 18 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 223 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10066 ms, replay 223 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 3 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10092 ms, replay 3 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 11 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10013 ms, replay 11 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 88 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10036 ms, replay 88 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 19 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10007 ms, replay 19 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 26 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10027 ms, replay 26 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 6 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10056 ms, replay 6 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 87 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10077 ms, replay 87 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10023 ms, replay 2236 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 38 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10018 ms, replay 38 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2214 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10038 ms, replay 2214 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 29 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10021 ms, replay 29 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 216 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10010 ms, replay 216 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 565 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10085 ms, replay 565 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 6 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10075 ms, replay 6 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 90 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10007 ms, replay 90 ops.
14/07/04 16:43:33 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 30 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1036, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10038 ms, replay 30 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 1 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10034 ms, replay 1 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 36 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10039 ms, replay 36 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 17 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10028 ms, replay 17 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20089 ms, replay 2247 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20085 ms, replay 2212 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2260 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20174 ms, replay 2260 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2200 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20120 ms, replay 2200 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20027 ms, replay 2264 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 572 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10072 ms, replay 572 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 11 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10030 ms, replay 11 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 1 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10013 ms, replay 1 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20034 ms, replay 2286 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 9 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10069 ms, replay 9 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014, retrying after 10007 ms, replay 2253 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20043 ms, replay 2287 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2290 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20027 ms, replay 2290 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2319 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20026 ms, replay 2319 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20197 ms, replay 2263 ops.
14/07/04 16:43:35 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 85 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1057, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014, retrying after 10010 ms, replay 85 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1078, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20167 ms, replay 2266 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20063 ms, replay 2302 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20003 ms, replay 2286 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20156 ms, replay 2274 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20065 ms, replay 2272 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20148 ms, replay 2247 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20187 ms, replay 2289 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20181 ms, replay 2271 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1079, waitTime=2122, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20162 ms, replay 2245 ops.
14/07/04 16:43:36 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1087, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20111 ms, replay 2247 ops.
14/07/04 16:43:38 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
2014-07-04 16:43:38:733 110 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:43:39 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:39 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:40 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:40 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:40 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:40 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:40 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:55 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:57 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:41 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:42 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:42 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:56 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:43 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:59 PDT 2014
14/07/04 16:43:45 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:58 PDT 2014
2014-07-04 16:43:48:734 120 sec: 290719 operations; 0 current ops/sec;  
14/07/04 16:43:56 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:43:56 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
2014-07-04 16:43:58:735 130 sec: 390763 operations; 10003.4 current ops/sec; [INSERT AverageLatency(us)=12068.04] 
14/07/04 16:43:58 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1177, waitTime=2339, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20038 ms, replay 2286 ops.
14/07/04 16:43:58 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1188, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20149 ms, replay 2266 ops.
14/07/04 16:43:58 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1191, waitTime=2076, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20085 ms, replay 2272 ops.
14/07/04 16:43:58 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1191, waitTime=2076, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20065 ms, replay 2302 ops.
14/07/04 16:43:58 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1191, waitTime=2076, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20175 ms, replay 2247 ops.
14/07/04 16:43:59 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1194, waitTime=2429, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20029 ms, replay 2247 ops.
14/07/04 16:43:59 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1194, waitTime=2429, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20132 ms, replay 2289 ops.
14/07/04 16:43:59 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1194, waitTime=2429, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20043 ms, replay 2245 ops.
14/07/04 16:43:59 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1194, waitTime=2429, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20180 ms, replay 2271 ops.
14/07/04 16:43:59 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1194, waitTime=2429, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20033 ms, replay 2274 ops.
2014-07-04 16:44:08:736 140 sec: 713407 operations; 32261.17 current ops/sec; [INSERT AverageLatency(us)=297.49] 
2014-07-04 16:44:18:740 150 sec: 922023 operations; 20853.26 current ops/sec; [INSERT AverageLatency(us)=365.85] 
14/07/04 16:44:21 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1925, waitTime=2419, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20070 ms, replay 2247 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1925, waitTime=2419, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20032 ms, replay 2302 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1925, waitTime=2419, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20006 ms, replay 2272 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1925, waitTime=2419, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20018 ms, replay 2286 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1925, waitTime=2419, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20015 ms, replay 2266 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1957, waitTime=2592, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20166 ms, replay 2247 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1957, waitTime=2592, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20125 ms, replay 2274 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1957, waitTime=2592, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20107 ms, replay 2271 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1957, waitTime=2592, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20031 ms, replay 2245 ops.
14/07/04 16:44:21 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1957, waitTime=2592, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20118 ms, replay 2289 ops.
2014-07-04 16:44:28:742 160 sec: 1077439 operations; 15538.49 current ops/sec; [INSERT AverageLatency(us)=473.44] 
2014-07-04 16:44:38:758 170 sec: 1366243 operations; 28834.27 current ops/sec; [INSERT AverageLatency(us)=311.08] 
14/07/04 16:44:43 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2612, waitTime=2070, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20166 ms, replay 2286 ops.
14/07/04 16:44:43 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2612, waitTime=2070, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20117 ms, replay 2302 ops.
14/07/04 16:44:43 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2612, waitTime=2070, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20166 ms, replay 2272 ops.
14/07/04 16:44:43 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2612, waitTime=2070, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20028 ms, replay 2266 ops.
14/07/04 16:44:43 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2619, waitTime=2079, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20093 ms, replay 2247 ops.
14/07/04 16:44:44 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2625, waitTime=2606, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20096 ms, replay 2271 ops.
14/07/04 16:44:44 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2625, waitTime=2606, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20166 ms, replay 2245 ops.
14/07/04 16:44:44 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2625, waitTime=2606, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20031 ms, replay 2289 ops.
14/07/04 16:44:44 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2625, waitTime=2606, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20093 ms, replay 2274 ops.
14/07/04 16:44:44 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2625, waitTime=2606, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20069 ms, replay 2247 ops.
2014-07-04 16:44:48:758 180 sec: 1388151 operations; 2190.8 current ops/sec; [INSERT AverageLatency(us)=460.67] 
2014-07-04 16:44:58:759 190 sec: 1600646 operations; 21247.38 current ops/sec; [INSERT AverageLatency(us)=870.06] 
14/07/04 16:45:05 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 2286 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3116, waitTime=2778, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20145 ms, replay 2286 ops.
14/07/04 16:45:05 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 2272 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3116, waitTime=2778, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20128 ms, replay 2272 ops.
14/07/04 16:45:05 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3116, waitTime=2778, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20094 ms, replay 2247 ops.
14/07/04 16:45:05 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2302 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3116, waitTime=2778, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20110 ms, replay 2302 ops.
14/07/04 16:45:05 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3116, waitTime=2778, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20107 ms, replay 2266 ops.
14/07/04 16:45:06 INFO client.AsyncProcess: #3, table=usertable, attempt=16/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3150, waitTime=3027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20191 ms, replay 2247 ops.
14/07/04 16:45:06 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3150, waitTime=3027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20140 ms, replay 2289 ops.
14/07/04 16:45:06 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3180, waitTime=2012, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20163 ms, replay 2274 ops.
14/07/04 16:45:06 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 2271 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3180, waitTime=2012, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20018 ms, replay 2271 ops.
14/07/04 16:45:07 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3188, waitTime=2737, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20026 ms, replay 2245 ops.
2014-07-04 16:45:08:760 200 sec: 1681008 operations; 8035.4 current ops/sec; [INSERT AverageLatency(us)=618.05] 
2014-07-04 16:45:18:761 210 sec: 1942315 operations; 26128.09 current ops/sec; [UPDATE AverageLatency(us)=2409097] [INSERT AverageLatency(us)=413.05] [CLEANUP AverageLatency(us)=2409427] 
14/07/04 16:45:26 INFO client.AsyncProcess: #17, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:26 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:26 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:26 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:26 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:28 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:45:28 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
2014-07-04 16:45:28:762 220 sec: 2242695 operations; 30035 current ops/sec; [UPDATE AverageLatency(us)=1725517] [INSERT AverageLatency(us)=4998.48] [CLEANUP AverageLatency(us)=1725763] 
14/07/04 16:45:29 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3857, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 10080 ms, replay 2344 ops.
14/07/04 16:45:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3857, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 10089 ms, replay 2820 ops.
14/07/04 16:45:29 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3857, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 10060 ms, replay 2277 ops.
14/07/04 16:45:29 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3857, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20021 ms, replay 2274 ops.
14/07/04 16:45:29 INFO client.AsyncProcess: #3, table=usertable, attempt=17/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3857, waitTime=2217, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20194 ms, replay 2247 ops.
14/07/04 16:45:29 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3887, waitTime=2019, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20047 ms, replay 2245 ops.
2014-07-04 16:45:38:764 230 sec: 2484931 operations; 24218.76 current ops/sec;  [INSERT AverageLatency(us)=268.21]  
14/07/04 16:45:40 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014
14/07/04 16:45:40 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014
14/07/04 16:45:41 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4266, waitTime=2013, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 10088 ms, replay 2277 ops.
2014-07-04 16:45:48:765 240 sec: 2726621 operations; 24166.58 current ops/sec; [UPDATE AverageLatency(us)=5696319] [INSERT AverageLatency(us)=934.81] [CLEANUP AverageLatency(us)=5696344] 
14/07/04 16:45:51 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4511, waitTime=2032, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20027 ms, replay 2274 ops.
14/07/04 16:45:52 INFO client.AsyncProcess: #11, table=usertable, attempt=18/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4522, waitTime=2616, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20068 ms, replay 2245 ops.
14/07/04 16:45:52 INFO client.AsyncProcess: #3, table=usertable, attempt=18/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4522, waitTime=2616, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20116 ms, replay 2247 ops.
14/07/04 16:45:53 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4558, waitTime=2820, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 20097 ms, replay 2277 ops.
2014-07-04 16:45:58:766 250 sec: 2788308 operations; 6168.08 current ops/sec;  [INSERT AverageLatency(us)=356.86]  
14/07/04 16:46:01 INFO client.AsyncProcess: #6, waiting for some tasks to finish. Expected max=0, tasksSent=334, tasksDone=329, currentTasksDone=329, retries=72 hasError=false, tableName=usertable
2014-07-04 16:46:08:767 260 sec: 2788308 operations; 0 current ops/sec;    
14/07/04 16:46:12 INFO client.AsyncProcess: #6, waiting for some tasks to finish. Expected max=0, tasksSent=346, tasksDone=341, currentTasksDone=341, retries=83 hasError=false, tableName=usertable
14/07/04 16:46:14 INFO client.AsyncProcess: #11, table=usertable, attempt=19/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4957, waitTime=3696, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20179 ms, replay 2245 ops.
14/07/04 16:46:14 INFO client.AsyncProcess: #3, table=usertable, attempt=19/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4957, waitTime=3696, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20054 ms, replay 2247 ops.
14/07/04 16:46:14 INFO client.AsyncProcess: #15, table=usertable, attempt=19/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4957, waitTime=3696, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20048 ms, replay 2274 ops.
14/07/04 16:46:15 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2277 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4979, waitTime=2294, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014, retrying after 20182 ms, replay 2277 ops.
2014-07-04 16:46:18:767 270 sec: 2788308 operations; 0 current ops/sec;    
14/07/04 16:46:24 INFO client.AsyncProcess: #6, waiting for some tasks to finish. Expected max=0, tasksSent=351, tasksDone=346, currentTasksDone=346, retries=88 hasError=false, tableName=usertable
2014-07-04 16:46:28:768 280 sec: 2863530 operations; 7521.45 current ops/sec;  [INSERT AverageLatency(us)=3069.46]  
14/07/04 16:46:37 INFO client.AsyncProcess: #3, table=usertable, attempt=20/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5369, waitTime=2482, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20083 ms, replay 2247 ops.
14/07/04 16:46:37 INFO client.AsyncProcess: #11, table=usertable, attempt=20/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5369, waitTime=2482, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20132 ms, replay 2245 ops.
14/07/04 16:46:37 INFO client.AsyncProcess: #15, table=usertable, attempt=20/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5369, waitTime=2482, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20183 ms, replay 2274 ops.
14/07/04 16:46:37 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:44:37 PDT 2014
2014-07-04 16:46:38:769 290 sec: 3169773 operations; 30621.24 current ops/sec; [UPDATE AverageLatency(us)=40564179] [INSERT AverageLatency(us)=838.99] [CLEANUP AverageLatency(us)=40564202] 
14/07/04 16:46:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2536 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5561, waitTime=2127, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:49 PDT 2014, retrying after 10098 ms, replay 2536 ops.
14/07/04 16:46:42 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2587 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5578, waitTime=2012, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:49 PDT 2014, retrying after 10008 ms, replay 2587 ops.
14/07/04 16:46:43 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5580, waitTime=2477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:50 PDT 2014, retrying after 10061 ms, replay 2230 ops.
2014-07-04 16:46:48:770 300 sec: 3383527 operations; 21373.26 current ops/sec;  [INSERT AverageLatency(us)=307.95]  
14/07/04 16:46:54 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:50 PDT 2014
14/07/04 16:46:54 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:49 PDT 2014
14/07/04 16:46:55 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:45:49 PDT 2014
2014-07-04 16:46:58:771 310 sec: 3615103 operations; 23155.28 current ops/sec;  [INSERT AverageLatency(us)=805.62]  
14/07/04 16:46:59 INFO client.AsyncProcess: #15, table=usertable, attempt=21/35 failed 2274 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6182, waitTime=2579, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20125 ms, replay 2274 ops.
14/07/04 16:46:59 INFO client.AsyncProcess: #11, table=usertable, attempt=21/35 failed 2245 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6182, waitTime=2579, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20129 ms, replay 2245 ops.
14/07/04 16:46:59 INFO client.AsyncProcess: #3, table=usertable, attempt=21/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6182, waitTime=2579, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014, retrying after 20086 ms, replay 2247 ops.
2014-07-04 16:47:08:772 320 sec: 3619179 operations; 407.56 current ops/sec;  [INSERT AverageLatency(us)=2559.43]  
2014-07-04 16:47:18:773 330 sec: 3729215 operations; 11002.5 current ops/sec; [UPDATE AverageLatency(us)=463680] [INSERT AverageLatency(us)=1219.31] [CLEANUP AverageLatency(us)=463700] 
14/07/04 16:47:20 INFO client.AsyncProcess: #3, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:47:20 INFO client.AsyncProcess: #15, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
14/07/04 16:47:20 INFO client.AsyncProcess: #11, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404516950863, tracking started Fri Jul 04 16:41:51 PDT 2014
2014-07-04 16:47:28:774 340 sec: 4088888 operations; 35963.7 current ops/sec; [UPDATE AverageLatency(us)=2024809] [INSERT AverageLatency(us)=2841.33] [CLEANUP AverageLatency(us)=2024830.5] 
2014-07-04 16:47:38:775 350 sec: 4388614 operations; 29969.6 current ops/sec;  [INSERT AverageLatency(us)=604.08]  
2014-07-04 16:47:48:776 360 sec: 4658405 operations; 26976.4 current ops/sec; [UPDATE AverageLatency(us)=4443340.83] [INSERT AverageLatency(us)=242.11] [CLEANUP AverageLatency(us)=4443367.5] 
2014-07-04 16:47:58:857 370 sec: 4986487 operations; 32544.59 current ops/sec; [UPDATE AverageLatency(us)=1321774] [INSERT AverageLatency(us)=100.01] [CLEANUP AverageLatency(us)=1321801.5] 
2014-07-04 16:48:00:742 372 sec: 5000000 operations; 7172.51 current ops/sec; [UPDATE AverageLatency(us)=897440] [INSERT AverageLatency(us)=268.78] [CLEANUP AverageLatency(us)=897463] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404517682
1404517682
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404517692
1404517692
++ echo /home/hadoop/git/physical_design/caseresult/case14/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case14/random_read_1.dat
Loading workload...
Starting test.
2014-07-04 16:48:14:145 0 sec: 0 operations; 
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/04 16:48:15 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4ef888ea, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/04 16:48:15 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4ef888ea connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/04 16:48:15 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:48:15 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/04 16:48:15 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x14703c1fd050000, negotiated timeout = 90000
2014-07-04 16:48:24:147 10 sec: 79781 operations; 7976.5 current ops/sec; [READ AverageLatency(us)=2482.46] 
2014-07-04 16:48:34:153 20 sec: 228712 operations; 14884.17 current ops/sec; [READ AverageLatency(us)=1338.26] 
2014-07-04 16:48:44:154 30 sec: 361955 operations; 13322.97 current ops/sec; [READ AverageLatency(us)=1495.56] 
2014-07-04 16:48:54:155 40 sec: 497344 operations; 13538.9 current ops/sec; [READ AverageLatency(us)=1471.62] 
2014-07-04 16:49:04:156 50 sec: 632877 operations; 13550.59 current ops/sec; [READ AverageLatency(us)=1470.19] 
2014-07-04 16:49:14:157 60 sec: 765300 operations; 13240.98 current ops/sec; [READ AverageLatency(us)=1504.74] 
2014-07-04 16:49:24:165 70 sec: 920350 operations; 15492.61 current ops/sec; [READ AverageLatency(us)=1285.42] 
2014-07-04 16:49:34:165 80 sec: 1100846 operations; 18049.6 current ops/sec; [READ AverageLatency(us)=1102.85] 
2014-07-04 16:49:44:166 90 sec: 1288161 operations; 18729.63 current ops/sec; [READ AverageLatency(us)=1062.46] 
2014-07-04 16:49:54:167 100 sec: 1474301 operations; 18612.14 current ops/sec; [READ AverageLatency(us)=1069.25] 
2014-07-04 16:50:04:167 110 sec: 1663481 operations; 18918 current ops/sec; [READ AverageLatency(us)=1052] 
2014-07-04 16:50:14:168 120 sec: 1848786 operations; 18528.65 current ops/sec; [READ AverageLatency(us)=1074.08] 
2014-07-04 16:50:24:169 130 sec: 2019246 operations; 17046 current ops/sec; [READ AverageLatency(us)=1168.04] 
2014-07-04 16:50:34:169 140 sec: 2203902 operations; 18463.75 current ops/sec; [READ AverageLatency(us)=1077.94] 
2014-07-04 16:50:44:170 150 sec: 2388279 operations; 18435.86 current ops/sec; [READ AverageLatency(us)=1079.42] 
2014-07-04 16:50:54:171 160 sec: 2574075 operations; 18579.6 current ops/sec; [READ AverageLatency(us)=1071.25] 
2014-07-04 16:51:04:171 170 sec: 2760266 operations; 18617.24 current ops/sec; [READ AverageLatency(us)=1068.95] 
2014-07-04 16:51:14:172 180 sec: 2944986 operations; 18470.15 current ops/sec; [READ AverageLatency(us)=1077.51] 
2014-07-04 16:51:24:172 190 sec: 3129897 operations; 18491.1 current ops/sec; [READ AverageLatency(us)=1076.4] 
2014-07-04 16:51:34:173 200 sec: 3298180 operations; 16826.62 current ops/sec; [READ AverageLatency(us)=1183.33] 
2014-07-04 16:51:44:174 210 sec: 3480113 operations; 18191.48 current ops/sec; [READ AverageLatency(us)=1094.14] 
2014-07-04 16:51:54:174 220 sec: 3661723 operations; 18161 current ops/sec; [READ AverageLatency(us)=1095.94] 
2014-07-04 16:52:04:176 230 sec: 3837222 operations; 17546.39 current ops/sec; [READ AverageLatency(us)=1133.96] 
2014-07-04 16:52:14:176 240 sec: 4025319 operations; 18809.7 current ops/sec; [READ AverageLatency(us)=1058.04] 
2014-07-04 16:52:24:178 250 sec: 4209514 operations; 18415.82 current ops/sec; [READ AverageLatency(us)=1080.67] 
2014-07-04 16:52:34:178 260 sec: 4393775 operations; 18426.1 current ops/sec; [READ AverageLatency(us)=1080.3] 
2014-07-04 16:52:44:179 270 sec: 4578104 operations; 18431.06 current ops/sec; [READ AverageLatency(us)=1079.83] 
2014-07-04 16:52:54:180 280 sec: 4747601 operations; 16948.01 current ops/sec; [READ AverageLatency(us)=1174.74] 
2014-07-04 16:53:04:180 290 sec: 4930135 operations; 18253.4 current ops/sec; [READ AverageLatency(us)=1090.55] 
2014-07-04 16:53:08:035 293 sec: 5000000 operations; 18123.22 current ops/sec; [UPDATE AverageLatency(us)=13.5] [READ AverageLatency(us)=966.78] [CLEANUP AverageLatency(us)=280.95] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404517988
1404517988
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404517998
1404517998
++ echo /home/hadoop/git/physical_design/caseresult/case14/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case14/workloada_1.dat
Loading workload...
Starting test.
2014-07-04 16:53:19:875 0 sec: 0 operations; 
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/04 16:53:20 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x401d9313, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/04 16:53:20 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x401d9313 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/04 16:53:20 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:53:20 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/04 16:53:20 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x4703c201950000, negotiated timeout = 90000
2014-07-04 16:53:29:877 10 sec: 31151 operations; 3106.71 current ops/sec; [INSERT AverageLatency(us)=413.44] [READ AverageLatency(us)=4029.96] 
2014-07-04 16:53:39:879 20 sec: 148400 operations; 11722.56 current ops/sec; [INSERT AverageLatency(us)=19.56] [READ AverageLatency(us)=1751.26] 
2014-07-04 16:53:49:880 30 sec: 260196 operations; 11178.48 current ops/sec; [INSERT AverageLatency(us)=13.91] [READ AverageLatency(us)=1937.03] 
2014-07-04 16:53:59:882 40 sec: 388177 operations; 12795.54 current ops/sec; [INSERT AverageLatency(us)=13.52] [READ AverageLatency(us)=1744.4] 
2014-07-04 16:54:09:882 50 sec: 531029 operations; 14285.2 current ops/sec; [INSERT AverageLatency(us)=14.26] [READ AverageLatency(us)=1539.07] 
2014-07-04 16:54:19:883 60 sec: 690967 operations; 15992.2 current ops/sec; [INSERT AverageLatency(us)=12.98] [READ AverageLatency(us)=1375.82] 
2014-07-04 16:54:29:884 70 sec: 834421 operations; 14343.97 current ops/sec; [INSERT AverageLatency(us)=14.72] [READ AverageLatency(us)=1536.03] 
2014-07-04 16:54:39:890 80 sec: 942711 operations; 10823.59 current ops/sec; [INSERT AverageLatency(us)=54.59] [READ AverageLatency(us)=1993.27] 
2014-07-04 16:54:49:890 90 sec: 1072086 operations; 12936.21 current ops/sec; [INSERT AverageLatency(us)=20.27] [READ AverageLatency(us)=1737.48] 
2014-07-04 16:54:59:891 100 sec: 1191923 operations; 11982.5 current ops/sec; [INSERT AverageLatency(us)=42.52] [READ AverageLatency(us)=1838.97] 
2014-07-04 16:55:09:892 110 sec: 1338372 operations; 14643.44 current ops/sec; [INSERT AverageLatency(us)=20.73] [READ AverageLatency(us)=1504.87] 
2014-07-04 16:55:19:893 120 sec: 1516288 operations; 17791.6 current ops/sec; [INSERT AverageLatency(us)=24.24] [READ AverageLatency(us)=1238.51] 
2014-07-04 16:55:29:894 130 sec: 1677305 operations; 16098.48 current ops/sec; [INSERT AverageLatency(us)=18.32] [READ AverageLatency(us)=1370.25] 
2014-07-04 16:55:39:895 140 sec: 1847731 operations; 17040.9 current ops/sec; [INSERT AverageLatency(us)=15.16] [READ AverageLatency(us)=1293.97] 
2014-07-04 16:55:49:896 150 sec: 1951878 operations; 10413.66 current ops/sec; [INSERT AverageLatency(us)=30.23] [READ AverageLatency(us)=2113.81] 
2014-07-04 16:55:59:897 160 sec: 2104832 operations; 15293.87 current ops/sec; [INSERT AverageLatency(us)=16.3] [READ AverageLatency(us)=1453.63] 
2014-07-04 16:56:09:899 170 sec: 2268157 operations; 16329.23 current ops/sec; [INSERT AverageLatency(us)=19.19] [READ AverageLatency(us)=1350.49] 
2014-07-04 16:56:19:901 180 sec: 2446702 operations; 17850.93 current ops/sec; [INSERT AverageLatency(us)=24.63] [READ AverageLatency(us)=1233.68] 
2014-07-04 16:56:29:902 190 sec: 2620763 operations; 17404.36 current ops/sec; [INSERT AverageLatency(us)=19.68] [READ AverageLatency(us)=1264.87] 
2014-07-04 16:56:39:904 200 sec: 2769129 operations; 14833.63 current ops/sec; [INSERT AverageLatency(us)=20.92] [READ AverageLatency(us)=1489.25] 
2014-07-04 16:56:49:905 210 sec: 2845198 operations; 7606.14 current ops/sec; [INSERT AverageLatency(us)=59.95] [READ AverageLatency(us)=2897.7] 
2014-07-04 16:56:59:906 220 sec: 2955451 operations; 11024.2 current ops/sec; [INSERT AverageLatency(us)=23.82] [READ AverageLatency(us)=2005.51] 
2014-07-04 16:57:09:908 230 sec: 3052800 operations; 9733.93 current ops/sec; [INSERT AverageLatency(us)=23.38] [READ AverageLatency(us)=2271.04] 
2014-07-04 16:57:19:909 240 sec: 3148989 operations; 9616.98 current ops/sec; [INSERT AverageLatency(us)=18.61] [READ AverageLatency(us)=2298.44] 
2014-07-04 16:57:29:917 250 sec: 3282701 operations; 13360.51 current ops/sec; [INSERT AverageLatency(us)=18.25] [READ AverageLatency(us)=1653.89] 
2014-07-04 16:57:39:918 260 sec: 3425976 operations; 14326.07 current ops/sec; [INSERT AverageLatency(us)=20.95] [READ AverageLatency(us)=1538.21] 
2014-07-04 16:57:49:918 270 sec: 3583455 operations; 15747.9 current ops/sec; [INSERT AverageLatency(us)=15.57] [READ AverageLatency(us)=1402.79] 
2014-07-04 16:57:59:919 280 sec: 3738286 operations; 15481.55 current ops/sec; [INSERT AverageLatency(us)=20.6] [READ AverageLatency(us)=1428.33] 
2014-07-04 16:58:09:920 290 sec: 3873817 operations; 13551.74 current ops/sec; [INSERT AverageLatency(us)=27.71] [READ AverageLatency(us)=1627.43] 
2014-07-04 16:58:19:921 300 sec: 4028197 operations; 15436.46 current ops/sec; [INSERT AverageLatency(us)=15.62] [READ AverageLatency(us)=1428.54] 
2014-07-04 16:58:29:922 310 sec: 4221305 operations; 19308.87 current ops/sec; [INSERT AverageLatency(us)=14.05] [READ AverageLatency(us)=2284.87] 
2014-07-04 16:58:39:922 320 sec: 4401505 operations; 18020 current ops/sec; [INSERT AverageLatency(us)=15.74] [READ AverageLatency(us)=1219.79] 
2014-07-04 16:58:49:923 330 sec: 4598425 operations; 19690.03 current ops/sec; [INSERT AverageLatency(us)=14.02] [READ AverageLatency(us)=1123.75] 
2014-07-04 16:58:59:924 340 sec: 4717780 operations; 11934.31 current ops/sec; [INSERT AverageLatency(us)=23.97] [READ AverageLatency(us)=1854.88] 
2014-07-04 16:59:09:925 350 sec: 4876693 operations; 15891.3 current ops/sec; [INSERT AverageLatency(us)=17.07] [READ AverageLatency(us)=1389.53] 
2014-07-04 16:59:17:915 358 sec: 5000000 operations; 15430.73 current ops/sec; [UPDATE AverageLatency(us)=138633] [INSERT AverageLatency(us)=13.51] [READ AverageLatency(us)=1229.85] [CLEANUP AverageLatency(us)=138814.3] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404518358
1404518358
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404518368
1404518368
++ echo /home/hadoop/git/physical_design/caseresult/case14/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case14/workloadb_1.dat
Loading workload...
Starting test.
2014-07-04 16:59:30:221 0 sec: 0 operations; 
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/04 16:59:30 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x7a38f07b, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/04 16:59:30 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x7a38f07b connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/04 16:59:30 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 16:59:30 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/04 16:59:30 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x14703c1fd050001, negotiated timeout = 90000
2014-07-04 16:59:40:233 10 sec: 23254 operations; 2322.38 current ops/sec; [INSERT AverageLatency(us)=570.47] [READ AverageLatency(us)=5454.93] 
2014-07-04 16:59:50:235 20 sec: 187644 operations; 16435.71 current ops/sec; [INSERT AverageLatency(us)=31.62] [READ AverageLatency(us)=1972.1] 
2014-07-04 17:00:00:236 30 sec: 337238 operations; 14957.9 current ops/sec; [INSERT AverageLatency(us)=24.87] [READ AverageLatency(us)=2505.45] 
2014-07-04 17:00:10:237 40 sec: 470704 operations; 13345.27 current ops/sec; [INSERT AverageLatency(us)=38.29] [READ AverageLatency(us)=2974.21] 
2014-07-04 17:00:20:238 50 sec: 626226 operations; 15550.64 current ops/sec; [INSERT AverageLatency(us)=20.55] [READ AverageLatency(us)=2560] 
2014-07-04 17:00:30:238 60 sec: 739315 operations; 11308.9 current ops/sec; [INSERT AverageLatency(us)=17.46] [READ AverageLatency(us)=3490.89] 
2014-07-04 17:00:40:239 70 sec: 892954 operations; 15362.36 current ops/sec; [INSERT AverageLatency(us)=22.65] [READ AverageLatency(us)=2577.13] 
2014-07-04 17:00:50:240 80 sec: 1033014 operations; 14004.6 current ops/sec; [INSERT AverageLatency(us)=19.55] [READ AverageLatency(us)=2830.12] 
2014-07-04 17:01:00:241 90 sec: 1160400 operations; 12738.6 current ops/sec; [INSERT AverageLatency(us)=27.13] [READ AverageLatency(us)=3093.27] 
2014-07-04 17:01:10:241 100 sec: 1316041 operations; 15562.54 current ops/sec; [INSERT AverageLatency(us)=30.76] [READ AverageLatency(us)=2489.33] 
2014-07-04 17:01:20:242 110 sec: 1491490 operations; 17543.15 current ops/sec; [INSERT AverageLatency(us)=21.01] [READ AverageLatency(us)=2147.93] 
2014-07-04 17:01:30:243 120 sec: 1625756 operations; 13426.6 current ops/sec; [INSERT AverageLatency(us)=23.77] [READ AverageLatency(us)=3092.26] 
2014-07-04 17:01:40:243 130 sec: 1754038 operations; 12826.92 current ops/sec; [INSERT AverageLatency(us)=20.55] [READ AverageLatency(us)=3085.31] 
2014-07-04 17:01:50:244 140 sec: 1896371 operations; 14231.88 current ops/sec; [INSERT AverageLatency(us)=20.55] [READ AverageLatency(us)=2760.42] 
2014-07-04 17:02:00:245 150 sec: 2068228 operations; 17185.7 current ops/sec; [INSERT AverageLatency(us)=19.18] [READ AverageLatency(us)=2250.16] 
2014-07-04 17:02:10:245 160 sec: 2185472 operations; 11723.23 current ops/sec; [INSERT AverageLatency(us)=18.77] [READ AverageLatency(us)=3418.56] 
2014-07-04 17:02:20:246 170 sec: 2273795 operations; 8831.42 current ops/sec; [INSERT AverageLatency(us)=18.84] [READ AverageLatency(us)=4448.19] 
2014-07-04 17:02:30:247 180 sec: 2393052 operations; 11924.51 current ops/sec; [INSERT AverageLatency(us)=18.2] [READ AverageLatency(us)=3317.87] 
2014-07-04 17:02:40:247 190 sec: 2486090 operations; 9303.8 current ops/sec; [INSERT AverageLatency(us)=19.18] [READ AverageLatency(us)=4334.1] 
2014-07-04 17:02:50:248 200 sec: 2624408 operations; 13830.42 current ops/sec; [INSERT AverageLatency(us)=21.67] [READ AverageLatency(us)=2831.62] 
2014-07-04 17:03:00:249 210 sec: 2729178 operations; 10475.95 current ops/sec; [INSERT AverageLatency(us)=20.85] [READ AverageLatency(us)=3820.31] 
2014-07-04 17:03:10:282 220 sec: 2825475 operations; 9598.03 current ops/sec; [INSERT AverageLatency(us)=20.63] [READ AverageLatency(us)=4058.66] 
2014-07-04 17:03:20:289 230 sec: 2952114 operations; 12655.04 current ops/sec; [INSERT AverageLatency(us)=20.35] [READ AverageLatency(us)=3197.63] 
2014-07-04 17:03:30:290 240 sec: 3006127 operations; 5400.76 current ops/sec; [INSERT AverageLatency(us)=26.15] [READ AverageLatency(us)=7351.23] 
2014-07-04 17:03:40:290 250 sec: 3098075 operations; 9194.8 current ops/sec; [INSERT AverageLatency(us)=36.88] [READ AverageLatency(us)=4296.04] 
2014-07-04 17:03:50:314 260 sec: 3196036 operations; 9772.65 current ops/sec; [INSERT AverageLatency(us)=41.13] [READ AverageLatency(us)=4019.5] 
2014-07-04 17:04:00:332 270 sec: 3300173 operations; 10394.99 current ops/sec; [INSERT AverageLatency(us)=18.43] [READ AverageLatency(us)=3848.77] 
2014-07-04 17:04:10:345 280 sec: 3399686 operations; 9938.38 current ops/sec; [INSERT AverageLatency(us)=20.05] [READ AverageLatency(us)=3971.59] 
2014-07-04 17:04:20:351 290 sec: 3511177 operations; 11142.41 current ops/sec; [INSERT AverageLatency(us)=35.22] [READ AverageLatency(us)=3569.53] 
2014-07-04 17:04:30:375 300 sec: 3598531 operations; 8714.49 current ops/sec; [INSERT AverageLatency(us)=17.52] [READ AverageLatency(us)=4575.04] 
2014-07-04 17:04:40:381 310 sec: 3724445 operations; 12583.85 current ops/sec; [INSERT AverageLatency(us)=15.76] [READ AverageLatency(us)=3139.14] 
2014-07-04 17:04:50:388 320 sec: 3805037 operations; 8053.56 current ops/sec; [INSERT AverageLatency(us)=39.79] [READ AverageLatency(us)=4917.68] 
2014-07-04 17:05:00:406 330 sec: 3904142 operations; 9892.69 current ops/sec; [INSERT AverageLatency(us)=16.22] [READ AverageLatency(us)=4005.17] 
2014-07-04 17:05:10:407 340 sec: 3985411 operations; 8126.09 current ops/sec; [INSERT AverageLatency(us)=35.23] [READ AverageLatency(us)=4845.9] 
2014-07-04 17:05:20:408 350 sec: 4105764 operations; 12034.1 current ops/sec; [INSERT AverageLatency(us)=17.98] [READ AverageLatency(us)=3327.76] 
2014-07-04 17:05:30:409 360 sec: 4201618 operations; 9584.44 current ops/sec; [INSERT AverageLatency(us)=35.39] [READ AverageLatency(us)=4029.26] 
2014-07-04 17:05:40:409 370 sec: 4301455 operations; 9983.7 current ops/sec; [INSERT AverageLatency(us)=26.32] [READ AverageLatency(us)=4044.61] 
2014-07-04 17:05:50:410 380 sec: 4382628 operations; 8116.49 current ops/sec; [INSERT AverageLatency(us)=26.93] [READ AverageLatency(us)=4860.89] 
2014-07-04 17:06:00:439 390 sec: 4464052 operations; 8119.66 current ops/sec; [INSERT AverageLatency(us)=21.75] [READ AverageLatency(us)=4904.72] 
2014-07-04 17:06:10:445 400 sec: 4487194 operations; 2312.58 current ops/sec; [INSERT AverageLatency(us)=20] [READ AverageLatency(us)=4029.63] 
2014-07-04 17:06:20:446 410 sec: 4487194 operations; 0 current ops/sec;   
2014-07-04 17:06:30:447 420 sec: 4487194 operations; 0 current ops/sec;   
2014-07-04 17:06:40:462 430 sec: 4487194 operations; 0 current ops/sec;   
2014-07-04 17:06:50:463 440 sec: 4488521 operations; 132.69 current ops/sec; [INSERT AverageLatency(us)=115.4] [READ AverageLatency(us)=1447022.84] 
2014-07-04 17:07:00:464 450 sec: 4545324 operations; 5680.3 current ops/sec; [INSERT AverageLatency(us)=81.4] [READ AverageLatency(us)=6874.53] 
2014-07-04 17:07:10:464 460 sec: 4637160 operations; 9182.68 current ops/sec; [INSERT AverageLatency(us)=22.23] [READ AverageLatency(us)=4299.68] 
2014-07-04 17:07:20:606 470 sec: 4721826 operations; 8348.06 current ops/sec; [INSERT AverageLatency(us)=24.92] [READ AverageLatency(us)=4765.14] 
2014-07-04 17:07:30:607 480 sec: 4810097 operations; 8826.22 current ops/sec; [INSERT AverageLatency(us)=17.09] [READ AverageLatency(us)=4524.11] 
2014-07-04 17:07:40:608 490 sec: 4888494 operations; 7838.92 current ops/sec; [INSERT AverageLatency(us)=19.24] [READ AverageLatency(us)=5082.72] 
2014-07-04 17:07:50:610 500 sec: 4957575 operations; 6906.72 current ops/sec; [INSERT AverageLatency(us)=16.94] [READ AverageLatency(us)=5763.52] 
2014-07-04 17:07:59:993 509 sec: 5000000 operations; 4521.48 current ops/sec; [UPDATE AverageLatency(us)=248298.35] [INSERT AverageLatency(us)=14] [READ AverageLatency(us)=4307.71] [CLEANUP AverageLatency(us)=248480.25] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404518881
1404518881
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404518891
1404518891
++ echo /home/hadoop/git/physical_design/caseresult/case14/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case14/workloadc_1.dat
Loading workload...
Starting test.
2014-07-04 17:08:13:141 0 sec: 0 operations; 
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/04 17:08:13 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x46f91a48, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/04 17:08:13 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x46f91a48 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/04 17:08:13 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/04 17:08:13 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/04 17:08:13 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x14703c1fd050002, negotiated timeout = 90000
2014-07-04 17:08:23:144 10 sec: 116651 operations; 11661.6 current ops/sec; [INSERT AverageLatency(us)=221.77] [READ AverageLatency(us)=12526.94] 
2014-07-04 17:08:33:146 20 sec: 283657 operations; 16697.26 current ops/sec; [INSERT AverageLatency(us)=27.63] [READ AverageLatency(us)=10968.42] 
2014-07-04 17:08:43:147 30 sec: 430760 operations; 14708.83 current ops/sec; [INSERT AverageLatency(us)=39.57] [READ AverageLatency(us)=13075.16] 
2014-07-04 17:08:53:148 40 sec: 608878 operations; 17810.02 current ops/sec; [INSERT AverageLatency(us)=15.87] [READ AverageLatency(us)=11613.53] 
2014-07-04 17:09:03:149 50 sec: 745774 operations; 13689.6 current ops/sec; [INSERT AverageLatency(us)=28.84] [READ AverageLatency(us)=14152.95] 
2014-07-04 17:09:13:149 60 sec: 852636 operations; 10685.13 current ops/sec; [INSERT AverageLatency(us)=16.69] [READ AverageLatency(us)=18619.36] 
2014-07-04 17:09:23:150 70 sec: 920414 operations; 6777.12 current ops/sec; [INSERT AverageLatency(us)=21.55] [READ AverageLatency(us)=14867.98] 
2014-07-04 17:09:33:315 80 sec: 1021465 operations; 9942.05 current ops/sec; [INSERT AverageLatency(us)=15.26] [READ AverageLatency(us)=29240.65] 
2014-07-04 17:09:43:330 90 sec: 1159951 operations; 13826.48 current ops/sec; [INSERT AverageLatency(us)=14.12] [READ AverageLatency(us)=14280.59] 
2014-07-04 17:09:53:331 100 sec: 1335668 operations; 17569.94 current ops/sec; [INSERT AverageLatency(us)=12.25] [READ AverageLatency(us)=11123.31] 
2014-07-04 17:10:03:402 110 sec: 1459550 operations; 12302.09 current ops/sec; [INSERT AverageLatency(us)=16.6] [READ AverageLatency(us)=15499.78] 
2014-07-04 17:10:13:412 120 sec: 1583312 operations; 12362.6 current ops/sec; [INSERT AverageLatency(us)=16.02] [READ AverageLatency(us)=15131.44] 
2014-07-04 17:10:23:444 130 sec: 1690539 operations; 10688.5 current ops/sec; [INSERT AverageLatency(us)=16.15] [READ AverageLatency(us)=19730.38] 
2014-07-04 17:10:33:445 140 sec: 1851798 operations; 16124.29 current ops/sec; [INSERT AverageLatency(us)=15.38] [READ AverageLatency(us)=12051.57] 
2014-07-04 17:10:43:447 150 sec: 1970894 operations; 11907.22 current ops/sec; [INSERT AverageLatency(us)=15.7] [READ AverageLatency(us)=15628.71] 
2014-07-04 17:10:53:448 160 sec: 2131862 operations; 16095.19 current ops/sec; [INSERT AverageLatency(us)=17.19] [READ AverageLatency(us)=12999.1] 
2014-07-04 17:11:03:459 170 sec: 2273401 operations; 14138.35 current ops/sec; [INSERT AverageLatency(us)=17] [READ AverageLatency(us)=13748.59] 
2014-07-04 17:11:13:461 180 sec: 2418469 operations; 14503.9 current ops/sec; [INSERT AverageLatency(us)=20.26] [READ AverageLatency(us)=13571.38] 
2014-07-04 17:11:23:464 190 sec: 2561637 operations; 14312.51 current ops/sec; [INSERT AverageLatency(us)=16.95] [READ AverageLatency(us)=13651.05] 
2014-07-04 17:11:33:538 200 sec: 2698046 operations; 13540.7 current ops/sec; [INSERT AverageLatency(us)=14.86] [READ AverageLatency(us)=14654.97] 
2014-07-04 17:11:43:540 210 sec: 2818960 operations; 12088.98 current ops/sec; [INSERT AverageLatency(us)=26.19] [READ AverageLatency(us)=16392.99] 
2014-07-04 17:11:53:567 220 sec: 2951954 operations; 13263.59 current ops/sec; [INSERT AverageLatency(us)=22.97] [READ AverageLatency(us)=14630.22] 
2014-07-04 17:12:03:570 230 sec: 3087242 operations; 13524.74 current ops/sec; [INSERT AverageLatency(us)=16.63] [READ AverageLatency(us)=14652.41] 
2014-07-04 17:12:13:592 240 sec: 3234015 operations; 14645.08 current ops/sec; [INSERT AverageLatency(us)=17.02] [READ AverageLatency(us)=13401.09] 
2014-07-04 17:12:23:593 250 sec: 3366362 operations; 13233.38 current ops/sec; [INSERT AverageLatency(us)=19.5] [READ AverageLatency(us)=14633.74] 
2014-07-04 17:12:33:641 260 sec: 3513884 operations; 14681.73 current ops/sec; [INSERT AverageLatency(us)=14.79] [READ AverageLatency(us)=13671.97] 
2014-07-04 17:12:43:643 270 sec: 3661728 operations; 14781.44 current ops/sec; [INSERT AverageLatency(us)=19.23] [READ AverageLatency(us)=13193.38] 
2014-07-04 17:12:53:857 280 sec: 3812019 operations; 14714.22 current ops/sec; [INSERT AverageLatency(us)=15.85] [READ AverageLatency(us)=13605.24] 
2014-07-04 17:13:03:859 290 sec: 3962439 operations; 15038.99 current ops/sec; [INSERT AverageLatency(us)=19.09] [READ AverageLatency(us)=12933.19] 
2014-07-04 17:13:13:947 300 sec: 4124578 operations; 16072.46 current ops/sec; [INSERT AverageLatency(us)=18.31] [READ AverageLatency(us)=12162.49] 
2014-07-04 17:13:23:949 310 sec: 4252093 operations; 12748.95 current ops/sec; [INSERT AverageLatency(us)=24.45] [READ AverageLatency(us)=15227.23] 
2014-07-04 17:13:33:979 320 sec: 4404265 operations; 15171.68 current ops/sec; [INSERT AverageLatency(us)=16.17] [READ AverageLatency(us)=12911.97] 
2014-07-04 17:13:44:005 330 sec: 4547870 operations; 14323.26 current ops/sec; [INSERT AverageLatency(us)=18.56] [READ AverageLatency(us)=13741.79] 
2014-07-04 17:13:54:032 340 sec: 4701392 operations; 15310.86 current ops/sec; [INSERT AverageLatency(us)=18.42] [READ AverageLatency(us)=12671.96] 
2014-07-04 17:14:04:054 350 sec: 4861535 operations; 15979.15 current ops/sec; [INSERT AverageLatency(us)=19.33] [READ AverageLatency(us)=12226.8] 
2014-07-04 17:14:14:054 360 sec: 4991269 operations; 12973.4 current ops/sec; [UPDATE AverageLatency(us)=379840.86] [INSERT AverageLatency(us)=16.58] [READ AverageLatency(us)=12125.28] [CLEANUP AverageLatency(us)=380673] 
2014-07-04 17:14:17:932 364 sec: 5000000 operations; 2251.42 current ops/sec; [UPDATE AverageLatency(us)=319790.33] [INSERT AverageLatency(us)=17.96] [READ AverageLatency(us)=11167.52] [CLEANUP AverageLatency(us)=319808] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404519259
1404519259
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
