++ ls caseresult/ -ltr
++ wc -l
+ filename=case74
+ mkdir caseresult/case74
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case74
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case74
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case74.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 3.4920 seconds

0 row(s) in 0.7500 seconds

0 row(s) in 0.0740 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case74/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case74/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case74/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case74/create_1.script
/home/hadoop/git/physical_design/caseresult/case74/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case74/create_1.script
0 row(s) in 1.8150 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405035894
1405035894
++ echo /home/hadoop/git/physical_design/caseresult/case74/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case74/load_1.dat
Loading workload...
Starting test.
2014-07-10 16:44:54:983 0 sec: 0 operations; 
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 16:44:55 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 16:44:55 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 16:44:55 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:44:55 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 16:44:55 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x4724567cce000b, negotiated timeout = 90000
2014-07-10 16:45:04:984 10 sec: 245121 operations; 24509.65 current ops/sec; [INSERT AverageLatency(us)=531.16] 
2014-07-10 16:45:14:985 20 sec: 253783 operations; 866.11 current ops/sec; [INSERT AverageLatency(us)=331.24] 
2014-07-10 16:45:24:986 30 sec: 287430 operations; 3364.36 current ops/sec; [INSERT AverageLatency(us)=3185.36] 
2014-07-10 16:45:34:986 40 sec: 653428 operations; 36599.8 current ops/sec; [INSERT AverageLatency(us)=660.03] 
2014-07-10 16:45:44:987 50 sec: 706700 operations; 5326.67 current ops/sec; [INSERT AverageLatency(us)=385.95] 
14/07/10 16:45:53 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10026 ms, replay 2296 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10014 ms, replay 2255 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10011 ms, replay 2268 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10037 ms, replay 2283 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10087 ms, replay 2291 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10041 ms, replay 2203 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10032 ms, replay 2217 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10090 ms, replay 2236 ops.
14/07/10 16:45:53 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44879 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10002 ms, replay 2215 ops.
2014-07-10 16:45:54:987 60 sec: 746807 operations; 4010.7 current ops/sec; [INSERT AverageLatency(us)=3526.77] 
2014-07-10 16:46:04:988 70 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:46:14 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10003 ms, replay 2236 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10097 ms, replay 2268 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10038 ms, replay 2203 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10033 ms, replay 2291 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10089 ms, replay 2283 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10017 ms, replay 2215 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10025 ms, replay 2255 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10053 ms, replay 2296 ops.
14/07/10 16:46:14 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 10085 ms, replay 2217 ops.
2014-07-10 16:46:14:988 80 sec: 746807 operations; 0 current ops/sec;  
2014-07-10 16:46:24:989 90 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:46:27 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20015 ms, replay 2296 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20136 ms, replay 2283 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20038 ms, replay 2291 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20157 ms, replay 2203 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20038 ms, replay 2215 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20137 ms, replay 2268 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20133 ms, replay 2217 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20050 ms, replay 2255 ops.
14/07/10 16:46:27 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44881 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20031 ms, replay 2236 ops.
2014-07-10 16:46:34:989 100 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:46:41 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4724567cce000b, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 16:46:42 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:46:42 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 16:46:42 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x4724567cce000b, negotiated timeout = 90000
14/07/10 16:46:43 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4724567cce000b, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 16:46:44 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:46:44 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 16:46:44 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4724567cce000b, likely server has closed socket, closing socket connection and attempting reconnect
2014-07-10 16:46:44:990 110 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:46:45 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:46:45 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 16:46:45 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x4724567cce000b, negotiated timeout = 90000
14/07/10 16:46:51 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2236 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20066 ms, replay 2236 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20029 ms, replay 2255 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2291 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20108 ms, replay 2291 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2296 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20052 ms, replay 2296 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2203 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20054 ms, replay 2203 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2217 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20070 ms, replay 2217 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2215 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20166 ms, replay 2215 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2283 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20127 ms, replay 2283 ops.
14/07/10 16:46:51 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2268 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20015 ms, replay 2268 ops.
2014-07-10 16:46:54:990 120 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:46:55 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1468 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10014 ms, replay 1468 ops.
14/07/10 16:46:55 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1369 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10007 ms, replay 1369 ops.
14/07/10 16:46:55 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2278 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:34 PDT 2014, retrying after 10094 ms, replay 2278 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 823 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10018 ms, replay 823 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1537 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10009 ms, replay 1537 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2464 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10089 ms, replay 2464 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1833 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10001 ms, replay 1833 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1509 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10002 ms, replay 1509 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2099 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10055 ms, replay 2099 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2025 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10004 ms, replay 2025 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1505 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10017 ms, replay 1505 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2494 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10078 ms, replay 2494 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 810 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10011 ms, replay 810 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2265 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10059 ms, replay 2265 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2239 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10017 ms, replay 2239 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1835 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10044 ms, replay 1835 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1453 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10012 ms, replay 1453 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1465 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10098 ms, replay 1465 ops.
14/07/10 16:46:57 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1973 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10088 ms, replay 1973 ops.
2014-07-10 16:47:04:992 130 sec: 746807 operations; 0 current ops/sec;  
14/07/10 16:47:07 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:07 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:07 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:34 PDT 2014
14/07/10 16:47:09 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:10 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 810 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10008 ms, replay 810 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2218 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10092 ms, replay 2218 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2025 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10099 ms, replay 2025 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 1973 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10046 ms, replay 1973 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 845 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10013 ms, replay 845 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 909 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:52 PDT 2014, retrying after 10069 ms, replay 909 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2464 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10030 ms, replay 2464 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2265 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10026 ms, replay 2265 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 567 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 10019 ms, replay 567 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1127 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 10094 ms, replay 1127 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 1453 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10041 ms, replay 1453 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1835 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10088 ms, replay 1835 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1505 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10073 ms, replay 1505 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1509 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10065 ms, replay 1509 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2494 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10007 ms, replay 2494 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 10084 ms, replay 2239 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1607 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10045 ms, replay 1607 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1465 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10068 ms, replay 1465 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1349 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10054 ms, replay 1349 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 792 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10014 ms, replay 792 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2099 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10034 ms, replay 2099 ops.
14/07/10 16:47:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 823 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1230, waitTime=2470, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 10076 ms, replay 823 ops.
14/07/10 16:47:12 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:47:12 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:47:12 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:47:12 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:47:13 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:47:14 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1282, waitTime=2493, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20178 ms, replay 2217 ops.
14/07/10 16:47:14 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1282, waitTime=2493, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20081 ms, replay 2291 ops.
14/07/10 16:47:14 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1282, waitTime=2493, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20150 ms, replay 2215 ops.
14/07/10 16:47:14 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1282, waitTime=2493, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20072 ms, replay 2283 ops.
2014-07-10 16:47:14:992 140 sec: 808608 operations; 6179.48 current ops/sec; [INSERT AverageLatency(us)=14529.04] 
14/07/10 16:47:21 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:22 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014
14/07/10 16:47:22 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2265 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20016 ms, replay 2265 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20058 ms, replay 2239 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2099 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20172 ms, replay 2099 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 845 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10026 ms, replay 845 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2218 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 10081 ms, replay 2218 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2494 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20089 ms, replay 2494 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1509 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20062 ms, replay 1509 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1465 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 20036 ms, replay 1465 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2464 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20152 ms, replay 2464 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 1973 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20015 ms, replay 1973 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 567 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 10083 ms, replay 567 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1505 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 20191 ms, replay 1505 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 823 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20017 ms, replay 823 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1607 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10006 ms, replay 1607 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 1835 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20040 ms, replay 1835 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1127 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 10039 ms, replay 1127 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 909 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:52 PDT 2014, retrying after 10077 ms, replay 909 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 1453 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 20195 ms, replay 1453 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2025 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014, retrying after 20103 ms, replay 2025 ops.
14/07/10 16:47:22 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 792 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1430, waitTime=2626, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 10074 ms, replay 792 ops.
2014-07-10 16:47:24:992 150 sec: 960894 operations; 15228.6 current ops/sec; [INSERT AverageLatency(us)=2186.56] 
2014-07-10 16:47:34:993 160 sec: 964772 operations; 387.76 current ops/sec; [INSERT AverageLatency(us)=485.54] 
14/07/10 16:47:35 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 845 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 20123 ms, replay 845 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 567 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 20044 ms, replay 567 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 1127 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 20083 ms, replay 1127 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 909 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:52 PDT 2014, retrying after 20184 ms, replay 909 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 792 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 20051 ms, replay 792 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2218 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 20194 ms, replay 2218 ops.
14/07/10 16:47:35 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 1607 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 20012 ms, replay 1607 ops.
14/07/10 16:47:38 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1596, waitTime=3965, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20178 ms, replay 2215 ops.
14/07/10 16:47:38 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1596, waitTime=3965, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20093 ms, replay 2291 ops.
14/07/10 16:47:38 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1596, waitTime=3965, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20060 ms, replay 2283 ops.
14/07/10 16:47:38 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1596, waitTime=3965, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20025 ms, replay 2217 ops.
14/07/10 16:47:43 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:43 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:43 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:43 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:43 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:36 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014
14/07/10 16:47:44 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1700, waitTime=2137, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20158 ms, replay 2239 ops.
14/07/10 16:47:44 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2464 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1700, waitTime=2137, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014, retrying after 20059 ms, replay 2464 ops.
2014-07-10 16:47:44:994 170 sec: 1006079 operations; 4130.7 current ops/sec; [INSERT AverageLatency(us)=8613.07] 
2014-07-10 16:47:55:032 180 sec: 1243641 operations; 23663.91 current ops/sec; [INSERT AverageLatency(us)=1016.04] 
14/07/10 16:47:56 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014
14/07/10 16:47:57 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 567 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 20190 ms, replay 567 ops.
14/07/10 16:47:57 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 792 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 20075 ms, replay 792 ops.
14/07/10 16:47:57 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2218 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014, retrying after 20038 ms, replay 2218 ops.
14/07/10 16:47:57 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 845 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014, retrying after 20012 ms, replay 845 ops.
14/07/10 16:47:57 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 1127 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014, retrying after 20119 ms, replay 1127 ops.
14/07/10 16:47:57 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 909 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2055, waitTime=2179, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:52 PDT 2014, retrying after 20079 ms, replay 909 ops.
14/07/10 16:48:00 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2108, waitTime=2632, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20012 ms, replay 2283 ops.
14/07/10 16:48:00 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2108, waitTime=2632, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20151 ms, replay 2217 ops.
14/07/10 16:48:00 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2108, waitTime=2632, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20147 ms, replay 2215 ops.
14/07/10 16:48:00 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2108, waitTime=2632, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20093 ms, replay 2291 ops.
2014-07-10 16:48:05:033 190 sec: 1423026 operations; 17936.71 current ops/sec; [INSERT AverageLatency(us)=492.06] 
14/07/10 16:48:06 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014
14/07/10 16:48:06 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:32 PDT 2014
2014-07-10 16:48:15:033 200 sec: 1723814 operations; 30078.8 current ops/sec; [INSERT AverageLatency(us)=1364.51] 
14/07/10 16:48:18 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014
14/07/10 16:48:18 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:52 PDT 2014
14/07/10 16:48:18 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:51 PDT 2014
14/07/10 16:48:18 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014
14/07/10 16:48:18 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:54 PDT 2014
14/07/10 16:48:19 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:45:35 PDT 2014
14/07/10 16:48:22 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=2171, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20065 ms, replay 2217 ops.
14/07/10 16:48:22 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=2171, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20175 ms, replay 2291 ops.
14/07/10 16:48:22 INFO client.AsyncProcess: #17, table=usertable, attempt=17/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=2171, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20193 ms, replay 2215 ops.
14/07/10 16:48:22 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=2171, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20091 ms, replay 2283 ops.
2014-07-10 16:48:25:034 210 sec: 1984543 operations; 26070.29 current ops/sec; [INSERT AverageLatency(us)=1324.8] 
2014-07-10 16:48:35:034 220 sec: 2019439 operations; 3489.6 current ops/sec; [INSERT AverageLatency(us)=2485.76] 
2014-07-10 16:48:45:035 230 sec: 2219862 operations; 20040.3 current ops/sec; [INSERT AverageLatency(us)=601.62] 
14/07/10 16:48:45 INFO client.AsyncProcess: #5, table=usertable, attempt=18/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3310, waitTime=2423, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20142 ms, replay 2283 ops.
14/07/10 16:48:45 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3310, waitTime=2423, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20026 ms, replay 2217 ops.
14/07/10 16:48:45 INFO client.AsyncProcess: #6, table=usertable, attempt=18/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3310, waitTime=2423, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20003 ms, replay 2291 ops.
14/07/10 16:48:45 INFO client.AsyncProcess: #17, table=usertable, attempt=18/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3310, waitTime=2423, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20085 ms, replay 2215 ops.
2014-07-10 16:48:55:035 240 sec: 2234368 operations; 1450.6 current ops/sec; [INSERT AverageLatency(us)=1991.58] 
2014-07-10 16:49:05:036 250 sec: 2477836 operations; 24344.37 current ops/sec; [INSERT AverageLatency(us)=749.45] 
14/07/10 16:49:07 INFO client.AsyncProcess: #2, table=usertable, attempt=19/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3809, waitTime=2201, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20064 ms, replay 2217 ops.
14/07/10 16:49:07 INFO client.AsyncProcess: #6, table=usertable, attempt=19/35 failed 2291 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3809, waitTime=2201, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20121 ms, replay 2291 ops.
14/07/10 16:49:07 INFO client.AsyncProcess: #17, table=usertable, attempt=19/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3809, waitTime=2201, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20186 ms, replay 2215 ops.
14/07/10 16:49:07 INFO client.AsyncProcess: #5, table=usertable, attempt=19/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3809, waitTime=2201, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20045 ms, replay 2283 ops.
14/07/10 16:49:11 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2140 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3951, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10007 ms, replay 2140 ops.
14/07/10 16:49:11 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2268 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3951, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10033 ms, replay 2268 ops.
14/07/10 16:49:11 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2029 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3951, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014, retrying after 10002 ms, replay 2029 ops.
14/07/10 16:49:11 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3951, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014, retrying after 10075 ms, replay 2289 ops.
14/07/10 16:49:11 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3955, waitTime=2047, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10056 ms, replay 2250 ops.
2014-07-10 16:49:15:036 260 sec: 2786534 operations; 30869.8 current ops/sec; [INSERT AverageLatency(us)=393.53] 
14/07/10 16:49:24 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2250 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4272, waitTime=2364, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10073 ms, replay 2250 ops.
14/07/10 16:49:24 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2140 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4272, waitTime=2364, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10054 ms, replay 2140 ops.
14/07/10 16:49:24 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2029 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4272, waitTime=2364, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014, retrying after 10064 ms, replay 2029 ops.
14/07/10 16:49:24 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2268 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4272, waitTime=2364, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014, retrying after 10017 ms, replay 2268 ops.
14/07/10 16:49:24 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4272, waitTime=2364, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014, retrying after 10072 ms, replay 2289 ops.
2014-07-10 16:49:25:037 270 sec: 2970359 operations; 18380.66 current ops/sec; [INSERT AverageLatency(us)=429.62] 
14/07/10 16:49:29 INFO client.AsyncProcess: #2, table=usertable, attempt=20/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4435, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20080 ms, replay 2217 ops.
14/07/10 16:49:29 INFO client.AsyncProcess: #6, table=usertable, attempt=20/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:49:29 INFO client.AsyncProcess: #5, table=usertable, attempt=20/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4435, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20176 ms, replay 2283 ops.
14/07/10 16:49:29 INFO client.AsyncProcess: #17, table=usertable, attempt=20/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4435, waitTime=2120, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20187 ms, replay 2215 ops.
2014-07-10 16:49:35:037 280 sec: 3250725 operations; 28036.6 current ops/sec; [INSERT AverageLatency(us)=1306.43] 
14/07/10 16:49:37 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014
14/07/10 16:49:37 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014
14/07/10 16:49:38 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014
14/07/10 16:49:38 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:19 PDT 2014
14/07/10 16:49:38 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:48:20 PDT 2014
2014-07-10 16:49:45:046 290 sec: 3376068 operations; 12523.03 current ops/sec; [INSERT AverageLatency(us)=4261.31] 
14/07/10 16:49:52 INFO client.AsyncProcess: #5, table=usertable, attempt=21/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4763, waitTime=2125, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20018 ms, replay 2283 ops.
14/07/10 16:49:52 INFO client.AsyncProcess: #2, table=usertable, attempt=21/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4763, waitTime=2125, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20100 ms, replay 2217 ops.
14/07/10 16:49:52 INFO client.AsyncProcess: #17, table=usertable, attempt=21/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4763, waitTime=2125, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20131 ms, replay 2215 ops.
2014-07-10 16:49:55:047 300 sec: 3553238 operations; 17715.23 current ops/sec; [INSERT AverageLatency(us)=944.83] 
2014-07-10 16:50:05:047 310 sec: 3557178 operations; 394 current ops/sec; [INSERT AverageLatency(us)=1883.03] 
14/07/10 16:50:14 INFO client.AsyncProcess: #2, table=usertable, attempt=22/35 failed 2217 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5337, waitTime=2198, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20010 ms, replay 2217 ops.
14/07/10 16:50:14 INFO client.AsyncProcess: #5, table=usertable, attempt=22/35 failed 2283 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5337, waitTime=2198, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20171 ms, replay 2283 ops.
14/07/10 16:50:14 INFO client.AsyncProcess: #17, table=usertable, attempt=22/35 failed 2215 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5337, waitTime=2198, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014, retrying after 20091 ms, replay 2215 ops.
2014-07-10 16:50:15:053 320 sec: 3794708 operations; 23738.76 current ops/sec; [INSERT AverageLatency(us)=808.61] 
2014-07-10 16:50:25:053 330 sec: 3975956 operations; 18124.8 current ops/sec; [INSERT AverageLatency(us)=1066.46] 
2014-07-10 16:50:35:054 340 sec: 4229197 operations; 25321.57 current ops/sec; [INSERT AverageLatency(us)=761.38] 
14/07/10 16:50:36 INFO client.AsyncProcess: #17, table=usertable, attempt=23/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:50:36 INFO client.AsyncProcess: #5, table=usertable, attempt=23/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:50:36 INFO client.AsyncProcess: #2, table=usertable, attempt=23/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:44:57 PDT 2014
14/07/10 16:50:40 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5919, waitTime=2105, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 10042 ms, replay 2239 ops.
14/07/10 16:50:40 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5919, waitTime=2105, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 10045 ms, replay 2255 ops.
2014-07-10 16:50:45:054 350 sec: 4529387 operations; 30019 current ops/sec; [INSERT AverageLatency(us)=4006.79] 
14/07/10 16:50:52 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6321, waitTime=2013, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 10060 ms, replay 2255 ops.
14/07/10 16:50:52 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6321, waitTime=2013, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 10009 ms, replay 2239 ops.
2014-07-10 16:50:55:055 360 sec: 4539004 operations; 961.6 current ops/sec; [INSERT AverageLatency(us)=364.12] 
14/07/10 16:51:04 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6598, waitTime=2055, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20040 ms, replay 2255 ops.
14/07/10 16:51:04 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6598, waitTime=2055, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20061 ms, replay 2239 ops.
2014-07-10 16:51:05:055 370 sec: 4539004 operations; 0 current ops/sec;  
2014-07-10 16:51:15:056 380 sec: 4681781 operations; 14276.27 current ops/sec; [INSERT AverageLatency(us)=2080.3] 
2014-07-10 16:51:25:056 390 sec: 4807290 operations; 12550.9 current ops/sec; [INSERT AverageLatency(us)=827.72] 
14/07/10 16:51:26 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7098, waitTime=2155, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20110 ms, replay 2255 ops.
14/07/10 16:51:26 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7098, waitTime=2155, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20100 ms, replay 2239 ops.
14/07/10 16:51:30 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7245, waitTime=2096, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 10019 ms, replay 2235 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 884 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10063 ms, replay 884 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1399 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10073 ms, replay 1399 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2023 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10041 ms, replay 2023 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1864 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10082 ms, replay 1864 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 10049 ms, replay 1856 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1065 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10034 ms, replay 1065 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 1741 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10057 ms, replay 1741 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2011 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10022 ms, replay 2011 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1984 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014, retrying after 10074 ms, replay 1984 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1569 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10087 ms, replay 1569 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1442 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10094 ms, replay 1442 ops.
14/07/10 16:51:34 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1131 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7331, waitTime=2773, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014, retrying after 10040 ms, replay 1131 ops.
2014-07-10 16:51:35:057 400 sec: 5085139 operations; 27782.12 current ops/sec; [INSERT AverageLatency(us)=915.82] 
14/07/10 16:51:42 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2235 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7534, waitTime=2171, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 10013 ms, replay 2235 ops.
2014-07-10 16:51:45:057 410 sec: 5085139 operations; 0 current ops/sec;  
14/07/10 16:51:47 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2011 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10075 ms, replay 2011 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 1442 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10032 ms, replay 1442 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1399 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10034 ms, replay 1399 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 1984 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014, retrying after 10065 ms, replay 1984 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2023 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10066 ms, replay 2023 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1864 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10083 ms, replay 1864 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 1741 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10050 ms, replay 1741 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1569 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10069 ms, replay 1569 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 884 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10050 ms, replay 884 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1065 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 10044 ms, replay 1065 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 10088 ms, replay 1856 ops.
14/07/10 16:51:47 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1131 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7600, waitTime=3188, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014, retrying after 10089 ms, replay 1131 ops.
14/07/10 16:51:48 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7652, waitTime=2078, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20070 ms, replay 2255 ops.
14/07/10 16:51:48 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7652, waitTime=2078, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20023 ms, replay 2239 ops.
14/07/10 16:51:53 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014
2014-07-10 16:51:55:069 420 sec: 5129731 operations; 4453.86 current ops/sec; [INSERT AverageLatency(us)=3384.85] 
14/07/10 16:51:58 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:51:58 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:51:58 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:51:59 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:51:59 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:51:59 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 1984 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014, retrying after 20099 ms, replay 1984 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1131 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014, retrying after 20197 ms, replay 1131 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2011 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20164 ms, replay 2011 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 1856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 20011 ms, replay 1856 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 1864 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20062 ms, replay 1864 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2023 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20180 ms, replay 2023 ops.
14/07/10 16:51:59 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 1569 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7930, waitTime=2043, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20083 ms, replay 1569 ops.
2014-07-10 16:52:05:069 430 sec: 5363614 operations; 23388.3 current ops/sec; [INSERT AverageLatency(us)=2001.81] 
14/07/10 16:52:10 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8305, waitTime=2075, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20007 ms, replay 2255 ops.
14/07/10 16:52:10 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8305, waitTime=2075, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20144 ms, replay 2239 ops.
2014-07-10 16:52:15:070 440 sec: 5581513 operations; 21787.72 current ops/sec; [UPDATE AverageLatency(us)=2156491] [INSERT AverageLatency(us)=406.57] [CLEANUP AverageLatency(us)=2156611] 
14/07/10 16:52:23 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 1856 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 20021 ms, replay 1856 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 1984 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014, retrying after 20193 ms, replay 1984 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 1864 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20094 ms, replay 1864 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2115 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 10052 ms, replay 2115 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 1569 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20024 ms, replay 1569 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2239 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 10087 ms, replay 2239 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 1131 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014, retrying after 20011 ms, replay 1131 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2023 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20017 ms, replay 2023 ops.
14/07/10 16:52:23 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2011 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20109 ms, replay 2011 ops.
2014-07-10 16:52:25:070 450 sec: 5581587 operations; 7.4 current ops/sec;  [INSERT AverageLatency(us)=114891.84]  
14/07/10 16:52:30 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20062 ms, replay 2255 ops.
14/07/10 16:52:31 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 2239 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44883 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20182 ms, replay 2239 ops.
14/07/10 16:52:35 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2239 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 10002 ms, replay 2239 ops.
14/07/10 16:52:35 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2115 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 10038 ms, replay 2115 ops.
2014-07-10 16:52:35:071 460 sec: 5581587 operations; 0 current ops/sec;    
2014-07-10 16:52:45:071 470 sec: 5581587 operations; 0 current ops/sec;    
14/07/10 16:52:45 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 1856 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44888 remote=slave1/9.1.143.59:60020] on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014, retrying after 20195 ms, replay 1856 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2115 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 20091 ms, replay 2115 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2239 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014, retrying after 20173 ms, replay 2239 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2011 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20109 ms, replay 2011 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2023 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20084 ms, replay 2023 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 1131 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014, retrying after 20117 ms, replay 1131 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 1984 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014, retrying after 20038 ms, replay 1984 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 1864 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20089 ms, replay 1864 ops.
14/07/10 16:52:45 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 1569 ops, last exception: java.io.IOException: Unexpected closed connection on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014, retrying after 20198 ms, replay 1569 ops.
14/07/10 16:52:53 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2255 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8754, waitTime=2497, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014, retrying after 20120 ms, replay 2255 ops.
14/07/10 16:52:53 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 failed 2239 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8754, waitTime=2497, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014, retrying after 20047 ms, replay 2239 ops.
2014-07-10 16:52:55:072 480 sec: 5581607 operations; 2 current ops/sec;  [INSERT AverageLatency(us)=1646510.3]  
14/07/10 16:52:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2725 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014, retrying after 10093 ms, replay 2725 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2494 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10051 ms, replay 2494 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 10073 ms, replay 2300 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2272 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014, retrying after 10094 ms, replay 2272 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2201 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014, retrying after 10048 ms, replay 2201 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2902 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014, retrying after 10083 ms, replay 2902 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10028 ms, replay 2280 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014, retrying after 10080 ms, replay 2244 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2256 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10087 ms, replay 2256 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2235 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014, retrying after 10056 ms, replay 2235 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1129 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10046 ms, replay 1129 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 309 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:11 PDT 2014, retrying after 10005 ms, replay 309 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 1662 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014, retrying after 10023 ms, replay 1662 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2199 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 10015 ms, replay 2199 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2294 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014, retrying after 10084 ms, replay 2294 ops.
14/07/10 16:52:58 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2794 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8771, waitTime=2794, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014, retrying after 10041 ms, replay 2794 ops.
2014-07-10 16:53:05:072 490 sec: 5799927 operations; 21832 current ops/sec;  [INSERT AverageLatency(us)=939.61]  
14/07/10 16:53:05 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:53:05 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:36 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:38 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:40 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:50:41 PDT 2014
14/07/10 16:53:06 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:51:31 PDT 2014
14/07/10 16:53:09 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014
14/07/10 16:53:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2494 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10077 ms, replay 2494 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2272 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014, retrying after 10070 ms, replay 2272 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2294 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014, retrying after 10023 ms, replay 2294 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 10062 ms, replay 2300 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2235 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014, retrying after 10017 ms, replay 2235 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1129 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10088 ms, replay 1129 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2201 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014, retrying after 10010 ms, replay 2201 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014
14/07/10 16:53:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2794 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014, retrying after 10049 ms, replay 2794 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 10030 ms, replay 2280 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2902 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014, retrying after 10038 ms, replay 2902 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2244 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014, retrying after 10001 ms, replay 2244 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 1662 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014, retrying after 10092 ms, replay 1662 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2199 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 10041 ms, replay 2199 ops.
14/07/10 16:53:10 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 309 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9260, waitTime=2445, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:11 PDT 2014, retrying after 10034 ms, replay 309 ops.
2014-07-10 16:53:15:087 500 sec: 6176837 operations; 37634.55 current ops/sec; [UPDATE AverageLatency(us)=3632297] [INSERT AverageLatency(us)=1837.17] [CLEANUP AverageLatency(us)=3632870] 
14/07/10 16:53:15 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:49 PDT 2014
14/07/10 16:53:15 INFO client.AsyncProcess: #14, table=usertable, attempt=18/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:49:46 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:08 PDT 2014
14/07/10 16:53:21 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:06 PDT 2014
14/07/10 16:53:22 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014
14/07/10 16:53:23 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 1662 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9656, waitTime=2571, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014, retrying after 20011 ms, replay 1662 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 1129 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9656, waitTime=2571, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 20103 ms, replay 1129 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2272 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9656, waitTime=2571, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014, retrying after 20099 ms, replay 2272 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2494 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9656, waitTime=2571, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014, retrying after 20097 ms, replay 2494 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2300 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9656, waitTime=2571, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 20134 ms, replay 2300 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 309 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9668, waitTime=2572, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:11 PDT 2014, retrying after 20000 ms, replay 309 ops.
14/07/10 16:53:23 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2199 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9668, waitTime=2572, rpcTimetout=2000 on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014, retrying after 20116 ms, replay 2199 ops.
2014-07-10 16:53:25:088 510 sec: 6504103 operations; 32726.6 current ops/sec;  [INSERT AverageLatency(us)=2056.78]  
2014-07-10 16:53:35:088 520 sec: 6536608 operations; 3250.17 current ops/sec;  [INSERT AverageLatency(us)=440.8]  
14/07/10 16:53:43 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:12 PDT 2014
14/07/10 16:53:43 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014
14/07/10 16:53:43 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:10 PDT 2014
14/07/10 16:53:43 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:09 PDT 2014
14/07/10 16:53:43 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014
14/07/10 16:53:44 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:11 PDT 2014
14/07/10 16:53:44 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405063953770, tracking started Thu Jul 10 16:52:07 PDT 2014
2014-07-10 16:53:45:088 530 sec: 6647426 operations; 11081.8 current ops/sec;  [INSERT AverageLatency(us)=4323.91]  
2014-07-10 16:53:55:089 540 sec: 6956262 operations; 30880.51 current ops/sec;  [INSERT AverageLatency(us)=533.69]  
2014-07-10 16:54:05:089 550 sec: 7392016 operations; 43575.4 current ops/sec; [UPDATE AverageLatency(us)=19752239.5] [INSERT AverageLatency(us)=641.48] [CLEANUP AverageLatency(us)=19752253] 
2014-07-10 16:54:15:090 560 sec: 7708919 operations; 31687.13 current ops/sec;  [INSERT AverageLatency(us)=449.4]  
2014-07-10 16:54:25:090 570 sec: 8094646 operations; 38572.7 current ops/sec; [UPDATE AverageLatency(us)=6855620] [INSERT AverageLatency(us)=388.52] [CLEANUP AverageLatency(us)=6855634] 
2014-07-10 16:54:35:091 580 sec: 8449204 operations; 35452.25 current ops/sec; [UPDATE AverageLatency(us)=4472611] [INSERT AverageLatency(us)=418.31] [CLEANUP AverageLatency(us)=4472628.5] 
2014-07-10 16:54:45:092 590 sec: 8718955 operations; 26972.4 current ops/sec; [UPDATE AverageLatency(us)=6218372] [INSERT AverageLatency(us)=378.94] [CLEANUP AverageLatency(us)=6218384] 
2014-07-10 16:54:55:092 600 sec: 9075110 operations; 35615.5 current ops/sec; [UPDATE AverageLatency(us)=4152081.33] [INSERT AverageLatency(us)=296.96] [CLEANUP AverageLatency(us)=4152093] 
2014-07-10 16:55:05:093 610 sec: 9363963 operations; 28882.41 current ops/sec; [UPDATE AverageLatency(us)=1900839] [INSERT AverageLatency(us)=290.66] [CLEANUP AverageLatency(us)=1900854] 
2014-07-10 16:55:15:093 620 sec: 9602192 operations; 23822.9 current ops/sec; [UPDATE AverageLatency(us)=4426093] [INSERT AverageLatency(us)=270.09] [CLEANUP AverageLatency(us)=4426105.5] 
2014-07-10 16:55:25:094 630 sec: 9626987 operations; 2479.25 current ops/sec;  [INSERT AverageLatency(us)=279.33]  
2014-07-10 16:55:35:094 640 sec: 9626987 operations; 0 current ops/sec;    
2014-07-10 16:55:45:095 650 sec: 9626987 operations; 0 current ops/sec;    
2014-07-10 16:55:55:095 660 sec: 9802269 operations; 17528.2 current ops/sec; [UPDATE AverageLatency(us)=37955455] [INSERT AverageLatency(us)=1100.34] [CLEANUP AverageLatency(us)=37955466] 
2014-07-10 16:56:03:575 668 sec: 10000000 operations; 23317.33 current ops/sec; [UPDATE AverageLatency(us)=954505.2] [INSERT AverageLatency(us)=74.48] [CLEANUP AverageLatency(us)=954516.6] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405036563
1405036563
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
