++ ls caseresult/ -ltr
++ wc -l
+ filename=case17
+ mkdir caseresult/case17
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case17
+ TEN=10
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=5000000
+ number_of_threads=20
+ number_of_records=5000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case17.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' all == all ']'
+ all=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ true
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 45.4910 seconds

0 row(s) in 0.8210 seconds

0 row(s) in 0.0830 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', DATA_BLOCK_ENCODING=>'\''DIFF'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'DATA_BLOCK_ENCODING=>'\''DIFF'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case17/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case17/create_1.script
/home/hadoop/git/physical_design/caseresult/case17/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case17/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 1.7690 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404656004
1404656004
++ echo /home/hadoop/git/physical_design/caseresult/case17/load_1.dat
+ ./ld 5000000 20 /home/hadoop/git/physical_design/caseresult/case17/load_1.dat
Loading workload...
Starting test.
2014-07-06 07:13:24:728 0 sec: 0 operations; 
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:13:25 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x21415036, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:13:25 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x21415036 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:13:25 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:13:25 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 07:13:25 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c000c3e000d, negotiated timeout = 90000
2014-07-06 07:13:34:877 10 sec: 277044 operations; 27297.66 current ops/sec; [INSERT AverageLatency(us)=316.32] 
2014-07-06 07:13:44:880 20 sec: 277044 operations; 0 current ops/sec;  
2014-07-06 07:13:54:881 30 sec: 277044 operations; 0 current ops/sec;  
2014-07-06 07:14:04:881 40 sec: 277044 operations; 0 current ops/sec;  
2014-07-06 07:14:14:882 50 sec: 441404 operations; 16434.36 current ops/sec; [INSERT AverageLatency(us)=1562.86] 
14/07/06 07:14:23 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2458 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10051 ms, replay 2458 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2370 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10074 ms, replay 2370 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2391 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10028 ms, replay 2391 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2529 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10063 ms, replay 2529 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2496 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10054 ms, replay 2496 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10065 ms, replay 2442 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2425 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10024 ms, replay 2425 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2477 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10027 ms, replay 2477 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2341 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10077 ms, replay 2341 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2423 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=603, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10030 ms, replay 2423 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2385 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=622, waitTime=2012, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10075 ms, replay 2385 ops.
14/07/06 07:14:23 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=622, waitTime=2012, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10096 ms, replay 2414 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2458 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10033 ms, replay 2458 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2305 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10006 ms, replay 2305 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10034 ms, replay 2442 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2524 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10038 ms, replay 2524 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2436 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10034 ms, replay 2436 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10015 ms, replay 2361 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2470 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10079 ms, replay 2470 ops.
14/07/06 07:14:24 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2438 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=624, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10045 ms, replay 2438 ops.
2014-07-06 07:14:24:882 60 sec: 441404 operations; 0 current ops/sec;  
14/07/06 07:14:25 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2476 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10084 ms, replay 2476 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2360 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10017 ms, replay 2360 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10079 ms, replay 2398 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2439 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10063 ms, replay 2439 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10040 ms, replay 2443 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10089 ms, replay 2414 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2417 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10000 ms, replay 2417 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2458 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10001 ms, replay 2458 ops.
14/07/06 07:14:25 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2437 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=632, waitTime=3515, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10055 ms, replay 2437 ops.
2014-07-06 07:14:34:883 70 sec: 441404 operations; 0 current ops/sec;  
14/07/06 07:14:36 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2477 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10004 ms, replay 2477 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2423 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10032 ms, replay 2423 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2370 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10075 ms, replay 2370 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2341 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10021 ms, replay 2341 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2391 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10025 ms, replay 2391 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2496 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10057 ms, replay 2496 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2529 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10076 ms, replay 2529 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2425 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10009 ms, replay 2425 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2442 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10088 ms, replay 2442 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2458 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:34405 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014, retrying after 10031 ms, replay 2458 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2361 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10027 ms, replay 2361 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2305 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10086 ms, replay 2305 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2414 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10035 ms, replay 2414 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2385 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10095 ms, replay 2385 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2414 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10027 ms, replay 2414 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2398 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10082 ms, replay 2398 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2476 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10007 ms, replay 2476 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2439 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10041 ms, replay 2439 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2437 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10086 ms, replay 2437 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2443 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10011 ms, replay 2443 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2360 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10051 ms, replay 2360 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2458 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10067 ms, replay 2458 ops.
14/07/06 07:14:36 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2417 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10064 ms, replay 2417 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2470 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10054 ms, replay 2470 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2438 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 10037 ms, replay 2438 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2524 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10013 ms, replay 2524 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2458 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10026 ms, replay 2458 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2436 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 10034 ms, replay 2436 ops.
14/07/06 07:14:37 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2442 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 10094 ms, replay 2442 ops.
2014-07-06 07:14:44:884 80 sec: 441404 operations; 0 current ops/sec;  
14/07/06 07:14:46 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:46 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:27 PDT 2014
14/07/06 07:14:47 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:14:47 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:14:47 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:14:49 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014
14/07/06 07:14:49 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2439 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20103 ms, replay 2439 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2305 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 20000 ms, replay 2305 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2360 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20121 ms, replay 2360 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 20098 ms, replay 2398 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2385 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20192 ms, replay 2385 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2417 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 20040 ms, replay 2417 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2437 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20034 ms, replay 2437 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20125 ms, replay 2443 ops.
14/07/06 07:14:49 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2458 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=796, waitTime=2301, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20017 ms, replay 2458 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2438 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014, retrying after 20048 ms, replay 2438 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 20174 ms, replay 2442 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2470 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 20079 ms, replay 2470 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2436 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 20046 ms, replay 2436 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2524 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014, retrying after 20195 ms, replay 2524 ops.
14/07/06 07:14:50 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2458 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=829, waitTime=3093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014, retrying after 20128 ms, replay 2458 ops.
2014-07-06 07:14:54:884 90 sec: 624548 operations; 18314.4 current ops/sec; [INSERT AverageLatency(us)=3265.06] 
2014-07-06 07:15:04:885 100 sec: 1089452 operations; 46485.75 current ops/sec; [INSERT AverageLatency(us)=830.64] 
14/07/06 07:15:09 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:10 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:31 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:32 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014
14/07/06 07:15:11 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:13:33 PDT 2014
2014-07-06 07:15:14:916 110 sec: 1458219 operations; 36762.74 current ops/sec; [INSERT AverageLatency(us)=2194.2] 
2014-07-06 07:15:25:292 120 sec: 1610708 operations; 14696.32 current ops/sec; [INSERT AverageLatency(us)=318.14] 
2014-07-06 07:15:35:293 130 sec: 1610708 operations; 0 current ops/sec;  
2014-07-06 07:15:45:388 140 sec: 1732804 operations; 12094.7 current ops/sec; [INSERT AverageLatency(us)=1422.18] 
2014-07-06 07:15:55:590 150 sec: 2136660 operations; 39585.96 current ops/sec; [INSERT AverageLatency(us)=966.73] 
2014-07-06 07:16:05:643 160 sec: 2423116 operations; 28494.58 current ops/sec; [INSERT AverageLatency(us)=552.45] 
14/07/06 07:16:06 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2123, waitTime=2640, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:12 PDT 2014, retrying after 10087 ms, replay 2428 ops.
14/07/06 07:16:06 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2439 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2123, waitTime=2640, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:11 PDT 2014, retrying after 10081 ms, replay 2439 ops.
14/07/06 07:16:06 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2434 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2123, waitTime=2640, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:11 PDT 2014, retrying after 10005 ms, replay 2434 ops.
2014-07-06 07:16:15:643 170 sec: 2465380 operations; 4226.4 current ops/sec; [INSERT AverageLatency(us)=2847.47] 
14/07/06 07:16:18 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:12 PDT 2014
14/07/06 07:16:18 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:11 PDT 2014
14/07/06 07:16:18 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:15:11 PDT 2014
2014-07-06 07:16:25:644 180 sec: 2573388 operations; 10799.72 current ops/sec; [INSERT AverageLatency(us)=2816.73] 
2014-07-06 07:16:35:646 190 sec: 2852679 operations; 27923.52 current ops/sec; [INSERT AverageLatency(us)=989.84] 
2014-07-06 07:16:45:788 201 sec: 3254087 operations; 39578.78 current ops/sec; [INSERT AverageLatency(us)=845.13] 
2014-07-06 07:16:55:788 211 sec: 3510118 operations; 25603.1 current ops/sec; [UPDATE AverageLatency(us)=7973952] [INSERT AverageLatency(us)=604.36] [CLEANUP AverageLatency(us)=7974178] 
2014-07-06 07:17:05:789 221 sec: 3589950 operations; 7982.4 current ops/sec; [UPDATE AverageLatency(us)=10613051] [INSERT AverageLatency(us)=593] [CLEANUP AverageLatency(us)=10613886] 
2014-07-06 07:17:17:335 232 sec: 3625886 operations; 3117.01 current ops/sec;  [INSERT AverageLatency(us)=5638.19]  
2014-07-06 07:17:27:374 242 sec: 3697958 operations; 7167.06 current ops/sec;  [INSERT AverageLatency(us)=2056.37]  
2014-07-06 07:17:37:374 252 sec: 3721438 operations; 2348 current ops/sec;  [INSERT AverageLatency(us)=2816.23]  
2014-07-06 07:17:47:383 262 sec: 3730830 operations; 938.45 current ops/sec;  [INSERT AverageLatency(us)=992.94]  
2014-07-06 07:17:57:383 272 sec: 3730830 operations; 0 current ops/sec;    
2014-07-06 07:18:07:394 282 sec: 3730830 operations; 0 current ops/sec;    
2014-07-06 07:18:17:397 292 sec: 3730830 operations; 0 current ops/sec;    
14/07/06 07:18:20 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2480 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10084 ms, replay 2480 ops.
14/07/06 07:18:22 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2424 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014, retrying after 10001 ms, replay 2424 ops.
14/07/06 07:18:22 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2465 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3305, waitTime=2242, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014, retrying after 10047 ms, replay 2465 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10085 ms, replay 2416 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10035 ms, replay 2427 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2402 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10053 ms, replay 2402 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35246 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10087 ms, replay 2398 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2443 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10041 ms, replay 2443 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2408 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10002 ms, replay 2408 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2406 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10025 ms, replay 2406 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2361 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10019 ms, replay 2361 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2438 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10013 ms, replay 2438 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2397 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 10025 ms, replay 2397 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2493 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10080 ms, replay 2493 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2427 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 10042 ms, replay 2427 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2405 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10006 ms, replay 2405 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2441 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10002 ms, replay 2441 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2375 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10064 ms, replay 2375 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2406 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10094 ms, replay 2406 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2461 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 10055 ms, replay 2461 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2428 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10097 ms, replay 2428 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2435 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10010 ms, replay 2435 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2437 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10008 ms, replay 2437 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2397 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10007 ms, replay 2397 ops.
14/07/06 07:18:26 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2415 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10026 ms, replay 2415 ops.
2014-07-06 07:18:27:409 302 sec: 3730830 operations; 0 current ops/sec;    
14/07/06 07:18:30 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 10059 ms, replay 2431 ops.
14/07/06 07:18:30 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10046 ms, replay 2453 ops.
14/07/06 07:18:32 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10058 ms, replay 2398 ops.
14/07/06 07:18:32 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2480 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10023 ms, replay 2480 ops.
14/07/06 07:18:34 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2418 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3343, waitTime=2032, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:35 PDT 2014, retrying after 10028 ms, replay 2418 ops.
14/07/06 07:18:34 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2424 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3343, waitTime=2032, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014, retrying after 10093 ms, replay 2424 ops.
14/07/06 07:18:34 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2475 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3345, waitTime=2136, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10023 ms, replay 2475 ops.
14/07/06 07:18:34 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014
2014-07-06 07:18:37:790 313 sec: 3735526 operations; 452.36 current ops/sec;  [INSERT AverageLatency(us)=20754.88]  
14/07/06 07:18:37 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:18:39 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2437 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10041 ms, replay 2437 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2438 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10067 ms, replay 2438 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10082 ms, replay 2405 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 10060 ms, replay 2397 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10022 ms, replay 2397 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2461 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 10080 ms, replay 2461 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10015 ms, replay 2416 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2408 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10070 ms, replay 2408 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10084 ms, replay 2427 ops.
14/07/06 07:18:39 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 10047 ms, replay 2427 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10031 ms, replay 2428 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10042 ms, replay 2398 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2406 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10083 ms, replay 2406 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10075 ms, replay 2361 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2406 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10082 ms, replay 2406 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 10085 ms, replay 2443 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10096 ms, replay 2441 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2415 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10022 ms, replay 2415 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2493 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10080 ms, replay 2493 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2375 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 10063 ms, replay 2375 ops.
14/07/06 07:18:41 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2435 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3366, waitTime=3825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 10035 ms, replay 2435 ops.
14/07/06 07:18:43 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 10007 ms, replay 2431 ops.
14/07/06 07:18:43 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10044 ms, replay 2453 ops.
14/07/06 07:18:44 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3389, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10049 ms, replay 2398 ops.
14/07/06 07:18:44 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2480 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3389, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20155 ms, replay 2480 ops.
14/07/06 07:18:46 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2418 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:35 PDT 2014, retrying after 10032 ms, replay 2418 ops.
14/07/06 07:18:46 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2475 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 10011 ms, replay 2475 ops.
14/07/06 07:18:46 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2424 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3397, waitTime=2227, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014, retrying after 20075 ms, replay 2424 ops.
2014-07-06 07:18:47:795 323 sec: 3744918 operations; 938.73 current ops/sec;  [INSERT AverageLatency(us)=461.78]  
14/07/06 07:18:51 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20166 ms, replay 2416 ops.
14/07/06 07:18:51 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20039 ms, replay 2397 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2437 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20186 ms, replay 2437 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2375 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20175 ms, replay 2375 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2428 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20152 ms, replay 2428 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20007 ms, replay 2427 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20001 ms, replay 2397 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20113 ms, replay 2405 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2435 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20198 ms, replay 2435 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20121 ms, replay 2427 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2408 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20135 ms, replay 2408 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2415 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20127 ms, replay 2415 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2461 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20098 ms, replay 2461 ops.
14/07/06 07:18:53 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2438 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20130 ms, replay 2438 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2398 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20105 ms, replay 2398 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20074 ms, replay 2406 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2441 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20163 ms, replay 2441 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2431 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20183 ms, replay 2431 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2453 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20154 ms, replay 2453 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2406 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20048 ms, replay 2406 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2493 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20198 ms, replay 2493 ops.
14/07/06 07:18:54 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2443 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20154 ms, replay 2443 ops.
14/07/06 07:18:55 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20166 ms, replay 2398 ops.
14/07/06 07:18:55 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2361 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35305 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20184 ms, replay 2361 ops.
2014-07-06 07:18:57:796 333 sec: 3763702 operations; 1878.21 current ops/sec;  [INSERT AverageLatency(us)=886.08]  
14/07/06 07:18:58 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014
14/07/06 07:18:58 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:35 PDT 2014
14/07/06 07:19:06 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:19:07 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:16:57 PDT 2014
2014-07-06 07:19:07:797 343 sec: 3792991 operations; 2928.61 current ops/sec; [UPDATE AverageLatency(us)=2058102] [INSERT AverageLatency(us)=3899.22] [CLEANUP AverageLatency(us)=2058112] 
14/07/06 07:19:12 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:19:12 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:19:17 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2415 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20153 ms, replay 2415 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2461 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20177 ms, replay 2461 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20057 ms, replay 2398 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2361 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20031 ms, replay 2361 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2408 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20078 ms, replay 2408 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2428 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20195 ms, replay 2428 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2437 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20002 ms, replay 2437 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20124 ms, replay 2427 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20127 ms, replay 2427 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20127 ms, replay 2453 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20014 ms, replay 2431 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2435 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20104 ms, replay 2435 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2441 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20042 ms, replay 2441 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20162 ms, replay 2397 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20049 ms, replay 2406 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2493 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20071 ms, replay 2493 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2375 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20006 ms, replay 2375 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2443 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20051 ms, replay 2443 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2438 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20158 ms, replay 2438 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20048 ms, replay 2405 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20166 ms, replay 2406 ops.
14/07/06 07:19:17 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20190 ms, replay 2398 ops.
2014-07-06 07:19:17:798 353 sec: 3858735 operations; 6574.4 current ops/sec;  [INSERT AverageLatency(us)=3763.4]  
2014-07-06 07:19:27:798 363 sec: 3859848 operations; 111.29 current ops/sec;  [INSERT AverageLatency(us)=1543.41]  
2014-07-06 07:19:38:019 373 sec: 3859848 operations; 0 current ops/sec;    
14/07/06 07:19:40 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2437 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20168 ms, replay 2437 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20054 ms, replay 2427 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2438 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20139 ms, replay 2438 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20188 ms, replay 2405 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2435 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20131 ms, replay 2435 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2408 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20100 ms, replay 2408 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2375 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20117 ms, replay 2375 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2428 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20181 ms, replay 2428 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2461 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20087 ms, replay 2461 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2361 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20047 ms, replay 2361 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20072 ms, replay 2397 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 2441 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20177 ms, replay 2441 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20085 ms, replay 2406 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20042 ms, replay 2406 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20061 ms, replay 2453 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2443 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20141 ms, replay 2443 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20113 ms, replay 2398 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20141 ms, replay 2427 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2415 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20040 ms, replay 2415 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20000 ms, replay 2431 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20009 ms, replay 2398 ops.
14/07/06 07:19:40 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2493 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35338 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20054 ms, replay 2493 ops.
2014-07-06 07:19:48:020 383 sec: 3859848 operations; 0 current ops/sec;    
2014-07-06 07:19:58:021 393 sec: 3859848 operations; 0 current ops/sec;    
14/07/06 07:20:03 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 failed 2437 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20123 ms, replay 2437 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2443 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20104 ms, replay 2443 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 2441 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20174 ms, replay 2441 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20080 ms, replay 2405 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2428 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20082 ms, replay 2428 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20008 ms, replay 2427 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2435 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20091 ms, replay 2435 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2438 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20171 ms, replay 2438 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20141 ms, replay 2398 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2398 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20142 ms, replay 2398 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2415 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20119 ms, replay 2415 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20199 ms, replay 2453 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2427 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20035 ms, replay 2427 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2461 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20196 ms, replay 2461 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20028 ms, replay 2406 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20107 ms, replay 2397 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2408 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20086 ms, replay 2408 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2361 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20184 ms, replay 2361 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2375 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20183 ms, replay 2375 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20091 ms, replay 2431 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2493 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20026 ms, replay 2493 ops.
14/07/06 07:20:03 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 failed 2406 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35397 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20192 ms, replay 2406 ops.
2014-07-06 07:20:08:021 403 sec: 3906808 operations; 4696 current ops/sec; [UPDATE AverageLatency(us)=42610991] [INSERT AverageLatency(us)=2160.08] [CLEANUP AverageLatency(us)=42611002] 
2014-07-06 07:20:18:066 413 sec: 3937210 operations; 3026.58 current ops/sec; [UPDATE AverageLatency(us)=1165039.5] [INSERT AverageLatency(us)=197.67] [CLEANUP AverageLatency(us)=1165051.5] 
14/07/06 07:20:25 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014
14/07/06 07:20:25 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:20:25 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:20:25 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014
14/07/06 07:20:25 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20060 ms, replay 2431 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20067 ms, replay 2428 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20129 ms, replay 2443 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2435 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20182 ms, replay 2435 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #13, table=usertable, attempt=16/35 failed 2397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20018 ms, replay 2397 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2405 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20073 ms, replay 2405 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #3, table=usertable, attempt=16/35 failed 2437 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20079 ms, replay 2437 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2415 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20176 ms, replay 2415 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 failed 2408 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3721, waitTime=2060, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20120 ms, replay 2408 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3730, waitTime=2044, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20043 ms, replay 2398 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3730, waitTime=2044, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20088 ms, replay 2398 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2375 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3730, waitTime=2044, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20021 ms, replay 2375 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 2438 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3730, waitTime=2044, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20081 ms, replay 2438 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3730, waitTime=2044, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20070 ms, replay 2441 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2461 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3735, waitTime=2038, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20178 ms, replay 2461 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #1, table=usertable, attempt=16/35 failed 2406 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3735, waitTime=2038, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20106 ms, replay 2406 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3735, waitTime=2038, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20008 ms, replay 2361 ops.
14/07/06 07:20:25 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2453 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3735, waitTime=2038, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20173 ms, replay 2453 ops.
2014-07-06 07:20:28:072 423 sec: 3974778 operations; 3754.55 current ops/sec;  [INSERT AverageLatency(us)=5037.69]  
2014-07-06 07:20:38:073 433 sec: 3994675 operations; 1989.5 current ops/sec; [UPDATE AverageLatency(us)=587664] [INSERT AverageLatency(us)=114.74] [CLEANUP AverageLatency(us)=587674] 
14/07/06 07:20:47 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35462 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20151 ms, replay 2397 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #13, table=usertable, attempt=17/35 failed 2435 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20139 ms, replay 2435 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 failed 2438 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20107 ms, replay 2438 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 failed 2453 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20182 ms, replay 2453 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 failed 2415 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20182 ms, replay 2415 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20046 ms, replay 2443 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #20, table=usertable, attempt=17/35 failed 2408 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20155 ms, replay 2408 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20018 ms, replay 2428 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #3, table=usertable, attempt=17/35 failed 2437 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20020 ms, replay 2437 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 failed 2461 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20103 ms, replay 2461 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2375 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20053 ms, replay 2375 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20176 ms, replay 2398 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #1, table=usertable, attempt=17/35 failed 2406 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20059 ms, replay 2406 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20090 ms, replay 2398 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 failed 2431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20139 ms, replay 2431 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20031 ms, replay 2361 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2405 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20089 ms, replay 2405 ops.
14/07/06 07:20:47 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3772, waitTime=2438, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20158 ms, replay 2441 ops.
2014-07-06 07:20:48:074 443 sec: 3994675 operations; 0 current ops/sec;    
2014-07-06 07:20:58:074 453 sec: 3994675 operations; 0 current ops/sec;    
2014-07-06 07:21:08:075 463 sec: 3994675 operations; 0 current ops/sec;    
14/07/06 07:21:09 INFO client.AsyncProcess: #13, table=usertable, attempt=18/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:35470 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014, retrying after 20009 ms, replay 2397 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20006 ms, replay 2428 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #4, table=usertable, attempt=18/35 failed 2461 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014, retrying after 20013 ms, replay 2461 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #10, table=usertable, attempt=18/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20066 ms, replay 2361 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #3, table=usertable, attempt=18/35 failed 2437 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20031 ms, replay 2437 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #12, table=usertable, attempt=18/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20150 ms, replay 2441 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #4, table=usertable, attempt=18/35 failed 2453 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20032 ms, replay 2453 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #14, table=usertable, attempt=18/35 failed 2443 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20112 ms, replay 2443 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #10, table=usertable, attempt=18/35 failed 2431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20045 ms, replay 2431 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #13, table=usertable, attempt=18/35 failed 2435 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20101 ms, replay 2435 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #1, table=usertable, attempt=18/35 failed 2406 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20119 ms, replay 2406 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #10, table=usertable, attempt=18/35 failed 2415 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20106 ms, replay 2415 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #5, table=usertable, attempt=18/35 failed 2438 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20024 ms, replay 2438 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #19, table=usertable, attempt=18/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014, retrying after 20045 ms, replay 2398 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #6, table=usertable, attempt=18/35 failed 2398 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014, retrying after 20013 ms, replay 2398 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 failed 2375 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20125 ms, replay 2375 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #20, table=usertable, attempt=18/35 failed 2408 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20031 ms, replay 2408 ops.
14/07/06 07:21:10 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 failed 2405 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3792, waitTime=2888, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20141 ms, replay 2405 ops.
2014-07-06 07:21:18:076 473 sec: 3994675 operations; 0 current ops/sec;    
2014-07-06 07:21:28:076 483 sec: 3994675 operations; 0 current ops/sec;    
14/07/06 07:21:30 INFO client.AsyncProcess: #13, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:22 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #4, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #15, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #3, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #5, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #6, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #4, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:25 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #1, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #2, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #19, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:36 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #14, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:21 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #2, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #10, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:32 INFO client.AsyncProcess: #10, table=usertable, attempt=19/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3818, waitTime=2023, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20164 ms, replay 2361 ops.
14/07/06 07:21:32 INFO client.AsyncProcess: #20, table=usertable, attempt=19/35 failed 2408 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3818, waitTime=2023, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20013 ms, replay 2408 ops.
14/07/06 07:21:32 INFO client.AsyncProcess: #10, table=usertable, attempt=19/35 failed 2431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3818, waitTime=2023, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20008 ms, replay 2431 ops.
14/07/06 07:21:32 INFO client.AsyncProcess: #13, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
14/07/06 07:21:33 INFO client.AsyncProcess: #12, table=usertable, attempt=19/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3828, waitTime=2223, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20165 ms, replay 2441 ops.
2014-07-06 07:21:38:210 493 sec: 4103369 operations; 10725.68 current ops/sec;  [INSERT AverageLatency(us)=22681.99]  
2014-07-06 07:21:48:421 503 sec: 4269591 operations; 16278.72 current ops/sec; [UPDATE AverageLatency(us)=10003192] [INSERT AverageLatency(us)=557.54] [CLEANUP AverageLatency(us)=10003203] 
14/07/06 07:21:55 INFO client.AsyncProcess: #20, table=usertable, attempt=20/35 failed 2408 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3978, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20100 ms, replay 2408 ops.
14/07/06 07:21:55 INFO client.AsyncProcess: #10, table=usertable, attempt=20/35 failed 2431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3978, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014, retrying after 20126 ms, replay 2431 ops.
14/07/06 07:21:55 INFO client.AsyncProcess: #10, table=usertable, attempt=20/35 failed 2361 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3978, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014, retrying after 20100 ms, replay 2361 ops.
14/07/06 07:21:56 INFO client.AsyncProcess: #12, table=usertable, attempt=20/35 failed 2441 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3986, waitTime=3261, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014, retrying after 20107 ms, replay 2441 ops.
2014-07-06 07:21:58:438 513 sec: 4367885 operations; 9812.72 current ops/sec; [UPDATE AverageLatency(us)=9322756] [INSERT AverageLatency(us)=756.46] [CLEANUP AverageLatency(us)=9322771] 
2014-07-06 07:22:08:438 523 sec: 4432093 operations; 6420.8 current ops/sec;  [INSERT AverageLatency(us)=1338.19]  
14/07/06 07:22:16 INFO client.AsyncProcess: #20, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014
14/07/06 07:22:16 INFO client.AsyncProcess: #10, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:23 PDT 2014
14/07/06 07:22:16 INFO client.AsyncProcess: #10, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:41 PDT 2014
14/07/06 07:22:17 INFO client.AsyncProcess: #12, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1404655636510, tracking started Sun Jul 06 07:17:09 PDT 2014
2014-07-06 07:22:18:439 533 sec: 4649998 operations; 21788.32 current ops/sec; [UPDATE AverageLatency(us)=1628773.4] [INSERT AverageLatency(us)=4278.58] [CLEANUP AverageLatency(us)=1628784.4] 
2014-07-06 07:22:28:440 543 sec: 4830075 operations; 18005.9 current ops/sec;  [INSERT AverageLatency(us)=290.5]  
2014-07-06 07:22:38:441 553 sec: 4896932 operations; 6685.03 current ops/sec; [UPDATE AverageLatency(us)=4832492] [INSERT AverageLatency(us)=697.19] [CLEANUP AverageLatency(us)=4832502] 
2014-07-06 07:22:48:442 563 sec: 4975407 operations; 7846.72 current ops/sec; [UPDATE AverageLatency(us)=3242923.25] [INSERT AverageLatency(us)=317.38] [CLEANUP AverageLatency(us)=3242936] 
2014-07-06 07:22:51:979 567 sec: 5000000 operations; 6953.07 current ops/sec; [UPDATE AverageLatency(us)=490237] [INSERT AverageLatency(us)=174.54] [CLEANUP AverageLatency(us)=490250] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404656573
1404656573
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo 'random read...'
random read...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1404656583
1404656583
++ echo /home/hadoop/git/physical_design/caseresult/case17/random_read_1.dat
+ ./random_read 5000000 20 /home/hadoop/git/physical_design/caseresult/case17/random_read_1.dat
Loading workload...
Starting test.
2014-07-06 07:23:05:081 0 sec: 0 operations; 
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:23:05 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x4ef888ea, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:23:05 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x4ef888ea connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:23:05 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:23:05 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 07:23:05 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c000a87000b, negotiated timeout = 90000
2014-07-06 07:23:15:084 10 sec: 47105 operations; 4709.09 current ops/sec; [READ AverageLatency(us)=4208.27] 
2014-07-06 07:23:25:096 20 sec: 143755 operations; 9653.42 current ops/sec; [READ AverageLatency(us)=2060.96] 
2014-07-06 07:23:35:097 30 sec: 297563 operations; 15379.26 current ops/sec; [READ AverageLatency(us)=1298.46] 
2014-07-06 07:23:45:097 40 sec: 461448 operations; 16388.5 current ops/sec; [READ AverageLatency(us)=1215.13] 
2014-07-06 07:23:55:098 50 sec: 633488 operations; 17202.28 current ops/sec; [READ AverageLatency(us)=1157.39] 
2014-07-06 07:24:05:099 60 sec: 811853 operations; 17834.72 current ops/sec; [READ AverageLatency(us)=1115.99] 
2014-07-06 07:24:15:099 70 sec: 979862 operations; 16800.9 current ops/sec; [READ AverageLatency(us)=1185.2] 
2014-07-06 07:24:25:101 80 sec: 1145524 operations; 16562.89 current ops/sec; [READ AverageLatency(us)=1202.21] 
2014-07-06 07:24:35:102 90 sec: 1315081 operations; 16955.7 current ops/sec; [READ AverageLatency(us)=1174.4] 
2014-07-06 07:24:45:102 100 sec: 1485740 operations; 17064.19 current ops/sec; [READ AverageLatency(us)=1166.72] 
2014-07-06 07:24:55:103 110 sec: 1653322 operations; 16756.52 current ops/sec; [READ AverageLatency(us)=1188.23] 
2014-07-06 07:25:05:104 120 sec: 1826547 operations; 17320.77 current ops/sec; [READ AverageLatency(us)=1149.45] 
2014-07-06 07:25:15:105 130 sec: 2000593 operations; 17402.86 current ops/sec; [READ AverageLatency(us)=1143.89] 
2014-07-06 07:25:25:106 140 sec: 2169894 operations; 16928.41 current ops/sec; [READ AverageLatency(us)=1176.15] 
2014-07-06 07:25:35:106 150 sec: 2338301 operations; 16840.7 current ops/sec; [READ AverageLatency(us)=1182.42] 
2014-07-06 07:25:45:107 160 sec: 2508075 operations; 16975.7 current ops/sec; [READ AverageLatency(us)=1169.08] 
2014-07-06 07:25:55:108 170 sec: 2679215 operations; 17112.29 current ops/sec; [READ AverageLatency(us)=1167.06] 
2014-07-06 07:26:05:108 180 sec: 2847092 operations; 16787.7 current ops/sec; [READ AverageLatency(us)=1186.1] 
2014-07-06 07:26:15:109 190 sec: 3022588 operations; 17547.85 current ops/sec; [READ AverageLatency(us)=1134.38] 
2014-07-06 07:26:25:110 200 sec: 3199884 operations; 17727.83 current ops/sec; [READ AverageLatency(us)=1122.87] 
2014-07-06 07:26:35:110 210 sec: 3366583 operations; 16669.9 current ops/sec; [READ AverageLatency(us)=1194.45] 
2014-07-06 07:26:45:111 220 sec: 3544682 operations; 17808.12 current ops/sec; [READ AverageLatency(us)=1117.78] 
2014-07-06 07:26:55:112 230 sec: 3718491 operations; 17379.16 current ops/sec; [READ AverageLatency(us)=1145.49] 
2014-07-06 07:27:05:112 240 sec: 3889725 operations; 17123.4 current ops/sec; [READ AverageLatency(us)=1162.84] 
2014-07-06 07:27:15:113 250 sec: 4064400 operations; 17465.75 current ops/sec; [READ AverageLatency(us)=1139.84] 
2014-07-06 07:27:25:114 260 sec: 4239404 operations; 17498.65 current ops/sec; [READ AverageLatency(us)=1137.67] 
2014-07-06 07:27:35:114 270 sec: 4409492 operations; 17008.8 current ops/sec; [READ AverageLatency(us)=1170.68] 
2014-07-06 07:27:45:115 280 sec: 4585799 operations; 17628.94 current ops/sec; [READ AverageLatency(us)=1129.33] 
2014-07-06 07:27:55:116 290 sec: 4762693 operations; 17687.63 current ops/sec; [READ AverageLatency(us)=1125.44] 
2014-07-06 07:28:05:116 300 sec: 4931848 operations; 16915.5 current ops/sec; [READ AverageLatency(us)=1177.14] 
2014-07-06 07:28:09:241 304 sec: 5000000 operations; 16521.7 current ops/sec; [UPDATE AverageLatency(us)=15.5] [READ AverageLatency(us)=1069.71] [CLEANUP AverageLatency(us)=171.7] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404656889
1404656889
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloada...
workloada...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404656899
1404656899
++ echo /home/hadoop/git/physical_design/caseresult/case17/workloada_1.dat
+ ./workloada 5000000 20 /home/hadoop/git/physical_design/caseresult/case17/workloada_1.dat
Loading workload...
Starting test.
2014-07-06 07:28:20:037 0 sec: 0 operations; 
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:28:20 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x6b355469, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:28:20 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x6b355469 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:28:20 INFO zookeeper.ClientCnxn: Opening socket connection to server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:28:20 INFO zookeeper.ClientCnxn: Socket connection established to sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, initiating session
14/07/06 07:28:20 INFO zookeeper.ClientCnxn: Session establishment complete on server sceplus-vm48.almaden.ibm.com/9.1.143.58:2181, sessionid = 0x470c000c3e000e, negotiated timeout = 90000
2014-07-06 07:28:30:039 10 sec: 37039 operations; 3702.42 current ops/sec; [INSERT AverageLatency(us)=559.03] [READ AverageLatency(us)=3195.11] 
2014-07-06 07:28:40:041 20 sec: 151206 operations; 11414.42 current ops/sec; [INSERT AverageLatency(us)=16.28] [READ AverageLatency(us)=1806.97] 
2014-07-06 07:28:50:042 30 sec: 266013 operations; 11479.55 current ops/sec; [INSERT AverageLatency(us)=13.3] [READ AverageLatency(us)=1907.26] 
2014-07-06 07:29:00:042 40 sec: 387195 operations; 12118.2 current ops/sec; [INSERT AverageLatency(us)=13.73] [READ AverageLatency(us)=1814.36] 
2014-07-06 07:29:10:049 50 sec: 513312 operations; 12602.88 current ops/sec; [INSERT AverageLatency(us)=13.71] [READ AverageLatency(us)=1716.2] 
2014-07-06 07:29:20:050 60 sec: 654308 operations; 14098.19 current ops/sec; [INSERT AverageLatency(us)=13.07] [READ AverageLatency(us)=1586.7] 
2014-07-06 07:29:30:051 70 sec: 797106 operations; 14279.8 current ops/sec; [INSERT AverageLatency(us)=13.23] [READ AverageLatency(us)=1533.64] 
2014-07-06 07:29:40:051 80 sec: 932660 operations; 13554.04 current ops/sec; [INSERT AverageLatency(us)=20.15] [READ AverageLatency(us)=1635.96] 
2014-07-06 07:29:50:052 90 sec: 997859 operations; 6519.25 current ops/sec; [INSERT AverageLatency(us)=40.66] [READ AverageLatency(us)=3398.09] 
2014-07-06 07:30:00:053 100 sec: 1089825 operations; 9195.68 current ops/sec; [INSERT AverageLatency(us)=12.83] [READ AverageLatency(us)=2410.21] 
2014-07-06 07:30:10:054 110 sec: 1221968 operations; 13212.98 current ops/sec; [INSERT AverageLatency(us)=12.35] [READ AverageLatency(us)=1672.42] 
2014-07-06 07:30:20:054 120 sec: 1342183 operations; 12021.5 current ops/sec; [INSERT AverageLatency(us)=13.39] [READ AverageLatency(us)=1839.94] 
2014-07-06 07:30:30:055 130 sec: 1468043 operations; 12584.74 current ops/sec; [INSERT AverageLatency(us)=21.78] [READ AverageLatency(us)=1758.89] 
2014-07-06 07:30:40:057 140 sec: 1585230 operations; 11716.36 current ops/sec; [INSERT AverageLatency(us)=19.15] [READ AverageLatency(us)=1886.36] 
2014-07-06 07:30:50:058 150 sec: 1676133 operations; 9089.39 current ops/sec; [INSERT AverageLatency(us)=18.74] [READ AverageLatency(us)=2414.54] 
2014-07-06 07:31:00:058 160 sec: 1777944 operations; 10181.1 current ops/sec; [INSERT AverageLatency(us)=73.31] [READ AverageLatency(us)=2175.64] 
2014-07-06 07:31:10:075 170 sec: 1877227 operations; 9911.45 current ops/sec; [INSERT AverageLatency(us)=41.64] [READ AverageLatency(us)=2230.36] 
2014-07-06 07:31:20:087 180 sec: 1933440 operations; 5614.56 current ops/sec; [INSERT AverageLatency(us)=86.06] [READ AverageLatency(us)=3929.26] 
2014-07-06 07:31:30:091 190 sec: 1971901 operations; 3844.56 current ops/sec; [INSERT AverageLatency(us)=36.04] [READ AverageLatency(us)=2403.35] 
2014-07-06 07:31:40:092 200 sec: 1971901 operations; 0 current ops/sec;   
2014-07-06 07:31:50:097 210 sec: 1971901 operations; 0 current ops/sec;   
2014-07-06 07:32:02:591 222 sec: 1971907 operations; 0.48 current ops/sec;  [READ AverageLatency(us)=35370238.67] 
2014-07-06 07:32:12:592 232 sec: 2116853 operations; 14493.15 current ops/sec; [INSERT AverageLatency(us)=22.49] [READ AverageLatency(us)=5781.29] 
2014-07-06 07:32:22:592 242 sec: 2264616 operations; 14776.3 current ops/sec; [INSERT AverageLatency(us)=21.31] [READ AverageLatency(us)=1492.83] 
2014-07-06 07:32:32:593 252 sec: 2421918 operations; 15728.63 current ops/sec; [INSERT AverageLatency(us)=18.64] [READ AverageLatency(us)=1385.81] 
2014-07-06 07:32:42:594 262 sec: 2583900 operations; 16196.58 current ops/sec; [INSERT AverageLatency(us)=14.71] [READ AverageLatency(us)=1377.55] 
2014-07-06 07:32:52:595 272 sec: 2750373 operations; 16645.64 current ops/sec; [INSERT AverageLatency(us)=14.05] [READ AverageLatency(us)=1324.84] 
2014-07-06 07:33:02:596 282 sec: 2847318 operations; 9693.53 current ops/sec; [INSERT AverageLatency(us)=24.86] [READ AverageLatency(us)=2284.24] 
2014-07-06 07:33:12:597 292 sec: 2986171 operations; 13883.91 current ops/sec; [INSERT AverageLatency(us)=17.73] [READ AverageLatency(us)=1588.58] 
2014-07-06 07:33:22:597 302 sec: 3140634 operations; 15446.3 current ops/sec; [INSERT AverageLatency(us)=15.51] [READ AverageLatency(us)=1428.85] 
2014-07-06 07:33:32:598 312 sec: 3287466 operations; 14681.73 current ops/sec; [INSERT AverageLatency(us)=19.21] [READ AverageLatency(us)=1503.25] 
2014-07-06 07:33:42:599 322 sec: 3435209 operations; 14772.82 current ops/sec; [INSERT AverageLatency(us)=19.12] [READ AverageLatency(us)=1496.31] 
2014-07-06 07:33:52:601 332 sec: 3596888 operations; 16164.67 current ops/sec; [INSERT AverageLatency(us)=17.84] [READ AverageLatency(us)=1362.51] 
2014-07-06 07:34:02:601 342 sec: 3742603 operations; 14571.5 current ops/sec; [INSERT AverageLatency(us)=26.8] [READ AverageLatency(us)=1515.37] 
2014-07-06 07:34:12:602 352 sec: 3871731 operations; 12911.51 current ops/sec; [INSERT AverageLatency(us)=27.21] [READ AverageLatency(us)=1709.58] 
2014-07-06 07:34:22:603 362 sec: 4038117 operations; 16636.94 current ops/sec; [INSERT AverageLatency(us)=19.41] [READ AverageLatency(us)=1327.45] 
2014-07-06 07:34:32:604 372 sec: 4207423 operations; 16928.91 current ops/sec; [INSERT AverageLatency(us)=16.89] [READ AverageLatency(us)=1303.73] 
2014-07-06 07:34:42:605 382 sec: 4374624 operations; 16718.43 current ops/sec; [INSERT AverageLatency(us)=16.39] [READ AverageLatency(us)=1320.97] 
2014-07-06 07:34:52:605 392 sec: 4542287 operations; 16766.3 current ops/sec; [INSERT AverageLatency(us)=17.61] [READ AverageLatency(us)=1317.45] 
2014-07-06 07:35:02:606 402 sec: 4689913 operations; 14761.12 current ops/sec; [INSERT AverageLatency(us)=18.81] [READ AverageLatency(us)=1477.85] 
2014-07-06 07:35:12:607 412 sec: 4803905 operations; 11398.06 current ops/sec; [INSERT AverageLatency(us)=27.16] [READ AverageLatency(us)=1966.04] 
2014-07-06 07:35:22:608 422 sec: 4955590 operations; 15168.5 current ops/sec; [INSERT AverageLatency(us)=15] [READ AverageLatency(us)=1457.25] 
2014-07-06 07:35:27:004 426 sec: 5000000 operations; 10100.07 current ops/sec; [UPDATE AverageLatency(us)=169839.1] [INSERT AverageLatency(us)=19.18] [READ AverageLatency(us)=1548.25] [CLEANUP AverageLatency(us)=170037.45] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404657327
1404657327
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadb...
workloadb...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404657337
1404657337
++ echo /home/hadoop/git/physical_design/caseresult/case17/workloadb_1.dat
+ ./workloadb 5000000 20 /home/hadoop/git/physical_design/caseresult/case17/workloadb_1.dat
Loading workload...
Starting test.
2014-07-06 07:35:38:970 0 sec: 0 operations; 
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:35:39 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0xfaaf84c, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:35:39 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0xfaaf84c connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:35:39 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:35:39 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 07:35:39 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c000a87000c, negotiated timeout = 90000
2014-07-06 07:35:48:973 10 sec: 38382 operations; 3836.67 current ops/sec; [INSERT AverageLatency(us)=665.31] [READ AverageLatency(us)=4038.87] 
2014-07-06 07:35:58:975 20 sec: 187363 operations; 14895.12 current ops/sec; [INSERT AverageLatency(us)=24.36] [READ AverageLatency(us)=2457.61] 
2014-07-06 07:36:08:976 30 sec: 323154 operations; 13577.74 current ops/sec; [INSERT AverageLatency(us)=21.29] [READ AverageLatency(us)=2892.79] 
2014-07-06 07:36:18:976 40 sec: 381035 operations; 5788.1 current ops/sec; [INSERT AverageLatency(us)=25.79] [READ AverageLatency(us)=6558.56] 
2014-07-06 07:36:28:977 50 sec: 555418 operations; 17436.56 current ops/sec; [INSERT AverageLatency(us)=18.31] [READ AverageLatency(us)=2295.28] 
2014-07-06 07:36:39:106 60 sec: 729049 operations; 17141.97 current ops/sec; [INSERT AverageLatency(us)=16.25] [READ AverageLatency(us)=2307.61] 
2014-07-06 07:36:49:107 70 sec: 804435 operations; 7537.85 current ops/sec; [INSERT AverageLatency(us)=16.68] [READ AverageLatency(us)=5237.89] 
2014-07-06 07:36:59:108 80 sec: 938996 operations; 13454.75 current ops/sec; [INSERT AverageLatency(us)=15.14] [READ AverageLatency(us)=2979.28] 
2014-07-06 07:37:09:109 90 sec: 1009214 operations; 7021.8 current ops/sec; [INSERT AverageLatency(us)=17.61] [READ AverageLatency(us)=5632.64] 
2014-07-06 07:37:19:109 100 sec: 1130661 operations; 12143.49 current ops/sec; [INSERT AverageLatency(us)=15.34] [READ AverageLatency(us)=3190.45] 
2014-07-06 07:37:29:110 110 sec: 1236061 operations; 10538.95 current ops/sec; [INSERT AverageLatency(us)=19.23] [READ AverageLatency(us)=3832.45] 
2014-07-06 07:37:39:110 120 sec: 1347672 operations; 11161.1 current ops/sec; [INSERT AverageLatency(us)=21.39] [READ AverageLatency(us)=3519.74] 
2014-07-06 07:37:49:111 130 sec: 1515602 operations; 16791.32 current ops/sec; [INSERT AverageLatency(us)=18.61] [READ AverageLatency(us)=2305.73] 
2014-07-06 07:37:59:112 140 sec: 1686315 operations; 17069.59 current ops/sec; [INSERT AverageLatency(us)=29.35] [READ AverageLatency(us)=2370.94] 
2014-07-06 07:38:09:245 150 sec: 1845610 operations; 15720.42 current ops/sec; [INSERT AverageLatency(us)=22.85] [READ AverageLatency(us)=2467.3] 
2014-07-06 07:38:19:246 160 sec: 1979849 operations; 13422.56 current ops/sec; [INSERT AverageLatency(us)=22.35] [READ AverageLatency(us)=2992.44] 
2014-07-06 07:38:31:091 172 sec: 2090765 operations; 9363.95 current ops/sec; [INSERT AverageLatency(us)=40.28] [READ AverageLatency(us)=3773.31] 
2014-07-06 07:38:41:092 182 sec: 2224344 operations; 13356.56 current ops/sec; [INSERT AverageLatency(us)=24.43] [READ AverageLatency(us)=3326.68] 
2014-07-06 07:38:51:093 192 sec: 2320908 operations; 9655.43 current ops/sec; [INSERT AverageLatency(us)=50.17] [READ AverageLatency(us)=4093.23] 
2014-07-06 07:39:01:093 202 sec: 2443272 operations; 12236.4 current ops/sec; [INSERT AverageLatency(us)=31.42] [READ AverageLatency(us)=3223.03] 
2014-07-06 07:39:11:094 212 sec: 2616907 operations; 17361.76 current ops/sec; [INSERT AverageLatency(us)=25.44] [READ AverageLatency(us)=2260.06] 
2014-07-06 07:39:21:095 222 sec: 2729545 operations; 11262.67 current ops/sec; [INSERT AverageLatency(us)=36.75] [READ AverageLatency(us)=3493.38] 
2014-07-06 07:39:31:226 232 sec: 2863953 operations; 13267 current ops/sec; [INSERT AverageLatency(us)=19.74] [READ AverageLatency(us)=2966.82] 
2014-07-06 07:39:41:227 242 sec: 3029894 operations; 16592.44 current ops/sec; [INSERT AverageLatency(us)=18.73] [READ AverageLatency(us)=2395.16] 
2014-07-06 07:39:51:228 252 sec: 3197483 operations; 16757.22 current ops/sec; [INSERT AverageLatency(us)=21.46] [READ AverageLatency(us)=2338.15] 
2014-07-06 07:40:01:228 262 sec: 3338645 operations; 14116.2 current ops/sec; [INSERT AverageLatency(us)=14.64] [READ AverageLatency(us)=2818] 
2014-07-06 07:40:11:289 272 sec: 3448290 operations; 10898.02 current ops/sec; [INSERT AverageLatency(us)=22.6] [READ AverageLatency(us)=3625.12] 
2014-07-06 07:40:21:289 282 sec: 3607035 operations; 15874.5 current ops/sec; [INSERT AverageLatency(us)=18.12] [READ AverageLatency(us)=2493.6] 
2014-07-06 07:40:31:295 292 sec: 3768459 operations; 16132.72 current ops/sec; [INSERT AverageLatency(us)=37.95] [READ AverageLatency(us)=2423.89] 
2014-07-06 07:40:41:296 302 sec: 3917518 operations; 14905.9 current ops/sec; [INSERT AverageLatency(us)=25.88] [READ AverageLatency(us)=2634.32] 
2014-07-06 07:40:51:296 312 sec: 4032540 operations; 11501.05 current ops/sec; [INSERT AverageLatency(us)=17.38] [READ AverageLatency(us)=3454.47] 
2014-07-06 07:41:01:304 322 sec: 4201670 operations; 16899.48 current ops/sec; [INSERT AverageLatency(us)=20.3] [READ AverageLatency(us)=2278.95] 
2014-07-06 07:41:11:305 332 sec: 4351933 operations; 15024.8 current ops/sec; [INSERT AverageLatency(us)=20.6] [READ AverageLatency(us)=2680.11] 
2014-07-06 07:41:21:310 342 sec: 4527672 operations; 17565.12 current ops/sec; [INSERT AverageLatency(us)=20.72] [READ AverageLatency(us)=2254.08] 
2014-07-06 07:41:31:311 352 sec: 4675749 operations; 14806.22 current ops/sec; [INSERT AverageLatency(us)=26.21] [READ AverageLatency(us)=2647.72] 
2014-07-06 07:41:41:312 362 sec: 4834360 operations; 15859.51 current ops/sec; [INSERT AverageLatency(us)=14.6] [READ AverageLatency(us)=2494.5] 
2014-07-06 07:41:51:333 372 sec: 4955964 operations; 12134.92 current ops/sec; [INSERT AverageLatency(us)=16.03] [READ AverageLatency(us)=3056.33] 
2014-07-06 07:41:57:376 378 sec: 5000000 operations; 7287.11 current ops/sec; [UPDATE AverageLatency(us)=337912.25] [INSERT AverageLatency(us)=16.58] [READ AverageLatency(us)=3762.31] [CLEANUP AverageLatency(us)=338784.4] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404657718
1404657718
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ true
+ echo workloadc...
workloadc...
+ echo 'start time: '
start time: 
++ date +%s
+ echo 1404657728
1404657728
++ echo /home/hadoop/git/physical_design/caseresult/case17/workloadc_1.dat
+ ./workloadc 5000000 20 /home/hadoop/git/physical_design/caseresult/case17/workloadc_1.dat
Loading workload...
Starting test.
2014-07-06 07:42:10:122 0 sec: 0 operations; 
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/06 07:42:10 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x578ef2b6, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/06 07:42:10 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x578ef2b6 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/06 07:42:10 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/06 07:42:10 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/06 07:42:10 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1470c000a87000d, negotiated timeout = 90000
2014-07-06 07:42:20:125 10 sec: 201334 operations; 20125.35 current ops/sec; [INSERT AverageLatency(us)=139.68] [READ AverageLatency(us)=6715.79] 
2014-07-06 07:42:30:261 20 sec: 404824 operations; 20075.97 current ops/sec; [INSERT AverageLatency(us)=25.25] [READ AverageLatency(us)=9717.34] 
2014-07-06 07:42:40:266 30 sec: 586468 operations; 18155.32 current ops/sec; [INSERT AverageLatency(us)=15.94] [READ AverageLatency(us)=10729.74] 
2014-07-06 07:42:50:267 40 sec: 740221 operations; 15373.76 current ops/sec; [INSERT AverageLatency(us)=28.31] [READ AverageLatency(us)=12242.15] 
2014-07-06 07:43:00:268 50 sec: 893657 operations; 15342.07 current ops/sec; [INSERT AverageLatency(us)=18.63] [READ AverageLatency(us)=13621.54] 
2014-07-06 07:43:10:269 60 sec: 1045807 operations; 15213.48 current ops/sec; [INSERT AverageLatency(us)=17.66] [READ AverageLatency(us)=12806] 
2014-07-06 07:43:20:270 70 sec: 1158747 operations; 11294 current ops/sec; [INSERT AverageLatency(us)=18.09] [READ AverageLatency(us)=16708.87] 
2014-07-06 07:43:30:270 80 sec: 1335070 operations; 17630.54 current ops/sec; [INSERT AverageLatency(us)=21.31] [READ AverageLatency(us)=10985.99] 
2014-07-06 07:43:40:271 90 sec: 1445417 operations; 11033.6 current ops/sec; [INSERT AverageLatency(us)=43.39] [READ AverageLatency(us)=19112.44] 
2014-07-06 07:43:50:272 100 sec: 1540221 operations; 9479.45 current ops/sec; [INSERT AverageLatency(us)=17.53] [READ AverageLatency(us)=20673.36] 
2014-07-06 07:44:00:540 110 sec: 1705497 operations; 16096.22 current ops/sec; [INSERT AverageLatency(us)=28.5] [READ AverageLatency(us)=11808.04] 
2014-07-06 07:44:10:541 120 sec: 1898947 operations; 19343.07 current ops/sec; [INSERT AverageLatency(us)=36.74] [READ AverageLatency(us)=10246.8] 
2014-07-06 07:44:20:542 130 sec: 2079201 operations; 18023.6 current ops/sec; [INSERT AverageLatency(us)=24.03] [READ AverageLatency(us)=10825.24] 
2014-07-06 07:44:30:542 140 sec: 2257645 operations; 17844.4 current ops/sec; [INSERT AverageLatency(us)=24.99] [READ AverageLatency(us)=11014.98] 
2014-07-06 07:44:40:543 150 sec: 2438901 operations; 18123.79 current ops/sec; [INSERT AverageLatency(us)=16.31] [READ AverageLatency(us)=10546] 
2014-07-06 07:44:50:544 160 sec: 2607402 operations; 16848.42 current ops/sec; [INSERT AverageLatency(us)=16.04] [READ AverageLatency(us)=11957.92] 
2014-07-06 07:45:00:545 170 sec: 2814422 operations; 20702 current ops/sec; [INSERT AverageLatency(us)=18.95] [READ AverageLatency(us)=9453.71] 
2014-07-06 07:45:10:545 180 sec: 2975652 operations; 16121.39 current ops/sec; [INSERT AverageLatency(us)=17.64] [READ AverageLatency(us)=12228.22] 
2014-07-06 07:45:20:546 190 sec: 3161247 operations; 18557.64 current ops/sec; [INSERT AverageLatency(us)=15.96] [READ AverageLatency(us)=10550.03] 
2014-07-06 07:45:30:547 200 sec: 3301827 operations; 14056.59 current ops/sec; [INSERT AverageLatency(us)=18.45] [READ AverageLatency(us)=13029.02] 
2014-07-06 07:45:40:563 210 sec: 3411656 operations; 10965.36 current ops/sec; [INSERT AverageLatency(us)=15.8] [READ AverageLatency(us)=17723.42] 
2014-07-06 07:45:50:564 220 sec: 3549557 operations; 13788.72 current ops/sec; [INSERT AverageLatency(us)=27.71] [READ AverageLatency(us)=14946.69] 
2014-07-06 07:46:00:564 230 sec: 3730801 operations; 18124.4 current ops/sec; [INSERT AverageLatency(us)=20.97] [READ AverageLatency(us)=10447.94] 
2014-07-06 07:46:10:565 240 sec: 3901992 operations; 17117.39 current ops/sec; [INSERT AverageLatency(us)=19.32] [READ AverageLatency(us)=11132.65] 
2014-07-06 07:46:20:589 250 sec: 4065206 operations; 16282.32 current ops/sec; [INSERT AverageLatency(us)=18.07] [READ AverageLatency(us)=12425.63] 
2014-07-06 07:46:30:590 260 sec: 4231408 operations; 16618.54 current ops/sec; [INSERT AverageLatency(us)=15.69] [READ AverageLatency(us)=11742.97] 
2014-07-06 07:46:40:601 270 sec: 4392694 operations; 16110.88 current ops/sec; [INSERT AverageLatency(us)=16.93] [READ AverageLatency(us)=11966.85] 
2014-07-06 07:46:50:602 280 sec: 4551215 operations; 15850.51 current ops/sec; [INSERT AverageLatency(us)=21.18] [READ AverageLatency(us)=12636.13] 
2014-07-06 07:47:00:627 290 sec: 4712096 operations; 16047.98 current ops/sec; [INSERT AverageLatency(us)=22.25] [READ AverageLatency(us)=12107.79] 
2014-07-06 07:47:10:629 300 sec: 4868919 operations; 15679.16 current ops/sec; [INSERT AverageLatency(us)=16.48] [READ AverageLatency(us)=12616.16] 
2014-07-06 07:47:20:630 310 sec: 4978565 operations; 10963.5 current ops/sec; [UPDATE AverageLatency(us)=475923.45] [INSERT AverageLatency(us)=27.25] [READ AverageLatency(us)=13230.98] [CLEANUP AverageLatency(us)=476350.55] 
2014-07-06 07:47:25:729 315 sec: 5000000 operations; 4203.77 current ops/sec; [UPDATE AverageLatency(us)=373464.11] [INSERT AverageLatency(us)=11.01] [READ AverageLatency(us)=8623.45] [CLEANUP AverageLatency(us)=373488.78] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1404658047
1404658047
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ let counter=1+1
+ read line
+ set +x
