++ ls caseresult/ -ltr
++ wc -l
+ filename=case76
+ mkdir caseresult/case76
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case76
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case76
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case76.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.7640 seconds

0 row(s) in 2.3780 seconds

0 row(s) in 0.0940 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case76/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case76/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case76/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case76/create_1.script
/home/hadoop/git/physical_design/caseresult/case76/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case76/create_1.script
0 row(s) in 1.5190 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405038265
1405038265
++ echo /home/hadoop/git/physical_design/caseresult/case76/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case76/load_1.dat
Loading workload...
Starting test.
2014-07-10 17:24:26:263 0 sec: 0 operations; 
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 17:24:26 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 17:24:26 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 17:24:26 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:24:26 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 17:24:26 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x147247aa9e9000d, negotiated timeout = 90000
2014-07-10 17:24:36:282 10 sec: 279184 operations; 27862.67 current ops/sec; [INSERT AverageLatency(us)=555.11] 
2014-07-10 17:24:46:282 20 sec: 470840 operations; 19163.68 current ops/sec; [INSERT AverageLatency(us)=584.64] 
2014-07-10 17:24:56:283 30 sec: 472357 operations; 151.68 current ops/sec; [INSERT AverageLatency(us)=12506.85] 
2014-07-10 17:25:06:283 40 sec: 547802 operations; 7544.5 current ops/sec; [INSERT AverageLatency(us)=1768.9] 
2014-07-10 17:25:16:284 50 sec: 943985 operations; 39614.34 current ops/sec; [INSERT AverageLatency(us)=1089.96] 
2014-07-10 17:25:26:284 60 sec: 1268880 operations; 32489.5 current ops/sec; [INSERT AverageLatency(us)=533.2] 
14/07/10 17:25:27 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1573, waitTime=2780, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10028 ms, replay 1942 ops.
14/07/10 17:25:27 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1903 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1573, waitTime=2780, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10098 ms, replay 1903 ops.
14/07/10 17:25:27 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1848 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1573, waitTime=2780, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10023 ms, replay 1848 ops.
2014-07-10 17:25:36:285 70 sec: 1346170 operations; 7728.23 current ops/sec; [INSERT AverageLatency(us)=373.11] 
14/07/10 17:25:40 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1903 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1956, waitTime=2511, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10013 ms, replay 1903 ops.
14/07/10 17:25:40 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1848 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1956, waitTime=2511, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10046 ms, replay 1848 ops.
14/07/10 17:25:40 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1956, waitTime=2511, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 10095 ms, replay 1942 ops.
2014-07-10 17:25:46:285 80 sec: 1346170 operations; 0 current ops/sec;  
14/07/10 17:25:52 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 1942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2222, waitTime=2276, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 20079 ms, replay 1942 ops.
14/07/10 17:25:52 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 1848 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2222, waitTime=2276, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 20171 ms, replay 1848 ops.
14/07/10 17:25:52 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1903 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2222, waitTime=2276, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014, retrying after 20142 ms, replay 1903 ops.
2014-07-10 17:25:56:286 90 sec: 1589982 operations; 24378.76 current ops/sec; [INSERT AverageLatency(us)=1400.09] 
2014-07-10 17:26:06:307 100 sec: 1981996 operations; 39119.25 current ops/sec; [INSERT AverageLatency(us)=804.45] 
14/07/10 17:26:13 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014
14/07/10 17:26:14 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014
14/07/10 17:26:14 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:24:34 PDT 2014
2014-07-10 17:26:16:307 110 sec: 2337148 operations; 35515.2 current ops/sec; [INSERT AverageLatency(us)=1186.13] 
2014-07-10 17:26:26:308 120 sec: 2621499 operations; 28432.26 current ops/sec; [INSERT AverageLatency(us)=625.26] 
2014-07-10 17:26:36:308 130 sec: 2946035 operations; 32453.6 current ops/sec; [INSERT AverageLatency(us)=622.76] 
2014-07-10 17:26:46:309 140 sec: 3047044 operations; 10099.89 current ops/sec; [INSERT AverageLatency(us)=517.39] 
2014-07-10 17:26:56:309 150 sec: 3047044 operations; 0 current ops/sec;  
2014-07-10 17:27:06:310 160 sec: 3047044 operations; 0 current ops/sec;  
2014-07-10 17:27:16:310 170 sec: 3047044 operations; 0 current ops/sec;  
14/07/10 17:27:18 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1511 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10072 ms, replay 1511 ops.
14/07/10 17:27:18 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1484 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56849 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10051 ms, replay 1484 ops.
14/07/10 17:27:18 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56849 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10060 ms, replay 2405 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1523 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:26 PDT 2014, retrying after 10068 ms, replay 1523 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1377 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:26 PDT 2014, retrying after 10010 ms, replay 1377 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 973 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014, retrying after 10041 ms, replay 973 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1101 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014, retrying after 10086 ms, replay 1101 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1280 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014, retrying after 10017 ms, replay 1280 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 851 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:30 PDT 2014, retrying after 10084 ms, replay 851 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 904 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014, retrying after 10011 ms, replay 904 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1082 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014, retrying after 10028 ms, replay 1082 ops.
14/07/10 17:27:23 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 3287 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56850 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014, retrying after 10000 ms, replay 3287 ops.
2014-07-10 17:27:26:310 180 sec: 3047044 operations; 0 current ops/sec;  
14/07/10 17:27:27 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1085 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10087 ms, replay 1085 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1314 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10090 ms, replay 1314 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 923 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:35 PDT 2014, retrying after 10077 ms, replay 923 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1343 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:35 PDT 2014, retrying after 10062 ms, replay 1343 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 3044 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10076 ms, replay 3044 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1307 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10031 ms, replay 1307 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1322 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10029 ms, replay 1322 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1201 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10022 ms, replay 1201 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 934 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10049 ms, replay 934 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1250 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10012 ms, replay 1250 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 957 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10005 ms, replay 957 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1558 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10012 ms, replay 1558 ops.
14/07/10 17:27:27 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1275 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10043 ms, replay 1275 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 453 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014, retrying after 10082 ms, replay 453 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 684 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014, retrying after 10010 ms, replay 684 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 921 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10036 ms, replay 921 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 682 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014, retrying after 10035 ms, replay 682 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 656 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014, retrying after 10094 ms, replay 656 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1083 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10035 ms, replay 1083 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 925 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10066 ms, replay 925 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1400 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10097 ms, replay 1400 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 775 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10060 ms, replay 775 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1034 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10038 ms, replay 1034 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1084 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10083 ms, replay 1084 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1068 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10032 ms, replay 1068 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 3043 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10029 ms, replay 3043 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 648 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10004 ms, replay 648 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 914 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10029 ms, replay 914 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1113 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10006 ms, replay 1113 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1127 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10015 ms, replay 1127 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 641 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10029 ms, replay 641 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 769 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10048 ms, replay 769 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 515 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014, retrying after 10023 ms, replay 515 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 813 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10045 ms, replay 813 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 905 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10073 ms, replay 905 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1076 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10093 ms, replay 1076 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 759 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10043 ms, replay 759 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1910 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014, retrying after 10063 ms, replay 1910 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 924 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10064 ms, replay 924 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 1511 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10034 ms, replay 1511 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 634 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10080 ms, replay 634 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 575 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014, retrying after 10091 ms, replay 575 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1132 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10050 ms, replay 1132 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 824 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014, retrying after 10072 ms, replay 824 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1484 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10034 ms, replay 1484 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 787 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10057 ms, replay 787 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1136 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014, retrying after 10008 ms, replay 1136 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 849 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10015 ms, replay 849 ops.
14/07/10 17:27:28 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2405 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014, retrying after 10060 ms, replay 2405 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 549 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10045 ms, replay 549 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 789 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10024 ms, replay 789 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2736 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10034 ms, replay 2736 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 330 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10024 ms, replay 330 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 287 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10068 ms, replay 287 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 420 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10047 ms, replay 420 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1322 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10061 ms, replay 1322 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 298 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10010 ms, replay 298 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 253 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10009 ms, replay 253 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 631 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10007 ms, replay 631 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 596 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10055 ms, replay 596 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 264 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 10040 ms, replay 264 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 183 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 10049 ms, replay 183 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 491 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10099 ms, replay 491 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 541 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10073 ms, replay 541 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1112 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10095 ms, replay 1112 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2436 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10071 ms, replay 2436 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 208 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10075 ms, replay 208 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 929 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10021 ms, replay 929 ops.
14/07/10 17:27:29 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 383 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56851 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10072 ms, replay 383 ops.
14/07/10 17:27:34 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:30 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:26 PDT 2014
14/07/10 17:27:34 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:26 PDT 2014
14/07/10 17:27:35 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:32 PDT 2014
2014-07-10 17:27:36:311 190 sec: 3089317 operations; 4226.88 current ops/sec; [INSERT AverageLatency(us)=8785.08] 
14/07/10 17:27:37 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:38 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:38 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:35 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:35 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:31 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:23 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:39 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:33 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:39 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:37 PDT 2014
14/07/10 17:27:40 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:34 PDT 2014
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:27:41 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:27:41 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2736 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10060 ms, replay 2736 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 929 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 10007 ms, replay 929 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1322 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10025 ms, replay 1322 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 10081 ms, replay 183 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10084 ms, replay 541 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10053 ms, replay 253 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 330 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10000 ms, replay 330 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 10005 ms, replay 264 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 631 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10001 ms, replay 631 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 596 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10038 ms, replay 596 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 420 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10025 ms, replay 420 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10006 ms, replay 287 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 549 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10036 ms, replay 549 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 10067 ms, replay 789 ops.
14/07/10 17:27:41 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4707, waitTime=2348, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10030 ms, replay 298 ops.
14/07/10 17:27:42 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2436 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4733, waitTime=3352, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 10055 ms, replay 2436 ops.
2014-07-10 17:27:46:311 200 sec: 3311604 operations; 22228.7 current ops/sec; [INSERT AverageLatency(us)=3584.43] 
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 287 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20149 ms, replay 287 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 929 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014, retrying after 20079 ms, replay 929 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2736 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20079 ms, replay 2736 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20085 ms, replay 253 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 596 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 20119 ms, replay 596 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 631 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 20131 ms, replay 631 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 264 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 20002 ms, replay 264 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 330 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20098 ms, replay 330 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 420 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20083 ms, replay 420 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 298 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20034 ms, replay 298 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20017 ms, replay 541 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014, retrying after 20196 ms, replay 183 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014, retrying after 20038 ms, replay 789 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 549 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20081 ms, replay 549 ops.
14/07/10 17:27:53 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1322 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5077, waitTime=2992, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014, retrying after 20014 ms, replay 1322 ops.
14/07/10 17:27:54 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
2014-07-10 17:27:56:312 210 sec: 3533424 operations; 22179.78 current ops/sec; [INSERT AverageLatency(us)=1045.88] 
2014-07-10 17:28:06:312 220 sec: 3829531 operations; 29610.7 current ops/sec; [INSERT AverageLatency(us)=880.09] 
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:41 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:36 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:38 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
14/07/10 17:28:15 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405066324628, tracking started Thu Jul 10 17:26:40 PDT 2014
2014-07-10 17:28:16:313 230 sec: 4305815 operations; 47623.64 current ops/sec; [INSERT AverageLatency(us)=660.81] 
2014-07-10 17:28:26:313 240 sec: 4667182 operations; 36136.7 current ops/sec; [INSERT AverageLatency(us)=450.78] 
2014-07-10 17:28:36:314 250 sec: 5041746 operations; 37452.65 current ops/sec; [INSERT AverageLatency(us)=603.29] 
2014-07-10 17:28:46:314 260 sec: 5345277 operations; 30353.1 current ops/sec; [INSERT AverageLatency(us)=637.89] 
2014-07-10 17:28:56:315 270 sec: 5643395 operations; 29808.82 current ops/sec; [INSERT AverageLatency(us)=444.56] 
2014-07-10 17:29:06:315 280 sec: 6070641 operations; 42724.6 current ops/sec; [INSERT AverageLatency(us)=616.25] 
2014-07-10 17:29:16:316 290 sec: 6401819 operations; 33114.49 current ops/sec; [INSERT AverageLatency(us)=563.46] 
2014-07-10 17:29:26:316 300 sec: 6401839 operations; 2 current ops/sec; [INSERT AverageLatency(us)=3282.95] 
2014-07-10 17:29:36:324 310 sec: 6401839 operations; 0 current ops/sec;  
2014-07-10 17:29:46:324 320 sec: 6555624 operations; 15378.5 current ops/sec; [INSERT AverageLatency(us)=4013.93] 
2014-07-10 17:29:56:325 330 sec: 7046755 operations; 49108.19 current ops/sec; [INSERT AverageLatency(us)=377.13] 
2014-07-10 17:30:06:326 340 sec: 7132783 operations; 8602.8 current ops/sec; [INSERT AverageLatency(us)=412.91] 
2014-07-10 17:30:16:326 350 sec: 7175954 operations; 4316.67 current ops/sec; [INSERT AverageLatency(us)=2345.39] 
2014-07-10 17:30:26:327 360 sec: 7550011 operations; 37405.7 current ops/sec; [INSERT AverageLatency(us)=1233.98] 
2014-07-10 17:30:36:336 370 sec: 7976840 operations; 42640.26 current ops/sec; [UPDATE AverageLatency(us)=4990251] [INSERT AverageLatency(us)=414.86] [CLEANUP AverageLatency(us)=4990413] 
2014-07-10 17:30:46:336 380 sec: 8101850 operations; 12501 current ops/sec;  [INSERT AverageLatency(us)=504.03]  
14/07/10 17:30:48 INFO client.AsyncProcess: #5, waiting for some tasks to finish. Expected max=0, tasksSent=538, tasksDone=537, currentTasksDone=537, retries=142 hasError=false, tableName=usertable
2014-07-10 17:30:56:337 390 sec: 8564790 operations; 46289.37 current ops/sec; [UPDATE AverageLatency(us)=8229885] [INSERT AverageLatency(us)=652.04] [CLEANUP AverageLatency(us)=8232164.5] 
2014-07-10 17:31:06:337 400 sec: 8747498 operations; 18270.8 current ops/sec;  [INSERT AverageLatency(us)=284.03]  
2014-07-10 17:31:16:338 410 sec: 8951080 operations; 20356.16 current ops/sec; [UPDATE AverageLatency(us)=11424812] [INSERT AverageLatency(us)=1310.42] [CLEANUP AverageLatency(us)=11424822] 
2014-07-10 17:31:26:339 420 sec: 9331300 operations; 38022 current ops/sec; [UPDATE AverageLatency(us)=4110325.25] [INSERT AverageLatency(us)=325.59] [CLEANUP AverageLatency(us)=4110335.25] 
2014-07-10 17:31:36:339 430 sec: 9749547 operations; 41820.52 current ops/sec; [UPDATE AverageLatency(us)=2457094.2] [INSERT AverageLatency(us)=238.95] [CLEANUP AverageLatency(us)=2457105.2] 
2014-07-10 17:31:46:340 440 sec: 9859702 operations; 11014.4 current ops/sec; [UPDATE AverageLatency(us)=3984572] [INSERT AverageLatency(us)=446.93] [CLEANUP AverageLatency(us)=3984583.67] 
2014-07-10 17:31:52:260 446 sec: 10000000 operations; 23702.99 current ops/sec; [UPDATE AverageLatency(us)=739338.25] [INSERT AverageLatency(us)=85.87] [CLEANUP AverageLatency(us)=739346.75] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405038712
1405038712
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
