++ ls caseresult/ -ltr
+ filename=case75
+ mkdir caseresult/case75
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case75
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case75
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case75.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.7160 seconds

0 row(s) in 1.3130 seconds

0 row(s) in 0.0800 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\'', CONFIGURATION =>  { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'', '\''hbase.hstore.compactionThreshold'\'' => '\''100000000000000'\'', '\''hbase.server.compactchecker.interval.multiplier'\'' => '\''100000000'\'', '\''hbase.hstore.compaction.max.size'\'' => '\''128'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\'',' ''\''hbase.hstore.compactionThreshold'\''' '=>' ''\''100000000000000'\'',' ''\''hbase.server.compactchecker.interval.multiplier'\''' '=>' ''\''100000000'\'',' ''\''hbase.hstore.compaction.max.size'\''' '=>' ''\''128'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case75/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case75/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case75/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case75/create_1.script
/home/hadoop/git/physical_design/caseresult/case75/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case75/create_1.script
0 row(s) in 1.7270 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405037052
1405037052
++ echo /home/hadoop/git/physical_design/caseresult/case75/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case75/load_1.dat
Loading workload...
Starting test.
2014-07-10 17:04:13:014 0 sec: 0 operations; 
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 17:04:13 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 17:04:13 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:04:13 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 17:04:13 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 17:04:13 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1472468205c0011, negotiated timeout = 90000
2014-07-10 17:04:23:015 10 sec: 258260 operations; 25823.42 current ops/sec; [INSERT AverageLatency(us)=356.92] 
2014-07-10 17:04:33:017 20 sec: 258260 operations; 0 current ops/sec;  
2014-07-10 17:04:43:017 30 sec: 258260 operations; 0 current ops/sec;  
2014-07-10 17:04:53:017 40 sec: 258260 operations; 0 current ops/sec;  
2014-07-10 17:05:03:018 50 sec: 403836 operations; 14556.14 current ops/sec; [INSERT AverageLatency(us)=1498.69] 
2014-07-10 17:05:13:018 60 sec: 624548 operations; 22071.2 current ops/sec; [INSERT AverageLatency(us)=254.35] 
14/07/10 17:05:13 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2832 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=620, waitTime=2134, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10012 ms, replay 2832 ops.
14/07/10 17:05:13 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2835 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=622, waitTime=2371, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10004 ms, replay 2835 ops.
14/07/10 17:05:13 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2848 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=622, waitTime=2371, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10071 ms, replay 2848 ops.
14/07/10 17:05:13 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2785 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=622, waitTime=2371, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10098 ms, replay 2785 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2828 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10001 ms, replay 2828 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2781 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10067 ms, replay 2781 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2839 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 10043 ms, replay 2839 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2857 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10095 ms, replay 2857 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2860 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10073 ms, replay 2860 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10058 ms, replay 2799 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2829 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10014 ms, replay 2829 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2815 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10087 ms, replay 2815 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2831 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10075 ms, replay 2831 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10091 ms, replay 2837 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2859 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10081 ms, replay 2859 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2827 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10076 ms, replay 2827 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2802 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 10034 ms, replay 2802 ops.
14/07/10 17:05:16 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10095 ms, replay 2832 ops.
14/07/10 17:05:17 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2808 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10037 ms, replay 2808 ops.
14/07/10 17:05:17 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44923 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10078 ms, replay 2799 ops.
2014-07-10 17:05:23:019 70 sec: 638636 operations; 1408.66 current ops/sec; [INSERT AverageLatency(us)=205.69] 
14/07/10 17:05:25 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44925 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10028 ms, replay 2832 ops.
14/07/10 17:05:27 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2785 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44925 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10095 ms, replay 2785 ops.
14/07/10 17:05:27 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2848 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44925 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10040 ms, replay 2848 ops.
14/07/10 17:05:27 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2835 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44925 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10064 ms, replay 2835 ops.
2014-07-10 17:05:33:019 80 sec: 638636 operations; 0 current ops/sec;  
14/07/10 17:05:42 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x1472468205c0011, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 17:05:42 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:42 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:42 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:42 INFO util.RetryCounter: Sleeping 1000ms before retry #0...
14/07/10 17:05:42 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:42 INFO util.RetryCounter: Sleeping 1000ms before retry #0...
14/07/10 17:05:42 INFO util.RetryCounter: Sleeping 1000ms before retry #0...
14/07/10 17:05:42 INFO util.RetryCounter: Sleeping 1000ms before retry #0...
2014-07-10 17:05:43:020 90 sec: 638636 operations; 0 current ops/sec;  
14/07/10 17:05:43 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:05:43 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 17:05:44 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x1472468205c0011, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 17:05:44 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:44 INFO util.RetryCounter: Sleeping 2000ms before retry #1...
14/07/10 17:05:44 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:44 INFO util.RetryCounter: Sleeping 2000ms before retry #1...
14/07/10 17:05:44 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:44 INFO util.RetryCounter: Sleeping 2000ms before retry #1...
14/07/10 17:05:44 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 17:05:44 INFO util.RetryCounter: Sleeping 2000ms before retry #1...
14/07/10 17:05:46 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:05:46 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 17:05:46 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1472468205c0011, negotiated timeout = 90000
2014-07-10 17:05:53:020 100 sec: 638636 operations; 0 current ops/sec;  
14/07/10 17:05:54 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2828 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10018 ms, replay 2828 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10003 ms, replay 2832 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2802 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 10016 ms, replay 2802 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2839 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 10077 ms, replay 2839 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2827 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10087 ms, replay 2827 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2831 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10049 ms, replay 2831 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2857 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10098 ms, replay 2857 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20089 ms, replay 2832 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2785 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20180 ms, replay 2785 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2781 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10009 ms, replay 2781 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2848 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20013 ms, replay 2848 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 10043 ms, replay 2837 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2835 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20101 ms, replay 2835 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10025 ms, replay 2799 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2860 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10025 ms, replay 2860 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2815 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10070 ms, replay 2815 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2808 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10098 ms, replay 2808 ops.
14/07/10 17:05:54 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 10035 ms, replay 2799 ops.
14/07/10 17:05:56 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2859 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10050 ms, replay 2859 ops.
14/07/10 17:05:56 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2829 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44929 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 10018 ms, replay 2829 ops.
2014-07-10 17:06:03:021 110 sec: 638636 operations; 0 current ops/sec;  
14/07/10 17:06:06 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2802 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 20029 ms, replay 2802 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2860 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20091 ms, replay 2860 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2831 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20194 ms, replay 2831 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2781 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20088 ms, replay 2781 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2828 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20049 ms, replay 2828 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20088 ms, replay 2837 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20075 ms, replay 2799 ops.
14/07/10 17:06:06 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 20007 ms, replay 2832 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2827 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20032 ms, replay 2827 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2829 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 20188 ms, replay 2829 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2859 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 20010 ms, replay 2859 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2808 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20160 ms, replay 2808 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2799 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20183 ms, replay 2799 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2815 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20199 ms, replay 2815 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2857 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20150 ms, replay 2857 ops.
14/07/10 17:06:08 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2839 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44931 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 20064 ms, replay 2839 ops.
2014-07-10 17:06:13:021 120 sec: 638636 operations; 0 current ops/sec;  
14/07/10 17:06:14 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:14 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:14 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:14 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
2014-07-10 17:06:23:021 130 sec: 751340 operations; 11270.4 current ops/sec; [INSERT AverageLatency(us)=5209.94] 
14/07/10 17:06:28 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:28 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:30 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2827 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20176 ms, replay 2827 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2808 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20006 ms, replay 2808 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2839 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014, retrying after 20089 ms, replay 2839 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2857 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014, retrying after 20023 ms, replay 2857 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2815 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20148 ms, replay 2815 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2859 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 20041 ms, replay 2859 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2799 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014, retrying after 20168 ms, replay 2799 ops.
14/07/10 17:06:30 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2829 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=941, waitTime=2236, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014, retrying after 20180 ms, replay 2829 ops.
2014-07-10 17:06:33:022 140 sec: 878132 operations; 12677.93 current ops/sec; [INSERT AverageLatency(us)=6646.67] 
2014-07-10 17:06:43:030 150 sec: 1065972 operations; 18768.98 current ops/sec; [INSERT AverageLatency(us)=703.6] 
14/07/10 17:06:51 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:15 PDT 2014
14/07/10 17:06:51 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:51 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014
14/07/10 17:06:51 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:19 PDT 2014
14/07/10 17:06:51 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:51 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
14/07/10 17:06:52 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:21 PDT 2014
14/07/10 17:06:52 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:04:20 PDT 2014
2014-07-10 17:06:53:031 160 sec: 1239802 operations; 17381.26 current ops/sec; [INSERT AverageLatency(us)=6554.81] 
2014-07-10 17:07:03:032 170 sec: 1455740 operations; 21593.8 current ops/sec; [INSERT AverageLatency(us)=1287.02] 
2014-07-10 17:07:13:032 180 sec: 1587228 operations; 13147.49 current ops/sec; [INSERT AverageLatency(us)=705.82] 
2014-07-10 17:07:23:033 190 sec: 1587228 operations; 0 current ops/sec;  
2014-07-10 17:07:33:033 200 sec: 1587228 operations; 0 current ops/sec;  
2014-07-10 17:07:43:034 210 sec: 1587228 operations; 0 current ops/sec;  
2014-07-10 17:07:53:034 220 sec: 1609257 operations; 2202.9 current ops/sec; [INSERT AverageLatency(us)=7603.53] 
14/07/10 17:07:54 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2791 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1685, waitTime=2174, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10000 ms, replay 2791 ops.
14/07/10 17:07:58 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2825 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1754, waitTime=2045, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10050 ms, replay 2825 ops.
14/07/10 17:07:58 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1754, waitTime=2045, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:05 PDT 2014, retrying after 10077 ms, replay 2831 ops.
14/07/10 17:07:58 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2819 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1754, waitTime=2045, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10078 ms, replay 2819 ops.
2014-07-10 17:08:03:034 230 sec: 1873684 operations; 26442.7 current ops/sec; [INSERT AverageLatency(us)=2435.77] 
14/07/10 17:08:06 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2791 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1882, waitTime=2168, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10047 ms, replay 2791 ops.
14/07/10 17:08:10 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1912, waitTime=2055, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:05 PDT 2014, retrying after 10053 ms, replay 2831 ops.
14/07/10 17:08:10 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2819 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1912, waitTime=2055, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10015 ms, replay 2819 ops.
14/07/10 17:08:10 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2825 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1912, waitTime=2055, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 10024 ms, replay 2825 ops.
2014-07-10 17:08:13:035 240 sec: 1930036 operations; 5634.64 current ops/sec; [INSERT AverageLatency(us)=1431.87] 
14/07/10 17:08:19 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2791 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2034, waitTime=3500, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20105 ms, replay 2791 ops.
14/07/10 17:08:22 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2074, waitTime=2095, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:05 PDT 2014, retrying after 20016 ms, replay 2831 ops.
14/07/10 17:08:22 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2825 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2074, waitTime=2095, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20148 ms, replay 2825 ops.
14/07/10 17:08:22 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2819 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2074, waitTime=2095, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20118 ms, replay 2819 ops.
2014-07-10 17:08:23:036 250 sec: 2000476 operations; 7044 current ops/sec; [INSERT AverageLatency(us)=1497.62] 
2014-07-10 17:08:33:047 260 sec: 2282236 operations; 28142.23 current ops/sec; [INSERT AverageLatency(us)=564.05] 
2014-07-10 17:08:43:048 270 sec: 2418420 operations; 13617.04 current ops/sec; [INSERT AverageLatency(us)=1248.04] 
14/07/10 17:08:43 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2791 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2356, waitTime=3033, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20119 ms, replay 2791 ops.
14/07/10 17:08:45 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2389, waitTime=2644, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:05 PDT 2014, retrying after 20069 ms, replay 2831 ops.
14/07/10 17:08:45 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2825 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2389, waitTime=2644, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20112 ms, replay 2825 ops.
14/07/10 17:08:45 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2819 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2389, waitTime=2644, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014, retrying after 20135 ms, replay 2819 ops.
14/07/10 17:08:51 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2846 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2460, waitTime=3346, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:56 PDT 2014, retrying after 10094 ms, replay 2846 ops.
2014-07-10 17:08:53:048 280 sec: 2418420 operations; 0 current ops/sec;  
14/07/10 17:09:02 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:56 PDT 2014
2014-07-10 17:09:03:049 290 sec: 2455988 operations; 3756.42 current ops/sec; [INSERT AverageLatency(us)=4519.07] 
14/07/10 17:09:04 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014
14/07/10 17:09:06 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:05 PDT 2014
14/07/10 17:09:06 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014
14/07/10 17:09:06 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:07:02 PDT 2014
2014-07-10 17:09:13:049 300 sec: 2836364 operations; 38037.6 current ops/sec; [INSERT AverageLatency(us)=1784.7] 
2014-07-10 17:09:23:050 310 sec: 3268396 operations; 43198.88 current ops/sec; [INSERT AverageLatency(us)=883.08] 
14/07/10 17:09:30 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3042, waitTime=2984, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 10076 ms, replay 2837 ops.
14/07/10 17:09:30 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3042, waitTime=2984, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 10096 ms, replay 2807 ops.
2014-07-10 17:09:33:050 320 sec: 3526676 operations; 25828 current ops/sec; [INSERT AverageLatency(us)=619.15] 
2014-07-10 17:09:43:051 330 sec: 3620596 operations; 9391.06 current ops/sec; [INSERT AverageLatency(us)=1086.27] 
14/07/10 17:09:43 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3239, waitTime=3019, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 10083 ms, replay 2837 ops.
14/07/10 17:09:43 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3239, waitTime=3019, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 10010 ms, replay 2807 ops.
2014-07-10 17:09:53:052 340 sec: 3784956 operations; 16434.36 current ops/sec; [INSERT AverageLatency(us)=1085.42] 
14/07/10 17:09:56 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3449, waitTime=3213, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20101 ms, replay 2807 ops.
14/07/10 17:09:56 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3449, waitTime=3213, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20054 ms, replay 2837 ops.
2014-07-10 17:10:03:052 350 sec: 3784956 operations; 0 current ops/sec;  
2014-07-10 17:10:13:052 360 sec: 3921140 operations; 13618.4 current ops/sec; [INSERT AverageLatency(us)=1765.18] 
14/07/10 17:10:16 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2854 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2959, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 10072 ms, replay 2854 ops.
14/07/10 17:10:16 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2822 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2959, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:23 PDT 2014, retrying after 10025 ms, replay 2822 ops.
14/07/10 17:10:16 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2780 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2959, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 10075 ms, replay 2780 ops.
14/07/10 17:10:16 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2868 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2959, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 10098 ms, replay 2868 ops.
14/07/10 17:10:18 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3757, waitTime=3211, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20095 ms, replay 2837 ops.
14/07/10 17:10:18 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3757, waitTime=3211, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20046 ms, replay 2807 ops.
2014-07-10 17:10:23:053 370 sec: 4108980 operations; 18782.12 current ops/sec; [INSERT AverageLatency(us)=603.01] 
14/07/10 17:10:28 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:23 PDT 2014
14/07/10 17:10:28 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014
14/07/10 17:10:28 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014
14/07/10 17:10:29 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2854 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3914, waitTime=2138, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 10039 ms, replay 2854 ops.
2014-07-10 17:10:33:054 380 sec: 4430925 operations; 32194.5 current ops/sec; [INSERT AverageLatency(us)=1265.92] 
14/07/10 17:10:39 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2875 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4135, waitTime=2262, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:47 PDT 2014, retrying after 10080 ms, replay 2875 ops.
14/07/10 17:10:39 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4135, waitTime=2262, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:48 PDT 2014, retrying after 10012 ms, replay 2842 ops.
14/07/10 17:10:41 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4163, waitTime=2108, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20044 ms, replay 2837 ops.
14/07/10 17:10:41 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4163, waitTime=2108, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20091 ms, replay 2807 ops.
14/07/10 17:10:41 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2854 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4170, waitTime=2109, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 20026 ms, replay 2854 ops.
2014-07-10 17:10:43:054 390 sec: 4616148 operations; 18520.45 current ops/sec; [INSERT AverageLatency(us)=325.7] 
14/07/10 17:10:51 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2875 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4342, waitTime=2207, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:47 PDT 2014, retrying after 10046 ms, replay 2875 ops.
14/07/10 17:10:51 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4342, waitTime=2207, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:48 PDT 2014, retrying after 10021 ms, replay 2842 ops.
2014-07-10 17:10:53:055 400 sec: 4785204 operations; 16905.6 current ops/sec; [INSERT AverageLatency(us)=842.65] 
2014-07-10 17:11:03:055 410 sec: 4921388 operations; 13617.04 current ops/sec; [INSERT AverageLatency(us)=925.01] 
14/07/10 17:11:03 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4483, waitTime=2946, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20052 ms, replay 2837 ops.
14/07/10 17:11:03 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2807 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4483, waitTime=2946, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20007 ms, replay 2807 ops.
14/07/10 17:11:03 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2854 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4501, waitTime=2046, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 20196 ms, replay 2854 ops.
14/07/10 17:11:03 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4511, waitTime=2004, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:48 PDT 2014, retrying after 20075 ms, replay 2842 ops.
14/07/10 17:11:03 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2875 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4512, waitTime=2164, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:47 PDT 2014, retrying after 20062 ms, replay 2875 ops.
2014-07-10 17:11:13:056 420 sec: 4921388 operations; 0 current ops/sec;  
2014-07-10 17:11:23:056 430 sec: 4921388 operations; 0 current ops/sec;  
14/07/10 17:11:25 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2854 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014, retrying after 20042 ms, replay 2854 ops.
14/07/10 17:11:25 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2807 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20069 ms, replay 2807 ops.
14/07/10 17:11:25 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014, retrying after 20046 ms, replay 2837 ops.
14/07/10 17:11:27 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2875 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:47 PDT 2014, retrying after 20095 ms, replay 2875 ops.
14/07/10 17:11:27 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2842 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:48 PDT 2014, retrying after 20100 ms, replay 2842 ops.
14/07/10 17:11:29 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2795 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:35 PDT 2014, retrying after 10010 ms, replay 2795 ops.
14/07/10 17:11:29 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2790 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:36 PDT 2014, retrying after 10089 ms, replay 2790 ops.
2014-07-10 17:11:33:057 440 sec: 4921388 operations; 0 current ops/sec;  
14/07/10 17:11:40 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:35 PDT 2014
14/07/10 17:11:40 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:36 PDT 2014
2014-07-10 17:11:43:057 450 sec: 5174972 operations; 25355.86 current ops/sec; [INSERT AverageLatency(us)=1593.9] 
14/07/10 17:11:46 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014
14/07/10 17:11:46 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:08:34 PDT 2014
14/07/10 17:11:46 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:24 PDT 2014
14/07/10 17:11:48 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:47 PDT 2014
14/07/10 17:11:48 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:09:48 PDT 2014
2014-07-10 17:11:53:058 460 sec: 5517496 operations; 34252.4 current ops/sec; [INSERT AverageLatency(us)=2165.67] 
14/07/10 17:11:55 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2777 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5064, waitTime=2117, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:59 PDT 2014, retrying after 10037 ms, replay 2777 ops.
14/07/10 17:11:55 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2810 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5064, waitTime=2117, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:11:01 PDT 2014, retrying after 10065 ms, replay 2810 ops.
14/07/10 17:11:55 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2822 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5064, waitTime=2117, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:59 PDT 2014, retrying after 10005 ms, replay 2822 ops.
14/07/10 17:11:55 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5064, waitTime=2117, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:11:00 PDT 2014, retrying after 10058 ms, replay 2856 ops.
2014-07-10 17:12:03:058 470 sec: 5637405 operations; 11989.7 current ops/sec; [INSERT AverageLatency(us)=2464.57] 
14/07/10 17:12:04 INFO client.AsyncProcess: #5, waiting for some tasks to finish. Expected max=0, tasksSent=332, tasksDone=331, currentTasksDone=331, retries=118 hasError=false, tableName=usertable
14/07/10 17:12:07 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:59 PDT 2014
14/07/10 17:12:07 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:11:00 PDT 2014
14/07/10 17:12:07 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:11:01 PDT 2014
14/07/10 17:12:07 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:10:59 PDT 2014
2014-07-10 17:12:13:059 480 sec: 5886293 operations; 24888.8 current ops/sec; [UPDATE AverageLatency(us)=13059337] [INSERT AverageLatency(us)=1764.89] [CLEANUP AverageLatency(us)=13059460] 
2014-07-10 17:12:23:059 490 sec: 5994301 operations; 10799.72 current ops/sec;  [INSERT AverageLatency(us)=1284.6]  
2014-07-10 17:12:33:060 500 sec: 6069437 operations; 7512.85 current ops/sec;  [INSERT AverageLatency(us)=2025.06]  
2014-07-10 17:12:43:060 510 sec: 6304237 operations; 23480 current ops/sec;  [INSERT AverageLatency(us)=831.05]  
2014-07-10 17:12:53:061 520 sec: 6304237 operations; 0 current ops/sec;    
2014-07-10 17:13:03:061 530 sec: 6304237 operations; 0 current ops/sec;    
14/07/10 17:13:12 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2888 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10084 ms, replay 2888 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2831 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10095 ms, replay 2831 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10016 ms, replay 2820 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2829 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10065 ms, replay 2829 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10011 ms, replay 2806 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2796 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10068 ms, replay 2796 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2809 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10083 ms, replay 2809 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2898 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10029 ms, replay 2898 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10031 ms, replay 2820 ops.
14/07/10 17:13:12 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2888 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10043 ms, replay 2888 ops.
2014-07-10 17:13:13:062 540 sec: 6323021 operations; 1878.21 current ops/sec;  [INSERT AverageLatency(us)=3104.95]  
2014-07-10 17:13:23:062 550 sec: 6510861 operations; 18784 current ops/sec;  [INSERT AverageLatency(us)=1297.12]  
14/07/10 17:13:24 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2898 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10089 ms, replay 2898 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10045 ms, replay 2820 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10018 ms, replay 2888 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10047 ms, replay 2820 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2806 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10028 ms, replay 2806 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2829 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10028 ms, replay 2829 ops.
14/07/10 17:13:24 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2796 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6210, waitTime=2069, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10030 ms, replay 2796 ops.
14/07/10 17:13:25 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6219, waitTime=2104, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10018 ms, replay 2888 ops.
14/07/10 17:13:25 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2809 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6219, waitTime=2104, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 10017 ms, replay 2809 ops.
14/07/10 17:13:25 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6219, waitTime=2104, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 10008 ms, replay 2831 ops.
14/07/10 17:13:26 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2892 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6229, waitTime=3118, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:33 PDT 2014, retrying after 10056 ms, replay 2892 ops.
14/07/10 17:13:33 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2828 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6338, waitTime=2037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:40 PDT 2014, retrying after 10099 ms, replay 2828 ops.
14/07/10 17:13:33 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2835 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6338, waitTime=2037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:39 PDT 2014, retrying after 10018 ms, replay 2835 ops.
14/07/10 17:13:33 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2889 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6338, waitTime=2037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:39 PDT 2014, retrying after 10083 ms, replay 2889 ops.
14/07/10 17:13:33 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2809 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6338, waitTime=2037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014, retrying after 10040 ms, replay 2809 ops.
14/07/10 17:13:33 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2874 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6343, waitTime=2001, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014, retrying after 10027 ms, replay 2874 ops.
2014-07-10 17:13:33:063 560 sec: 6755053 operations; 24416.76 current ops/sec;  [INSERT AverageLatency(us)=1021.36]  
14/07/10 17:13:33 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2809 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6344, waitTime=2150, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014, retrying after 10047 ms, replay 2809 ops.
14/07/10 17:13:36 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2806 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6403, waitTime=2026, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20155 ms, replay 2806 ops.
14/07/10 17:13:36 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2829 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6403, waitTime=2026, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20016 ms, replay 2829 ops.
14/07/10 17:13:36 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6403, waitTime=2026, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20062 ms, replay 2820 ops.
14/07/10 17:13:36 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2796 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6403, waitTime=2026, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20178 ms, replay 2796 ops.
14/07/10 17:13:36 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6403, waitTime=2026, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20129 ms, replay 2888 ops.
14/07/10 17:13:37 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2898 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6410, waitTime=2286, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20078 ms, replay 2898 ops.
14/07/10 17:13:37 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2809 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6410, waitTime=2286, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20074 ms, replay 2809 ops.
14/07/10 17:13:37 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6410, waitTime=2286, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20184 ms, replay 2820 ops.
14/07/10 17:13:37 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6410, waitTime=2286, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20173 ms, replay 2831 ops.
14/07/10 17:13:37 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6410, waitTime=2286, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20000 ms, replay 2888 ops.
14/07/10 17:13:38 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2892 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6429, waitTime=2118, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:33 PDT 2014, retrying after 10050 ms, replay 2892 ops.
2014-07-10 17:13:43:063 570 sec: 6921638 operations; 16658.5 current ops/sec;  [INSERT AverageLatency(us)=508.06]  
14/07/10 17:13:43 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:39 PDT 2014
14/07/10 17:13:45 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014
14/07/10 17:13:45 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:39 PDT 2014
14/07/10 17:13:45 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:40 PDT 2014
14/07/10 17:13:45 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014
14/07/10 17:13:45 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:38 PDT 2014
14/07/10 17:13:50 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:33 PDT 2014
2014-07-10 17:13:53:064 580 sec: 7189308 operations; 26764.32 current ops/sec; [UPDATE AverageLatency(us)=2232070] [INSERT AverageLatency(us)=1526.13] [CLEANUP AverageLatency(us)=2236745] 
14/07/10 17:14:01 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 2898 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20012 ms, replay 2898 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2796 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20073 ms, replay 2796 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20101 ms, replay 2888 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20153 ms, replay 2820 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2806 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20036 ms, replay 2806 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2829 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20159 ms, replay 2829 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2831 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20133 ms, replay 2831 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2888 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20031 ms, replay 2888 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2820 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014, retrying after 20151 ms, replay 2820 ops.
14/07/10 17:14:01 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2809 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6776, waitTime=3904, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014, retrying after 20068 ms, replay 2809 ops.
2014-07-10 17:14:03:065 590 sec: 7374679 operations; 18537.1 current ops/sec;  [INSERT AverageLatency(us)=229.89]  
2014-07-10 17:14:13:065 600 sec: 7374679 operations; 0 current ops/sec;    
14/07/10 17:14:22 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014
14/07/10 17:14:22 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014
14/07/10 17:14:22 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014
14/07/10 17:14:22 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014
14/07/10 17:14:22 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014
14/07/10 17:14:22 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014
2014-07-10 17:14:23:066 610 sec: 7398159 operations; 2348 current ops/sec;  [INSERT AverageLatency(us)=10479.47]  
14/07/10 17:14:23 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014
14/07/10 17:14:23 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:19 PDT 2014
14/07/10 17:14:23 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014
14/07/10 17:14:23 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:12:18 PDT 2014
2014-07-10 17:14:33:066 620 sec: 7548326 operations; 15015.2 current ops/sec;  [INSERT AverageLatency(us)=2799.47]  
2014-07-10 17:14:43:066 630 sec: 7806711 operations; 25838.5 current ops/sec;  [INSERT AverageLatency(us)=375.6]  
14/07/10 17:14:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2771 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10057 ms, replay 2771 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2785 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10094 ms, replay 2785 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2833 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10042 ms, replay 2833 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2810 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10023 ms, replay 2810 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2803 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10012 ms, replay 2803 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2836 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10074 ms, replay 2836 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2854 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10068 ms, replay 2854 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2895 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10014 ms, replay 2895 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2779 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10064 ms, replay 2779 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2842 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 10005 ms, replay 2842 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10076 ms, replay 2837 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2828 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10001 ms, replay 2828 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2856 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10010 ms, replay 2856 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2825 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10065 ms, replay 2825 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2867 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10056 ms, replay 2867 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2858 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10098 ms, replay 2858 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2826 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10016 ms, replay 2826 ops.
14/07/10 17:14:50 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 10022 ms, replay 2806 ops.
14/07/10 17:14:52 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2813 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7332, waitTime=3442, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 10098 ms, replay 2813 ops.
14/07/10 17:14:52 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2862 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7332, waitTime=3442, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:57 PDT 2014, retrying after 10087 ms, replay 2862 ops.
2014-07-10 17:14:53:067 640 sec: 7858367 operations; 5165.08 current ops/sec;  [INSERT AverageLatency(us)=151.6]  
14/07/10 17:15:01 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:01 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2828 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7435, waitTime=2149, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10085 ms, replay 2828 ops.
14/07/10 17:15:02 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7435, waitTime=2149, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 10002 ms, replay 2842 ops.
14/07/10 17:15:02 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7435, waitTime=2149, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10052 ms, replay 2856 ops.
14/07/10 17:15:02 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2785 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7435, waitTime=2149, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10037 ms, replay 2785 ops.
14/07/10 17:15:02 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:15:02 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2858 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7435, waitTime=2149, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 10039 ms, replay 2858 ops.
14/07/10 17:15:02 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7453, waitTime=2014, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 10039 ms, replay 2837 ops.
2014-07-10 17:15:03:068 650 sec: 8079079 operations; 22068.99 current ops/sec;  [INSERT AverageLatency(us)=1969.43]  
14/07/10 17:15:04 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2813 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7474, waitTime=2924, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 10087 ms, replay 2813 ops.
14/07/10 17:15:04 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2862 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7474, waitTime=2924, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:57 PDT 2014, retrying after 10085 ms, replay 2862 ops.
2014-07-10 17:15:13:068 660 sec: 8182391 operations; 10331.2 current ops/sec; [UPDATE AverageLatency(us)=76122632] [INSERT AverageLatency(us)=809.89] [CLEANUP AverageLatency(us)=76122644] 
14/07/10 17:15:15 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 20063 ms, replay 2842 ops.
14/07/10 17:15:15 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20085 ms, replay 2856 ops.
14/07/10 17:15:15 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 20179 ms, replay 2837 ops.
14/07/10 17:15:15 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2785 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20158 ms, replay 2785 ops.
14/07/10 17:15:15 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2858 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20011 ms, replay 2858 ops.
14/07/10 17:15:15 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2828 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7617, waitTime=3037, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20028 ms, replay 2828 ops.
14/07/10 17:15:16 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014
14/07/10 17:15:16 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:57 PDT 2014
2014-07-10 17:15:23:069 670 sec: 8431554 operations; 24913.81 current ops/sec; [UPDATE AverageLatency(us)=2268967] [INSERT AverageLatency(us)=744.74] [CLEANUP AverageLatency(us)=2268980] 
2014-07-10 17:15:33:069 680 sec: 8860594 operations; 42904 current ops/sec; [UPDATE AverageLatency(us)=1579454] [INSERT AverageLatency(us)=277.58] [CLEANUP AverageLatency(us)=1579466.5] 
14/07/10 17:15:37 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2828 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20126 ms, replay 2828 ops.
14/07/10 17:15:37 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2858 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20146 ms, replay 2858 ops.
14/07/10 17:15:37 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2856 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20199 ms, replay 2856 ops.
14/07/10 17:15:37 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2837 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 20129 ms, replay 2837 ops.
14/07/10 17:15:37 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2785 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20063 ms, replay 2785 ops.
14/07/10 17:15:37 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2842 ops, last exception: java.io.IOException: Call to slave1/9.1.143.59:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7988, waitTime=2453, rpcTimetout=2000 on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 20191 ms, replay 2842 ops.
2014-07-10 17:15:43:070 690 sec: 8888770 operations; 2817.32 current ops/sec;  [INSERT AverageLatency(us)=1142.45]  
2014-07-10 17:15:53:071 700 sec: 9249927 operations; 36112.09 current ops/sec; [UPDATE AverageLatency(us)=1645465.75] [INSERT AverageLatency(us)=412.32] [CLEANUP AverageLatency(us)=1645483.25] 
14/07/10 17:16:00 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2856 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20032 ms, replay 2856 ops.
14/07/10 17:16:00 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2828 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20195 ms, replay 2828 ops.
14/07/10 17:16:00 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2837 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014, retrying after 20120 ms, replay 2837 ops.
14/07/10 17:16:00 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2858 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20046 ms, replay 2858 ops.
14/07/10 17:16:00 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2785 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014, retrying after 20154 ms, replay 2785 ops.
14/07/10 17:16:00 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2842 ops, last exception: java.net.SocketTimeoutException: Call to slave1/9.1.143.59:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:44933 remote=slave1/9.1.143.59:60020] on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014, retrying after 20175 ms, replay 2842 ops.
2014-07-10 17:16:03:071 710 sec: 9425601 operations; 17567.4 current ops/sec; [UPDATE AverageLatency(us)=886259.67] [INSERT AverageLatency(us)=154.13] [CLEANUP AverageLatency(us)=886274] 
2014-07-10 17:16:13:072 720 sec: 9589715 operations; 16409.76 current ops/sec; [UPDATE AverageLatency(us)=490720] [INSERT AverageLatency(us)=81.23] [CLEANUP AverageLatency(us)=490733] 
14/07/10 17:16:20 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:16:20 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:16:20 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:55 PDT 2014
14/07/10 17:16:20 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
14/07/10 17:16:20 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:56 PDT 2014
14/07/10 17:16:21 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on slave1,60020,1405065110777, tracking started Thu Jul 10 17:13:54 PDT 2014
2014-07-10 17:16:23:073 730 sec: 9669547 operations; 7982.4 current ops/sec;  [INSERT AverageLatency(us)=9132.28]  
2014-07-10 17:16:33:073 740 sec: 10000000 operations; 33045.3 current ops/sec; [UPDATE AverageLatency(us)=732295.75] [INSERT AverageLatency(us)=124.15] [CLEANUP AverageLatency(us)=732310.5] 
2014-07-10 17:16:33:222 740 sec: 10000000 operations; 0 current ops/sec; [UPDATE AverageLatency(us)=402158]  [CLEANUP AverageLatency(us)=402172] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405037793
1405037793
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
